apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
spec:
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
        - name: wireguard
          image: lscr.io/linuxserver/wireguard:latest
          ports:
            - name: wireguard
              containerPort: 51820
          securityContext:
            capabilities:
              add:
                - SYS_MODULE
                - NET_ADMIN
            sysctls:
              - name: net.ipv4.ip_forward
                value: "1"
              - name: net.ipv4.conf.all.forwarding
                value: "1"
              - name: net.ipv4.conf.all.src_valid_mark
                value: "1"