apiVersion: v1
kind: Service
metadata:
  name: wireguard
  labels:
    app: wireguard
spec:
  selector:
    app: wireguard
  type: NodePort
  ports:
    - name: wireguard
      port: 51820
      targetPort: 51820
      protocol: UDP
      nodePort: 30000