apiVersion: apps/v1
kind: Deployment
metadata:
  name: homarr
spec:
  selector:
    matchLabels:
      app: homarr
  template:
    metadata:
      labels:
        app: homarr
    spec:
      containers:
        - name: homarr
          image: ghcr.io/ajnart/homarr:latest
          ports:
            - name: web
              containerPort: 7575
              protocol: TCP