apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sealed-secrets
rules:
  - apiGroups:
      - bitnami.com
    resources:
      - sealedsecrets
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - bitnami.com
    resources:
      - sealedsecrets/status
    verbs:
      - update

  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - watch

  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch