apiVersion: v1
kind: Service
metadata:
  name: sealed-secrets
  labels:
    app: sealed-secrets
  annotations:
    kube-vip.io/loadbalancerIPs: "192.168.1.118"
    prometheus.cluster.starsystem.dev/scrape: "true"
    prometheus.cluster.starsystem.dev/scheme: http
    prometheus.cluster.starsystem.dev/path: /metrics
    prometheus.cluster.starsystem.dev/port: "8001"
spec:
  selector:
    app: sealed-secrets
  type: LoadBalancer
  loadBalancerIP: 192.168.1.118
  ports:
    - name: cert
      port: 8080
      targetPort: 8080
      protocol: TCP