apiVersion: v1
kind: Service
metadata:
  name: sealed-secrets
  labels:
    app: sealed-secrets
  annotations:
    prometheus.cluster.starsystem.dev/scrape: "true"
    prometheus.cluster.starsystem.dev/scheme: http
    prometheus.cluster.starsystem.dev/path: /metrics
    prometheus.cluster.starsystem.dev/port: "8001"
spec:
  selector:
    app: sealed-secrets
  ports:
    - name: metrics
      port: 8081
      targetPort: 8081
      protocol: TCP