apiVersion: v1
kind: Service
metadata:
  name: satisfactory-headless
  labels:
    app: satisfactory
spec:
  clusterIP: None
  selector:
    app: satisfactory
  ports:
    # Satisfactory server
    - port: 7777
      targetPort: 7777
      protocol: TCP
    - port: 7777
      targetPort: 7777
      protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: satisfactory
  labels:
    app: satisfactory
spec:
  selector:
    app: satisfactory
  ports:
    # Satisfactory server
    - port: 7777
      targetPort: 7777
      protocol: TCP
    - port: 7777
      targetPort: 7777
      protocol: UDP