apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nfs-server
spec:
  template:
    spec:
      nodeSelector:
        starsystem.dev/nfs: "true"
      priorityClassName: system-cluster-critical
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: local