apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nfs-server
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                # TODO: make sure this matches, maybe make a separate class just for NFS
                - key: class.nodes.cluster.starsystem.dev
                  operator: In
                  values:
                    - database
      priorityClassName: system-cluster-critical
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: local