apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nfs-server
spec:
  template:
    spec:
      nodeSelector:
        starsystem.dev/nfs: "true"
      priorityClassName: system-cluster-critical
      containers:
        - name: nfs-server
          env:
            # Waits for changes to be commited before replying to requests
            # Not as fast as async mode, but avoids data corruption due to a sudden crash
            - name: SYNC
              value: "true"
            - name: SHARED_DIRECTORY
              value: /export
          resources:
            requests:
              cpu: 100m
              memory: 100M
          volumeMounts:
            - name: data
              mountPath: /export
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Delete
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: local