apiVersion: v1
kind: ConfigMap
metadata:
  name: local-provisioner
data:
  config.json: |
    {
      "database": {
        "nodePathMap": [
          {
            "node": "luna",
            "paths": [
              "/mnt/cluster/databases"
            ]
          }
        ]
      },
      "game": {
        "nodePathMap": [
          {
            "node": "clover",
            "paths": [
              "/games"
            ]
          }
        ]
      },
      "local": {
        "nodePathMap": [
          {
            "node": "luna",
            "paths": [
              "/mnt/cluster"
            ]
          },
          {
            "node": "sol",
            "paths": [
              "/mnt/cluster"
            ]
          }
        ]
      }
    }

  helperPod.yaml: |
    apiVersion: v1
    kind: Pod
    metadata:
      name: local-provisioner-helper
      namespace: storage-system
    spec:
      priorityClassName: system-node-critical
      tolerations:
        - key: node.kubernetes.io/disk-pressure
          operator: Exists
          effect: NoSchedule
      containers:
        - name: helper
          image: rancher/mirrored-library-busybox:1.36.1

  setup: |
    #!/bin/sh
    set -eu
    mkdir -m 0777 -p "${VOL_DIR}"
    chmod 700 "${VOL_DIR}/.."

  teardown: |
    #!/bin/sh
    set -eu
    rm -rf "${VOL_DIR}"