apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config-map.yaml
  - ../../base/local-provisioner
  - storage-class.yaml
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment