apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: database
  annotations:
    defaultVolumeType: local
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: storage.cluster.starsystem.dev/local-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  pathPattern: "{{ .PVC.Name }}"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: game
  annotations:
    defaultVolumeType: local
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: storage.cluster.starsystem.dev/local-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  pathPattern: "{{ .PVC.Name }}"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local
  annotations:
    defaultVolumeType: local
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: storage.cluster.starsystem.dev/local-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  pathPattern: "{{ .PVC.Name }}"