apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vpn-peers
  namespace: starsys-network
  annotations:
    nfs.cluster.starsystem.dev/path: "wireguard"
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi