apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealed-secret.yaml
  - config-map.yaml
  - pvc.yaml
  - ../../base/wgportal
  - ingress-routes.yaml
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment