apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealed-secrets.yaml
  - database.yaml
  - config-map.yaml
  - ../../base/wgportal
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment