apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-lldap
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-lldap
spec:
  selector:
    matchLabels:
      app: postgres
      database: lldap
  template:
    metadata:
      labels:
        app: postgres
        database: lldap
    spec:
      nodeSelector:
        starsystem.dev/database: "true"
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          envFrom:
            - secretRef:
                name: postgres-lldap
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 500Mi
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
        # TODO: prometheus exporter

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-lldap
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-lldap
  # TODO: annotations for prometheus exporter
spec:
  selector:
    app: postgres
    database: lldap
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP