apiVersion: v1
kind: Service
metadata:
  name: nfs-server-headless
  labels:
    app: nfs-server
spec:
  clusterIP: None
  selector:
    app: nfs-server
  ports:
    - name: nfsv4
      port: 2049
      targetPort: 2049
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-server
  labels:
    app: nfs-server
spec:
  selector:
    app: nfs-server
  ports:
    - name: nfsv4
      port: 2049
      targetPort: 2049
      protocol: TCP