apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nfs-server
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Delete
  serviceName: nfs-server-headless
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      containers:
        - name: nfs-server
          image: itsthenetwork/nfs-server-alpine:latest-arm
          securityContext:
            privileged: true
          ports:
            - name: nfsv4
              containerPort: 2049
          env:
            # Waits for changes to be commited before replying to requests
            # Not as fast as async mode, but avoids data corruption due to a sudden crash
            - name: SYNC
              value: "true"
            - name: SHARED_DIRECTORY
              value: /export
          resources:
            requests:
              cpu: 100m
              memory: 100M
          volumeMounts:
            - name: data
              mountPath: /export
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: ""