apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflare-ddns
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ddns
      sourceRef:
        kind: HelmRepository
        name: constellation
      version: ">=1.0.0"
  interval: 10m0s
  releaseName: cloudflare
  targetNamespace: starsys-network
  upgrade:
    force: true
  values:
    common:
      namespace: starsys-network
    pods:
      priorityClassName: starsys-network
    ddns:
      secretName: cloudflare-ddns-config