apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: compsoc-kevin
  namespace: flux-system
spec:
  dependsOn:
    - name: namespaces
    - name: sealed-secrets
  interval: 10m0s
  timeout: 2m0s
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/overlays/compsoc-kevin
  prune: true
  force: true
  wait: true