apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitea
  namespace: flux-system
spec:
  dependsOn:
    - name: namespaces
    - name: crds
    - name: sealed-secrets
    - name: local-provisioner
    - name: nfs-provisioner
    - name: postgres-gitea
  interval: 10m0s
  timeout: 2m0s
  targetNamespace: labs
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/overlays/gitea
  prune: true
  force: true
  wait: true