apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homarr
  namespace: flux-system
spec:
  dependsOn:
    - name: namespaces
    - name: crds
    - name: sealed-secrets
    - name: nfs-provisioner
    - name: lldap
  interval: 10m0s
  timeout: 1m0s
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/overlays/homarr
  prune: true
  force: true
  wait: true