apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lldap
  namespace: flux-system
spec:
  dependsOn:
    - name: crds
    - name: sealed-secrets
    - name: local-provisioner
  interval: 10m0s
  timeout: 2m0s
  targetNamespace: kube-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/lldap
  prune: true
  force: true
  wait: true