apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lldap
  namespace: flux-system
spec:
  dependsOn:
    - name: namespaces
    - name: crds
    - name: sealed-secrets
    - name: local-provisioner
    - name: postgres-lldap
  interval: 10m0s
  timeout: 2m0s
  targetNamespace: database-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/overlays/lldap
  prune: true
  force: true
  wait: true