apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minecraft-router
  namespace: flux-system
spec:
  dependsOn:
    - name: namespaces
    - name: crds
  interval: 10m0s
  timeout: 2m0s
  targetNamespace: games
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/overlays/minecraft-router
  prune: true
  force: true
  wait: true