apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nfs-provisioner
  namespace: flux-system
spec:
  dependsOn:
    - name: namespaces
    - name: nfs-server
  interval: 10m0s
  timeout: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/overlays/nfs-provisioner
  prune: true
  force: true
  wait: true