apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pihole
  namespace: flux-system
spec:
  dependsOn:
    - name: namespaces
    - name: crds
    - name: sealed-secrets
    - name: nfs-provisioner
  interval: 20m0s
  timeout: 1m0s
  targetNamespace: network-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/overlays/pihole
  prune: true
  force: true
  wait: true