apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pihole
  namespace: flux-system
spec:
  suspend: true
  dependsOn:
    - name: namespaces
    - name: sealed-secrets
    - name: nfs-provisioner
    - name: traefik
  interval: 10m0s
  timeout: 30s
  targetNamespace: network-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/overlays/pihole
  prune: true
  force: true
  wait: true