apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres-gitea
  namespace: flux-system
spec:
  dependsOn:
    - name: namespaces
    - name: sealed-secrets
    - name: local-provisioner
  interval: 10m0s
  timeout: 1m0s
  targetNamespace: database-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/overlays/postgres-gitea
  prune: true
  force: true
  wait: true