apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: priority-classes
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./priority-classes
  prune: true
  force: true
  wait: true