apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: satisfactory
  namespace: flux-system
spec:
  suspend: true
  dependsOn:
    - name: namespaces
    - name: local-provisioner
  interval: 10m0s
  timeout: 30s
  targetNamespace: games
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/overlays/satisfactory
  prune: true
  force: true
  wait: true