apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: sealed-secrets
    namespace: flux-system
spec:
    interval: 15m
    path: ./stacks/system/sealed-secrets
    prune: true
    timeout: 2m
    sourceRef:
        kind: GitRepository
        name: flux-system