apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  dependsOn:
    - name: namespaces
  interval: 10m0s
  timeout: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/base/sealed-secrets
  prune: true
  force: true
  wait: true