apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  depends_on:
    - ddns
    - kube-vip
    - local-provisioner
    - nfs-provisioner
    - minecraft-router
    - priority-classes
    - sealed-secrets
    - traefik
    - wireguard
  interval: 10m0s
  timeout: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./tenants
  prune: true
  force: true
  wait: true