apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  dependsOn:
    - name: ddns
    - name: kube-vip
    - name: local-provisioner
    - name: nfs-provisioner
    - name: minecraft-router
    - name: priority-classes
    - name: sealed-secrets
    - name: traefik
    - name: wireguard
  interval: 10m0s
  timeout: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./tenants
  prune: true
  force: true
  wait: true