apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  dependsOn:
    - name: namespaces
    - name: crds
    - name: sealed-secrets
    - name: nfs-provisioner
  interval: 10m0s
  timeout: 2m0s
  targetNamespace: network-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/overlays/traefik
  prune: true
  force: true
  wait: true