apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wg-portal
  namespace: flux-system
spec:
  suspend: true
  dependsOn:
    - name: namespaces
    - name: sealed-secrets
    - name: traefik
    - name: nfs-provisioner
    - name: postgres-operator
  interval: 10m0s
  timeout: 1m0s
  targetNamespace: network-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/overlays/wg-portal
  prune: true
  force: true
  wait: true