apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wireguard-admin
  namespace: flux-system
spec:
  dependsOn:
    - name: namespaces
    - name: local-provisioner
  interval: 10m0s
  timeout: 1m0s
  targetNamespace: network-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/overlays/wireguard-admin
  prune: true
  force: true
  wait: true