# This is the local volume tht serves as the backend to the NFS storage class. The NFS server and provisioner should run on the storage node to be able to access this volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-backend
spec:
  capacity:
    storage: 240Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  local:
    path: /mnt/cluster/nfs
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - sentinel