# Wireguard certificates are kept in this volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wireguard
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  local:
    path: /mnt/cluster/wireguard
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - sentinel