apiVersion: v1
kind: ServiceAccount
metadata:
  name: minecraft-router
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: minecraft-router
subjects:
  - kind: ServiceAccount
    name: minecraft-router
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: minecraft-router
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minecraft-router
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - watch
      - list