---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: ddns-config
  namespace: kube-system
spec:
  encryptedData:
    config.json: AgCmchByt1v7TCByDDrIx4rr9jhZXtasYSk09LAcWG3MPRToIlurujndJ38w9lGZ88t/D7QveV9tedPYOvD6jaqnC+l7sVA5se8Qwo1tfcL0SzHMh2WUpsU7quyZaTTKQyMIzKlZjAPmCckRubmJaVuxk6MEpynWKWJmk6ocqsMrfhg2WZUwDWHoIj76Y4EcUm6TCD0XDUSUyfXqzlEJka0gBwEU/DhSqCNWm7ACUJTse3txAwgRW1Y0HfjCjyTJiHHTr8e9HnBGD5p5D3bU8DH03q7LZ6vjtzWSjqzQgVoNupD/2E5ezImWaVbYpKd8kUWyrH3MX3hC06UEITxLRJ+ZnkX9akdL6QNfpiVvq85YRA7j6qF3fl5U+r2l6VS6VMJnr0YU792+1NlIlrF4rmLOML20o6alQ3cYsfiZR+vtSPPWKOyM9Qgh4hS3jZnHms2FytVmQYwZHW8GjNDDqbz8il+0xXe+5iZygCv3U5X8KSP4hLrINhkZluUHopc8SoEEQ92Oa8014A3FJLUdvBqRISLhg4o5YmIWjPNnwPtf2/SwfWPVKKto6MCbPOlpxrWMfWLkdYMBPSQwFve2iO68Z18Srgxh79iQ6Mwi0rCgJyCbhv6twTC98Dw+tTG//hWyDO6VJ0eT5C4ZJ2J+7ISzjL1zUlqO94y1ctX3jk4abNVQYxDbnA2swbYdhzM43WkhtdXfae8jbtbJLvCNY1/twcQlUpEJfhAE8eib4PiYwlfrZ4q6pWs/EnhycOAzMfEjnFYXUtCR4F/w65KUbgmPUHgcjVSy++xZl0xIJL3yXNvS2st3/5xbuGPQ9yAhtiZYGyGz0dF/0DWAyLQr07dmVk++rSmINRci93vNxUfCsBxCSdH6aTsWAVqXUG21+yvfv1rlazhhub1u8CGPY0jSQk6mjgm3fL26PR0L5ouPI63cmbIuBxxHEDMsGGFphcF8MelGK0bZGlBuZvhc7FFePKFDyLJ1lryKrjHFTWRT/znpaEQLzHamYVLyx0wtSNxYG+qjceVEnqsQvJJIVCrRmLlCFM0TUhdBlBk+GdZkEBgCLPR0NzzUxjW8eVNEefDyPUEOKRCAS1vDqy+fkQ2RpByKSSj74lazDOK4roVO3NixriDVdk1N1y4RhhYkyvy7OWxCm09bl+l2ZTg+2NG9BVtJ83Z8KAgiOaAQk2/4ZKwemcGyWLFTqgIH21WceBtgSGADwVA0i1Ncya7vV0fkbIgDpflpo55U96TnOVILZHfQ5JOfbIyvCRF9Retpq93QxRS3rU81Wk1Vxz8/9SKuwxaqO3cXVoM+9BsbTuOIHYAG59TdqWhGJwDccUQYfXjdP0Gf2EQpavbHKs1+NZq3gsW/iXa5eVZlzHAl16QqIrkyY0q2lqagEIabnyyW0g78djdA7BrfoTaeFUrWQJZrnsJm7fiMYARvLw7DMfvXprMOcVGSWX5Arxs2Vwfy7CZju1ZqI8w8e+j5HDNmzEfU
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: ddns-config
      namespace: kube-system
