---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: ddns-config
  namespace: kube-system
spec:
  encryptedData:
    config.json: AgBKOUuKp6AXqztTM/aEtWeRi44Qs8BgMuoE7EmcCdVULCKcTp71lecBjpc1Uh5SeagjbamBhfu5xZuY7mEb/iModqtIzXXXyqO8n/jK7l3/w+r4Et2omWpKN/09q16bs6Os1d4Vx+S77CrS9LIrVm3fr+n6hjOcBtgI3Q2YChUAqbqeCd7p4+Gq9u1buRo+QCIH97fBYuyf2MNsV5Lq4yKBByP8ERCWzlGO7kLKjDiLyFo+lnLSZW+MZiJ4gCPKg3z6LMwDBSDk6CAQ8J5nCqwSGVno7cslueYdpU37ftoVYUpITi+j9bkLIF0DkLRTN5izA7bTj/BoezCMasY+0uJyzPCW5kXiO8VP/ONshIdR09Rl/h1/hojlm+gFs2VZhz6tQkqhNIdzwdWmy8Mx3VMF3bvhWsYMq6oFuyqAolW3MgRquSoKaKGQ249RQshMdtNO0jTecU1gZ6BnfrdmDiqo2U/x2wRB4UjKBzzmMDvE3aVkCCYhkyY46iT0Po0qzEc+Xy/nBsnYHGku+lDnCqScRjRuRd7aCMcHVYlKhOkyWr+2Vsn3JwPg+ssWrg5CW7Hg4ps7XqjEikzn/dm+yUlYElEvILnnmKPV16ZVLVCBHepv1Uc9rHh5Te87Ycuyifols1qHH2Vf244WyXL1Dd9GeKxBPByqASdHNNSTt+tuhuiglkB/K1vuKkUJqcYHF461xMibzbUlHrcOCzjF/yYSzOhSIHA6vUodD778KD/kP5LXc4/9YLaE6s8KSLoWeKGEsdWjlscFjyqKPIUeQp+E9bsloE1CEli/CqAaTMWjBoem89M04U9zeznBZsp/HpzsdVleayHRpWf5uyWrkDDkWwukcrLnDqJkEhp6YYqnCPoER9z0B5M1QneG35FP6HXFGuek7mh4Y6NLmy+EPD+2WO9JmdmxSu+KoB78x4WTPo/pt6smRUoxhU14RYJrhDZPJvyBKnGXMaB7VaHUxGu/jLpk3T/buw+GwmHeeaiyWTu4IjYXv1OLLlWyy99Qn3+aYypK2eo2YC8LT0gW1gu2yQwmV2ijT1huM6vhGwID2urS/aJxxcWaDZNojc1cj8tIgdFbm7+/vdPWVtqxzduXWjCorLW/8PxyRBIeSs3TDA0l2y7dQBcPBGloXU8RRBsH2iULDuTws6Q3J6TCIUWgVnF1M8pw1ESpOmjGD+s1VqH3LCUV2O85Vwu4VrDly6J7BKNS6k/8zQZhg36GY1gJyRheEh0WOpEUL1UKsFfdT88fnbUFRQVMwnkHqH8AVI9TZVbB5pn3yZEWtBylLu0QIpPfUHFQeysnOHgPyYahrggt5dny01lGHJjDbiJfJo2dj3ffNVI5hkxFYnw8IiwUkZA5/2/VaRYTE62nHvVfKOXPg9iOxETTUiulVhlqjWbCAvLXRHNxsBBhHY9p3qtaIX5lXN25lmtw+ZXFRI6vlp/A5qPxQHVlvKCDX3g30xbXgJBC+zgSkAjtAyjNzCqm
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: ddns-config
      namespace: kube-system
