apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
spec:
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - name: gitea
          image: gitea/gitea:latest
          env:
            - name: GITEA_CUSTOM
              value: /custom
          ports:
            - name: web
              containerPort: 3000
            - name: ssh
              containerPort: 2222
          resources:
            requests:
              cpu: 200m
              memory: 200M
            limits:
              cpu: 400m
              memory: 400M
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: 3000
            initialDelaySeconds: 200
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          volumeMounts:
            - name: data
              mountPath: /var/lib/gitea
            - name: config
              mountPath: /data
            - name: secrets
              mountPath: /custom/conf/app.ini
              subPath: app.ini
              readOnly: true

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: gitea-data
        - name: config
          persistentVolumeClaim:
            claimName: gitea-config
        - name: secrets
          secret:
            secretName: gitea

# TODO: email support
# TODO: traefik route
# TODO: LDAP integration
# TODO: GPG commit signatures
# TOOD: prometheus exporter?