apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-role.yaml
  - service-account.yaml
  - crds.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - middlewares.yaml
  - ingress-routes.yaml