apiVersion: v1
kind: Service
metadata:
  name: traefik
  labels:
    app: traefik
  annotations:
    kube-vip.io/loadbalancerIPs: "192.168.1.119"
    prometheus.cluster.starsystem.dev/scrape: "true"
    prometheus.cluster.starsystem.dev/scheme: http
    prometheus.cluster.starsystem.dev/path: /metrics
    prometheus.cluster.starsystem.dev/port: "8008"
spec:
  selector:
    app: traefik
  loadBalancerIP: 192.168.1.119
  type: LoadBalancer
  ports:
    - name: web
      port: 80
      targetPort: 80
      protocol: TCP
    - name: websecure
      port: 443
      targetPort: 443
      protocol: TCP
    # Used by the internal ping and prometheus services to expose information
    - name: traefik
      port: 8080
      targetPort: 8080
      protocol: TCP