apiVersion: v1
kind: Service
metadata:
  name: traefik
  labels:
    app: traefik
  annotations:
    kube-vip.io/loadbalancerIPs: "192.168.1.99"
    prometheus.cluster.starsystem.dev/scrape: "true"
    prometheus.cluster.starsystem.dev/scheme: http
    prometheus.cluster.starsystem.dev/path: /metrics
    prometheus.cluster.starsystem.dev/port: "8008"
spec:
  selector:
    app: traefik
  loadBalancerIP: 192.168.1.99
  type: LoadBalancer
  ports:
    - name: web
      port: 80
      targetPort: 80
      protocol: TCP
    - name: websecure
      port: 443
      targetPort: 443
      protocol: TCP
    # Used by the internal ping and prometheus services to expose information
    - name: traefik
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
    - name: minecraft
      port: 25565
      targetPort: 25565
      protocol: TCP
    - name: wireguard
      port: 51820
      targetPort: 51820
      protocol: UDP