apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfs-provisioner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nfs-provisioner
subjects:
  - kind: ServiceAccount
    name: nfs-provisioner
roleRef:
  kind: ClusterRole
  name: nfs-provisioner
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nfs-provisioner
rules:
  - apiGroups:
      - ""
    resources: 
      - persistentvolumes
    verbs: 
      - get
      - list
      - watch
      - create
      - patch
      - delete

  - apiGroups:
      - ""
    resources: 
      - persistentvolumeclaims
    verbs: 
      - get
      - list
      - watch
      - update

  - apiGroups: 
      - storage.k8s.io
    resources: 
      - storageclasses
    verbs: 
      - get
      - list
      - watch

  - apiGroups:
      - ""
    resources: 
      - events
    verbs: 
      - get
      - list
      - watch
      - create
      - update
      - patch

  - apiGroups: 
      - storage.k8s.io
    resources: 
      - csinodes
    verbs: 
      - get
      - list
      - watch

  - apiGroups: 
      - ""
    resources: 
      - nodes
    verbs: 
      - get
      - list
      - watch

  - apiGroups: 
      - coordination.k8s.io
    resources: 
      - leases
    verbs: 
      - get
      - list
      - watch
      - create
      - update
      - patch

  - apiGroups: 
      - ""
    resources: 
      - secrets
    verbs: 
      - get