apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: gitea
spec:
  users:
    gitea: []
  databases:
    gitea: gitea
  postgresql:
    version: "16"
  volume:
    size: 1Gi
    storageClass: local