apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
spec:
  template:
    spec:
      containers:
        - name: gitea
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    sleep 30
                    gitea admin auth add-ldap --name=lldap --host=lldap.database-system --port=3890 --security-protocol=unencrypted --bind-dn="cn=gitea,dc=starsystem,dc=dev" --bind-password=cupkar-xUhrit-hixme9 --user-search-base="ou=people,dc=starsystem,cd=dev" --user-filter="(&(objectClass=person)(|(user_id=%[1]s)(mail=%[1]s)))" --admin-filter="(memberOf=cn=gitea_admin,ou=groups,dc=starsystem,dc=dev)" --username-attribute=user_id --firstname-attribute=first_name --surname-attribute=last_name --email-attribute=mail --avatar-attribute=avatar --synchronize-users=true --public-ssh-key-attribute=ssh_pub_key --restricted-filter="(&(objectClass=person)(memberOf=cn=disabled,ou=groups,dc=starsystem,dc=dev))"