apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
spec:
  template:
    spec:
      containers:
        - name: gitea
          envFrom:
            - secretRef:
                name: gitea
          resources:
            requests:
              cpu: 10m
              memory: 200M
            limits:
              memory: 200M
          volumeMounts:
            - name: data
              mountPath: /var/lib/gitea
            - name: config
              mountPath: /etc/gitea
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: gitea-data
        - name: config
          persistentVolumeClaim:
            claimName: gitea-config
# TODO: GPG commit signatures
# TOOD: prometheus exporter?