apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: local-provisioner
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete