apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-vip
data:
  # Virtual IP broadcasting via ARP
  address: "192.168.1.119"
  vip_ddns: "false"
  vip_arp: "true"
  vip_interface: eth0
  # Leader election for Virtual IP broadcasting
  vip_leaderelection: "true"
  vip_leaseduration: "5"
  vip_renewdeadline: "3"
  vip_retryperiod: "1"
  cp_namespace: kube-system
  cp_enable: "true"
  enable_node_labeling: "true"
  # Service load balancing
  svc_enable: "true"
  svc_election: "true" # Leader election per service
  enable_service_security: "true"