apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-vip
spec:
  template:
    spec:
      priorityClassName: system-cluster-critical
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: node-role.kubernetes.io/master
                  operator: Exists
              - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: Exists
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: PreferNoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      containers:
        - name: kubevip
          envFrom:
            - configMapRef:
                name: kube-vip
          resources:
            requests:
              cpu: 10m
              memory: 50M 
            limits:
              memory: 50M