---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: traefik
  namespace: kube-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgBTgIWV0ZJHp6BM/SMJjDaWgxAMEi5ugXM3FaTQ99s6srNFu5pmwaefpbnun9pBjtKsruALHB9xHVmK0zLMYYVr9wr0IprfCqUNaNvWDEtItRCpivDgGB/It70WC9vKggK9CDhbzjb/LUIAgnd9wOmFsnVkbWSyu6ZSj0saiVsZ/emYPcpIvddiPAOjCj20WGnrArvRU1UN1Jc8LwFBuJHLoJCN8quN07VQIveBMBOnFcOEI0GMRo9zBYLY6a7zMH06av6dKm2fefLELMSNu47KNL+xpOtU7J8NK1VmKJIlIqgpn16WMTurvQi6imREAk+tSZLNOgonEMpoVHA0d+7Sde5IoOOljZh0DESZSncICYcRkUFLLqQua6UcCZSRqMtAQ7D8RWaMxLk6fQXoH3+3OMB9nI65ink95E+QF3NhhtaSQSMwHkF7Pe5d1TMJl1XrgH+Pg/SPc6Zn2xqR58XW9uqL3cYIvfwbMtwW3VOFPDaYqZ7BToYBT15LSr+/9loNtPcVouv5QCkk8zZh6Xt+xMFanEqmbqy/lDmIAb9AWNFp7UzlLWmamM06ZVvn43m6QXD3p6l1bc1I1lRb1kNB0ePAYThv2Xl8/qz1GU4B3DqC1GAtIQyZM9uxsS7M2ZSEnZAKEleruhk1I3k765NYwT4ig6CE5jruuJp9BbZ3QBTf1G+INMVi2dNlbPwJkTzSkDDdvNC+yRw5laDfe1B2q7kFhXRc3txy0lsClczNHDZSgCpg4rOS
    CF_ZONE_API_TOKEN: AgBjEDctt8dsSIeRrfOTWlPNz2vlXXJetNQPn0dp49rI8blG+97gOJj8Ksiu3JX+3hisPepMc2CE5brLjXyrKcQzrwGNU7VgAAjBZv5mwBeJGb+wG4fNta2QNlNnEPwmW5ZzdjtCQPEzdWOMxPRWAWtdw7/PCZ/IR86T2aMVDDJ5RHtFEAKram++WQyDaF5vZxSan3MiYWZNjOSxyGbRyYrkz9j2j/qsJZdpdnF5JS7CoiiSEPUUG+Tc7KbnXIH/s0CckWwt0sOEuP/XnQ9V1/TJzFLXpZ2VuoVguJobiLEdmgU3f48/fIu5481HtJg5ZfpjbDLSpZCmtWAXNV/YE1u7YwKnEs4xSFPyTt1sJhJfMVM2+ZwLpHMD+8y2QvvVKdEWYBu9M4ouhpIAIA6/9HLUEb76+4UDiM8sVwFT88YWMQQCK3oB9d+B6vISKMWajlLCbAg6bKb1lmoM4MSvcILUv8KqUfcpfhXvNmjkSfujsAqU1P94t5g57sXfCTKQ6cCQ+lO8IvkhrLIbteSmieOAB33pemb/8vhhKPBxAJtK19S/vBTzYZ2fthQ9EgMSna5whks62RFz4wwneyLD4/ICS9aWqvqcOSCmEfOW1ZG2Pwd1vqdCGWID32PIOZuZRTOjmI0CQilXrEPN/EYWd6519mNfcNyz+qs7fpcSQVaEZpfMDi/a2Na9hrsZznG4yFhx31KXlkcpLrfVgMCtcOzqi3/DxlUM1f9cpYe9l5ApAASMapfIJOE8
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: traefik
      namespace: kube-system
