---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: traefik
  namespace: kube-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgAmvU65zCxJ6EBen9EctrJnRJrDgUfvw5HFTGd11dVu0InsmXDn6ipZfSAYJgKrvaPsGBKMCTpjMED6sACnGad0v4C/vBEhfqgwGE1IiZK8rulMzrCw9JJuApj5xOW/1MGXpMSOYPY6j5x6QknLQjzlxDy2yEes/pJqU5Hj0s+Tw3sUHbJ79bNVcGEVgPfVMfsR5bns3Z20DKVkJYgxdrln1PJige2fUsLi1Cc5Sv6WcLQLsgfbknfV/IKvZRXDxfUbEXiAowL0VATzysW70xJjZwlzN7NL6H+wzKGcJCLjTdgQ53MnDrPT5ltskJeUZTPim26gJpzSJiUdKYiUq9/aL/yFGJR/dfmbTdH3EhR6tYPIaRnq2lfCa3vRCBo4KgncS5NY+cZau8jhR4AdXvDAbOGvKKm7bLJayVuIxOY7ffUjKhc74X+z+Gc4MtjExTT3113StKOy942Sa4z1x6+geB/+2nnW+Z2qj7GIwG6P/t5IHrC8Fd8zUraixUjb6XQF4hyFW6Ng7582H62XaOkkl8oyl9HCat6OJrULac3nxBvUVzV80f62b7ohIwI+vm+OrTU2+ZFh+vk7B2Vi103iCcVUCry012vwyU/KKLjRl9pLptC8BONS+kWcG6Px6aDgltwjr72R99Aqxo4BjnBwuHKrjcEswgd+80FklWf23NH3klrvcwK40bld+RRPiXZhY/7OQ5lyZPigrNtBKv6v/a/3v9sJRyKzb+0uEpxtwe1wRA/ItctU
    CF_ZONE_API_TOKEN: AgCqHPMYUg+XyW5qc+qlz03mHxaifTMO7VNrWnPHCCzXtIEircVCo9QSvxCbUYHS1xi2Hwop8+P/Zb+USG8FPUKThdwtDycnnWfc3qO29UN/5g6SdEnkiJONLg33Ne5pjG+9RcmQyisRIELRLLo7XYKPJGXYPMAUmTqhPXKV/+l4DWsrYWuc/jgSybZhv0TVMatQ8vRKKCkEk2JyYab8Rjt4+Ep0OJHHWqT4TBF/oaG/KIb1Ipip9o+ZzPfZTPRbFbmqHT2492KDLhZf+2VyWYtNpeepx1IEPxmu6EzLYzzzy9V82Li3iiF7Ldx9c91x2xL1eTsaOqMCmTGTmTOJ8ZiEfUCMt0NIQouio4ZOKbac6f13H5Wc8WMkgHohqgT8xznZhIFZkQAOts64M0E2bCJ00WWBwFED3bKLrsRMTYInTOAwicvQ2rmG0rrul6Ec6n9UbYLJya2VN9m1MVQpPN6Xh1bQzp8Tzi6lmxOcaxOxV1eHWT/xhZsY3cTmOJ6ALfawhswUV2DsMsVM7c9hGoG0qoDRhO9OX6QPBl8zPIK0Oto5jBqYKs281CXVFibjxm/zsiSt9BSqUacp93SZlPaAoZw8HIoZTfle8Zk0QxlwiyTn3D/jD1WEVUwCmMVMT7/KWh3k85v2cyoPzLvzn7WhdzT1BPLrywYL/YiBTWOHwoPFW2PsWjCUVSFOeJkgZs7pyw1SqQfTlOgjiy9bWX2xFi46EmiVub/kTMO76mgK7d6VT6GWOWx2
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: traefik
      namespace: kube-system
