apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: satisfactory
spec:
  template:
    spec:
      priorityClassName: games
      nodeSelector:
        starsystem.dev/games: "true"
      tolerations:
        - key: starsystem.dev/games
          operator: Exists
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 32Gi
        storageClassName: local