apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
stringData:
  prometheus.yml: |-
    scrape_configs:
      - job_name: kubernetes-services
        scrape_interval: 1s
        scrape_timeout: 1s
        kubernetes_sd_configs:
          - role: service

        relabel_configs:
          # Sets a few basic labels about the Service
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_service_name]
            action: replace
            target_label: kubernetes_service
          # Service must have prometheus.cluster.starsystem.dev/scrape=true
          - source_labels: [__meta_kubernetes_service_annotationpresent_prometheus_cluster_starsystem_dev_scrape]
            action: keep
          # Fetches value of prometheus.cluster.starsystem.dev/scheme
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_cluster_starsystem_dev_scheme]
            action: replace
            target_label: __scheme__
            regex: (https?)
          # Fetches value of prometheus.cluster.starsystem.dev/path
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_cluster_starsystem_dev_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          # Fetches value of prometheus.cluster.starsystem.dev/port
          - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_cluster_starsystem_dev_port]
            action: replace
            target_label: __address__
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2