apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: nfs-provisioner
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://github.com/kubernetes-csi/csi-driver-nfs
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nfs-provisioner
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: nfs-provisioner
  path: "./deploy/crd-csi-snapshot.yaml"
  prune: true
  timeout: 30s