apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nfs-driver
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts