kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: nfs-provisioner
spec:
  selector:
    matchLabels:
      app: nfs-provisioner
      component: node
  template:
    metadata:
      labels:
        app: nfs-provisioner
        component: node
    spec:
      serviceAccountName: nfs-provisioner
      containers:
        # Generic CSI liveness probe
        - name: liveness-probe
          image: registry.k8s.io/sig-storage/livenessprobe:v2.13.1
          args:
            - --csi-address=/csi/csi.sock
            - --probe-timeout=3s
            - --http-endpoint=localhost:29653
            - --v=2
          ports:
            - name: liveness
              containerPort: 29653
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
            limits:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: socket
              mountPath: /csi

        # Generic CSI node driver registrar
        - name: driver-registrar
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.11.1
          args:
            - --v=2
            - --csi-address=/csi/csi.sock
            - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
          livenessProbe:
            exec:
              command:
                - /csi-node-driver-registrar
                - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
                - --mode=kubelet-registration-probe
            initialDelaySeconds: 30
            timeoutSeconds: 15
          env:
            - name: DRIVER_REG_SOCK_PATH
              value: /var/lib/kubelet/plugins/csi-nfsplugin/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
            limits:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: socket
              mountPath: /csi
            - name: registration
              mountPath: /registration

        # NFS controller
        - name: nfs-provisioner
          image: registry.k8s.io/sig-storage/nfsplugin:v4.9.0
          args:
            - -v=5
            - --nodeid=$(NODE_ID)
            - --endpoint=$(CSI_ENDPOINT)
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
          securityContext:
            privileged: true
            capabilities:
              add: 
                - SYS_ADMIN
          livenessProbe:
            failureThreshold: 5
            httpGet:
              host: localhost
              path: /healthz
              port: 29653
            timeoutSeconds: 10
            periodSeconds: 30
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
            limits:
              cpu: 100m
              memory: 300Mi
          volumeMounts:
            - name: socket
              mountPath: /csi
            - name: pods
              mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional

      volumes:
        - name: socket
          hostPath:
            path: /var/lib/kubelet/plugins/csi-nfsplugin
            type: DirectoryOrCreate
        - name: pods
          hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
        - name: registration
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory