apiVersion: apps/v1
kind: Deployment
metadata:
  name: profit-muhammad
spec:
  selector:
    matchLabels:
      app: profit-muhammad
  template:
    metadata:
      labels:
        app: profit-muhammad
    spec:
      containers:
        - name: profit-muhammad
          image: ghcr.io/constellation-net/profit-muhammad:latest
          envFrom:
            - secretRef:
                secretName: profit-muhammad
          resources:
            requests:
              cpu: 100m
              memory: 50M 
            limits:
              cpu: 200m
              memory: 100M