apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: lldap-dashboard
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`users.starsystem.dev`)
      kind: Rule
      services:
        - name: lldap
          port: 17170