apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
spec:
  template:
    spec:
      priorityClassName: system-cluster-critical
      nodeSelector:
        starsystem.dev/nfs: "true"
      tolerations:
        - operator: Exists
      containers:
        - name: wireguard
          resources:
            requests:
              cpu: 100m
              memory: 100M
            limits:
              memory: 100M
          env:
            - name: SERVERPORT
              value: "51820"
            - name: LOG_CONFS
              value: "true"
            - name: PEERS
              value: "1"
            - name: PERSISTENTKEEPALIVE_PEERS
              value: "25"
            - name: TZ
              value: Europe/London
            - name: ALLOWEDIPS
              value: 0.0.0.0/0,::/0,192.168.1.0/32
          volumeMounts:
            - name: kernel
              mountPath: /lib/modules
            - name: peers
              mountPath: /etc/wireguard
      volumes:
        - name: peers
          persistentVolumeClaim:
            claimName: wireguard
        # Needed to properly load iptables
        - name: kernel
          hostPath:
            path: /lib/modules
            type: Directory