# Sealed Secrets provides encryption for Secrets stored in Git repositories. Each Secret is encrypted before being commited to the repo and automatically decrypted by the cluster when it is used
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  chart:
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
      version: ">=1.15.0-0"
  interval: 1h0m0s
  releaseName: sealed-secrets
  targetNamespace: starsys-secure
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    priorityClassName: starsys-secure
    metrics:
      serviceMonitor:
        enabled: true # Deploy for Prometheus Operator
      dashboards: # Creates a Grafana Dashboard ConfigMap in the monitor namespace
        create: true
        namespace: starsys-monitor