---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: starbound
  namespace: games
spec:
  encryptedData:
    STEAM_PASSWORD: AgBudfkokT5ZcBZO5X4KLwW9lq4i03EiLP/Qm2k/noZ5x3U13sLPZIUdlSA2+nouhHB6fEsyxaovv40TErOKExeitE5byafGYuxDldY4NTo1KPyJJFBn8/shcqQAqlqEUz76yptEuemInaRr+dUrA2ljQJbSKL3D6x/jqLds/gOy6m8DeeuP3vaXc3B6mmxc2vIFc97fdG51chnuKh4Ez3tP8Ity1/1FaJjlJhOL04lJTKI0Ma3JV00ZfKzMKWjRLEmfcHp/SgMRei+CyuvAyDRoVhSR2ImYUp66EfBFwVjHV7ABa8SmoZ4AAPQmpb/ZH0E0p5Rowx7dQ5ozjuveAPBYORA/mqyheexrQjjsWgXStl3/hJHgShcZXnhzhe4nwMIg9IfPj5zQh3XHsEPTiiNr1W4sO/YvL/DQdU5QjhThJRiOs3UZqeMwJp8xmm46hwlOKHbhQya3XBO1oHfWqE+TMmHApWTn1HUMxNPXxXlAERO/sZbibKPd6jOCMoYmAsAqv0NVE6GFg5KC15oWw+sE5CdaDTUh20hhd+OzmawVtTCJQC7olpBEH7W7RM3mbcBhl5EEo3OoJ6l0F9a41nJ/G9tLu9iZ4usCsiG2dQOIRpDzCkOzH1A4E6P5c9mqinD2higXpool5iixa2iOS1rGwXn4hKNTG23bgY7n+D+Eskzr1OiiP0xD5aGA+JEKLH+o8LkmifXCiePuGjBuuI6nDpE3Ew==
    STEAM_USERNAME: AgAlPg2i7MknpY0sBi1o4ODhSaGTqXmjkN8fsu4UsZ2KxzRN1KufraQAVudtaZ50IeSNAFopQLxJLifkmmYQBJk4QYrtY3b125d+DmZQJka3Lp8LieDUTPsx/2ZnECFcb1M+WLMO0X/Oerd6V3BFrQHhCYPmEZJZ61itDspIhdkQVt7q1Fw34ppmep+3vAstVG3zWAYoLT2kmGvOuL8arSxHY1LAplqe9+R/SGA78F7oM/fYGyeyqVSBjqSdcrfDkgEZv3zDjZsUuSRuiwEccg6ZIEkseYuyg38xJX1sb8UzIneC4MabGRqw1J6audXdhzFsE7vF0goaSaZl1H2HbqajoZeD4sdEsjGMDd5Kwwk0ucy6xNGN/CEiYy9ImPDTWcQZ4SchnygNspuv9ZE7oTVs3QXz0bXybAl44WaAuFmhbgsaqugKCCRLDATt2u0I4zZdXWi/yCsdm04mkwEJLHwywhJz0svqvTqw2BxQt2SiRLT5zeSiFmRwhwkpxjoVI1XNUOGqSLODOsq7NZDj0ZsAp1b3m3sBAWh8swXNjYo1cl/090Nvo8R4QJTtQ5CTPq+FnZT1ZkSE2wQ1THDi9z+gbLHlKHdHmFIftS0xDpV8zyR+pMrpqq3/HN+wN8c1pqTeFAylhzgl6fgNZOSD52/WBWvfT6i0qpSlXU4QKIqkC770L61R2FN3Dbig1m4If7y5Eq3l8HV3MA==
  template:
    metadata:
      creationTimestamp: null
      name: starbound
      namespace: games
