---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: starbound
  namespace: games
spec:
  encryptedData:
    STEAM_PASSWORD: AgA/DhAALJxWi7emXVIW/zUV/G2a0IZcOXIgLs8k4p0YCME1RykAIXj4QKAvjrcxwwf3qHdOHqCtBfrTTr5gZ7HHlkn+DfVwjsGQ3jQcp3xCSpO2oyEW+FHaKqB3MuuoxdoVuOxQwqkeR6fOEMNuNV9Qxhq1OwpiwnUPKsB/vauYWt2EhN645P2aMPBXZbLqSkTr6ULlY4oZu+AJ+yjvkIUFRGe/EjUCUK9+LDfWwgA1ATegJSSOm/aOCDkkehVVYrlI/Am5PAp2RZzbBjVoSmBYObjIeS13/KBGkeViwEm4zgjh8IdyP7UIDhjXkAPrhFtwICrKkGGGpJXwkBpKPgcXvZFBLZ5oTayqDXiOEVTwCj1QGjZZ1lScXsQr3jobLDUDj9XzYYe7bHmUsB/Egh1T4fMpS77Ik9S+xvA+q90D3/ElVSp7dXYpr8T5aayosUnsxmE/ZrhOIlaDr/khErrj5eMExZurxnm4FwtGIasTEiADUJDaVM9XDstRhEq6ApiNIpHMHi1YOlWXmT8O6Vo6Kxo/7G/rEkPq2TvdOsxcbZBU0NTatMSRVzjPDKP3ob3dfms8zhG/wqylJiJPiyi1U39d+JGB0Pg3OZiNucBmtN+otIusKvJlliYBPuhQ4ueJP/PSqCeDXN4GW1i21rPbn2oMWFMJmw8Vwfvc0dS+AD4T5fEWquixMl+pBOUYHuIXKXSSrD9aG7pgqW0s2DK8jMvrgA==
    STEAM_USERNAME: AgBHK4j6Zqlmk4ymoynab5twhTaCGOCVy8OWA+HEru0dYiUKO3X1VtC/sOh/EiC33BT+wsNthx0/YdnpJbisqDUv5rtg+NW2wUMFgnvcP/F2KY5t5m8gGIzKlWv8D1g6ne6wkR9TOiNC3AIRCRpr9vX7yzoq96CWTu+dFN6xSien3QKBiVe9H0Tbrr7J1Mtj8msTMb1A+GSkZkIIIol0xeKnHJm46hcKZFuVbBLICyz2Gui1I1rcVF2fMdtuIFIoiTjK5gJmJgbuVMGy3o9c3a3yQI1y93Y4P7RcpCjNJQ1bxQalgzunzXxDOZCtRP/i3Y+cf/KlRUQ8meh/9j8jjbckHStG5DQrmc7fikWKt4AGOzukEVk+M6WdInQ+Z7hpJPNlXSLKmHPFJ7QPEWc8oGl2MYdrv/GsHJB0nYNbVLTro6YqfFiXTzyM5+Og47zCAK5r+jn/1XVpCBevzsQ7zodcX6uqUbrIECycmyEejOLL1BTnLOIJhvUjM5psWv6ghVzZEj+eaeJFz3dsylytgnXN7kiJ1wSSoyU9w12nckzx3PSWwRI1vRKoUJ6n3Wop223zS+xxgNFLG5rnW7+ds8oZ23OA9nLO0QRaKoSnebINxG+4gM0+BnnEz24bDYFHt6xGYBPEZR89lYZ52DvJh7s+h5nqfN14s4QhAfRkHpWz2e105iFzL2SzJ43/L6Rq0f7N897cjwe0ww==
  template:
    metadata:
      creationTimestamp: null
      name: starbound
      namespace: games
