---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: starbound
  namespace: games
spec:
  encryptedData:
    STEAM_PASSWORD: AgDICwrE0Fd+02qmp/CO/BwDt0VueTfDZ9hZ6eD5H6VCdkOSuR8O2NU0LGEIPjOTinonSS2jdhm/OoUwAZ48uDU0gannCOFy2G3/JHyUpREGOu8cWLJzqzlPv5rWDl0iv7ql7nAJk0rG9+NP+W6WozkU4ejsCOtjNiebdzwmm7LA1gKwGFKEAULSz41cHqSSrksme1G7tgxydM9CMwbSb+uHPhedpNRFWy18TAUxngYZW8ECUNY8SfYbEuHxH7VogKAOO3XEZcdlwR2qY8hT3YRN3vFna0VXizmkEF5XLmNSR8oRqXEYaVwA5VTnFuNsrTnD0KR7IY5/Rv84spPkyFzDYpcdGlH0CIjLhvQgBK95hd3kTbKUBP8nFk31hVxG6tMHlBBWxSCbn8cLJU6kI0mdQRE74o66luxyDhOnA2K4TuJsL7pixHinfXb6x0DaoZ0sT6ZU2WAJTZ+X/S+hMfUGeMpTYzMNNhTpem246uueeCdHRLOjV5pvpsjee4iRV2ORF6ZOt14AgLKxq/aiqAfYm/EFh2mNEEcvWlKE3GQJFdRTs2F0fe21FK7TseZy/vG4qSWE2+3ji0u8gxIyrxSiq/wzEYq30lsMxGgeCQso1qP40EAQ978UZ8KwppQA2mFuA6uXURzd6zNzDeLFe2+R7BpfmOGwPvJ1bVkr5pKb5z9Qs0SzrWxYg5C/m9UOMvd1ex81hdSCeTM7hFFjdaTi81oi0A==
    STEAM_USERNAME: AgCFY22U2h4cHwTm7J/ONAfA9QdLMIRIHvq0Yxza7V2AOD6cIBZPjDscomy0ytFbV2tPLW2wDcFGHnr8rWQ/4MjsX2oyF0TvTxoR/EY3WTg64pmNFJKpdVSJXkTekwN636tj+4zBNK6zy9vZOFLSXIGnGahb6ebiuFT6lxoZRTYQXNrky95if11JCgQ+lxXMgmsBTLvHRXbX63fLiVWl+VG79+fgPY6g9mH2XgwdWb2mftpy5ApHHBv+5lwf7Mf5tNunRdLqycVzO5tNy7CNZ+KHYpCDPrs/NwXN4r7KWpXQk3hvKynXx2cGJLS4W1N0NOhI/isg6jeq6TSIfmqjkphKn0Zx0ARsPvjWTb18k0qvqUl7WcsuwQ9xEXd3Gj22ypYbYj0SbY2TOgAdFtWdvhoHCDqBUk/EPosTBDWY9jvhCQ7Bb2QYrj1FFoVOzAfw7z3Lycgi2gIT3QBv3djjimD99RXhbYlB5WJwVdczgAzTocZ4Glg3klsZltZaahP4V3rQCT73HE+rcNq3nfhLMsT51XTMzhRb05B8GHgvAL920xMHgPBE4kNN2kyT7fG62g8BcZFtSbeX8Dk/YNGaMrHdj+gG9Rjij1yDQ7wajuE5Inw8vafW+xpf1IGAQ17UmXFERrMfjDmAu+I4Ff3AnjefIYjgw/Uf2HnRc0s97MXaSyK7T74nhJzwQCKyOWyUEEA2O28R3rqSuQ==
  template:
    metadata:
      creationTimestamp: null
      name: starbound
      namespace: games
