---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: starbound
  namespace: games
spec:
  encryptedData:
    STEAM_PASSWORD: AgAeuaLfqP7Vs2I36ZTR1XxzBvV3Km0ZyI6Z2rDzLLcoRjSdyeK1mGOZnd61szqXr+YgZUwXcHfoT8NSS44CSxDKIoPkt5Z2WdFVGvZ5IU7HoR+1WIC5LQTB/WB5jY3suHAoH9paWENN86C745nXZoR79Eowu2Qsu7lINh2vwo1VpALOWcXwicLxFtLuX+1pnoBbgUJ9E7jgcMsRjt8RdeplNzfR1ZwS9XtM63QfxVdWPLhVEEB8YYe9USRmtu0286rEgZ8IurzuRPaxdYmt8dTlYNT5OqHpb1B+sp68/Jm4HMVsjR/94TtVbn0Tzs9GT9Bct2a/toF7qNo0iRMVBnQVhDI8bGLY8GrNx/N3DfJWEqYBypKjjEi/nsXMs3PmZGW7hpAH7jspz6iLOLMfgCA4AXePanjl4DFj7aNyBhskiB2lAcKtvKda918XC95Fd0xXJNZ08GOxYBmZ1/P2LHfDAoTD7d54x3qqyUJY9VvwNKg77X054U1lbaKREAlj/TCvxfJGf3V6Knaf+TSx6ZW9Arv/esJnrVzcufsGZS5rMjF5AjTxmvoda9Qn4tHn0RWh48pZjnysNYaLNjp2AC95F60Y3vF49W1gbvEGb3QORvtfiJm/mws/apW6y66NGGeawae8M9cYPaYc1Ce4YTUN6IWKFnGzBLumvEgBEU1WrCueDJhdqBVRaKlPXKlGJiuufkIVqj5wn40PzlPuSGe+PeYBaQ==
    STEAM_USERNAME: AgACvB27BMOM+K0f2imG888/BKi4/mSX/k7USYI+UBjOXs+fdOqrhPz/n+e6bt7B6RQxZTgvGdHKpDFxQXo0I2fLut+Pu6gcdeEbe7hJoPLtysDhWap+6gkZBeCr37H1VtdhFi5+945apc12BToAPcUhZtb+82Ru7oqsruiToYtBBTc2N7ZDEgMxTGUkNqgeF1vbh75t+mVqtqjflgIpyVWkd0xrbM0X24aBawwszyXjBFYQ/pi4DbbjYluoALRrMrgwmhky5nSjNFEc/lGS5VH6Unc2LMkKupPJ/g3OlylsT8jHv6/RD8Q4HQEhuei9BJfpN1bNIuLUgh7XFfEg9jG3BK1mxAsJz0x7FT4zZbbEN5Xi5xW4psccpsWliIkCl0UNU+ZjanFCoVhV9WR4LfEKvPcvwogXXcjWExWyd1b4waB0WLlPeDkK57SFdHnh8crTZWWjRgwS3pWpaWLycQ81zykjYruMnPPQb3Vce12M58y0HdgzWvC+bxCdrmILzDS3mELk+UWxg8qMD78Lsb9ADeJ/8qyMlcwS1/wSSxLAoZz8ENzViWbUdBKSQgkbFzPGPaisOlGadjVUQ6nd7diHRUrrmMd5O6skZtD43SGXFz3+sOoQOUcl17M96n+Ti14UuM3MV9iLOSz7xPzP5YG2eZ8C6JV25io64eSWh+Bxm4qRQbN5vQWF9WZkz8bINm1NKXCKYGi//A==
  template:
    metadata:
      creationTimestamp: null
      name: starbound
      namespace: games
