---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: starbound
  namespace: games
spec:
  encryptedData:
    STEAM_PASSWORD: AgA6yV4brMK9yfuDMVH4Pp8Q0mbUEH5ESMFmjcXy01NvgM6sMLnJnwrLD0iA3Bed1Kti6eUoLtZOG8QLz4MGgVTPjT20AmVmXl4j33ryCw8nWx/tLgF73eyuBaXA7DCQZeEvNk77OsuMaWm3eKL2026Nj871eqkpIgPtEgpSPw/uZ/QweNo8R4PiIXnnChc1f7S032xI3vu2D0OCmvOJNnqFUfOua93AIqWRK1EcaZ1+qOD73//2DvCYqmOyV1OH/yIgQG9PntSNhWLhoCz/xQ2UwCLJqP76bEX1pO9vjSLvKc1cp0IXUXMjkWEKKV5q0QwQLszRveqAjgs+W8nh3GY5mS7Fiw0Nb/K2n4hgjp84HaGVO9zH2NNeSSVJy+znPfRQLUqbn3Audq03ioSlyVpCDT6IGGN6FEHFJlI4M0hQbsdREtQbWlmuKcKlTys4ltRUwLIVthQhw56WkPOJU5t/Tw0phGeqEVeNHzJKSYijialosbddBc7nYKE7dCLgcZGrbwLI8LXEAtyp7UvVjMLP0Ewx8MYCZmzfyKAPz+ovFEwUVFdDNEA1A9em+Uzncl0e6keBAwuYRepMjJO8oT7Pegyt5584MuNNVuSVEzuc1ZMd79ZKqPwTQYU0+a0lOeNgPpZ1ykyKz6n3Hxe6aleXaZSkXUnEtCIbmJc5HBuTUG/QRuXw7iTckZoPGZCLDrOnNd0mq8WS4XJ2UkUWDuYs71OZhg==
    STEAM_USERNAME: AgC08vc6IY0xUaAVJzsgSsJQNl7esmXDX5pjhHpFT43MN4xmrElq2j5qcfPm7uYHuzGwy88L5Vl2+fHEgt1qL+DXLWyL8cLumQM7gnh9F28AsNMhyAM6qi8lA0azwgertrB6umCYme5N0ad/6GbsL/hHkuX+kBfoZlI/yLsW8OiAY0Sotv1Q3ImxgVWR5yIVItED1v1XjWKdZsKFQ8Q9O7XWtSj1gF/Y3UK/c5Z3+pwMN/LlGWVOjYAnObpE8tntEhUoXDdgh82Zg4ehCg+0EkgfwjphcR/JhaFHpcnBXW9ddMXOnvXwOic3TnjViKDJg0T6oQsFT8SLgo+6R53Z3Ya0xqCy73G/kkruaDzBm69r+hqnqg9kSa66LQk+1aXFA8k1f+JKe1Se/epnnHcPIx5rpULO1Xnzmi7iTuONXhQ/j4o31liJZo0MlAgffkugBEoVINTAtkrERyvX1TirnYPv9Y/Qpi/+zOFOKPnlvhRuhYx7QRsMfBGh4LFVfXM8Ss6XWdm4AFKQBHn+/iPdHbV+ioZuCjHhOJ3cUAAaKMkXqLSiP0LEbzFnWyw97/EVwYoGCrdmgqXz/jmogm5UgzdbQDv/vZQM99fcsqFrcMP0yCJcuR2UivcFdV+8YzSN9dTfTGekB62fHXeFzm+SxbZTDStdfl2k3xThXT+HRE3hFkUkizeZ3kGB5zrQuiQmXt4WNXlgJQ49kA==
  template:
    metadata:
      creationTimestamp: null
      name: starbound
      namespace: games
