---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: starbound
  namespace: games
spec:
  encryptedData:
    STEAM_PASSWORD: AgCk3NsOqj7ws5Jzn72wibryAcDwqjd2OcmfvdWCpc/CopmijHQ4YHkCD/D87t0sS7rVxJCCbPyh2+NoE5meuga3Am1Pi1YzY4V+kENaMUi4RDn2+3VGBJs4jwQcNF2D3DrXR7nAlvEfYG+IoTPKTL2UtesLLWOUpBxlbtbKdwbFtu5kJOawDudlRuaG4mF4TJk5Kd8A454YD0oDg1jDdACotbHQaV/bZ3qfSylkw+svA3dBKab/FGo0w+GHtb6hZPXHc/rJipZt+dMUD2JP943SIOKhnI+HgxCHTFIe0puORcL1+09ngPcmgF/pS/yQebJFoh/xd2lqGRzCpaFbLeSQxMvXaywAOd9ailLqhff0P5t9B5O+KcZO9ObP1XtdAGXmT3GbYroNhC59r4m9g963nlXZ3+Ek6BFwYsxnMtTqVVPgTCt0LI9krhKxSKIZ6r4iExmXTfeRzbWBI9065hvl6WBCbIfK98SASTdacvu1NwexYiv15g7YEjba9aF4boYLm+YrKWQ7VzmanVODS3uIPPTVMkwJcGbM3vnfQRE35DKb2i9M5bLqmuWHEnUN2yFgWhPnwgiiuY0qrJSNXF27sMakibuNehxiDubLDtYkL6VJAOPBL3y1rksgJHR6Aq/Y6nCvZFhHSonwa985Drqnh8aZ1dCzgZdWN+DzKMH7jiDktHo0eX4AOi3P4f8YBv6Bjwt6yKgT3LCrgu18LjOietXKWw==
    STEAM_USERNAME: AgCszPtAJKMcRlhw5tPs6zPe9zT9M7scfUDKPOlzMEKUV/oEHaYsZrQ8VDZQ5/l4RzO/h06CUVWexzKJtymOBZBPjTt891ts/vvHD6WXs/RrXHNeymXUmvtcHMINWqRMMzL9EQmXa9jYqaWD8ew7e4FJzTli1XV0rUCZhqDnNBujcWMHhxJkB5UaFGDENssGhT8cFHc4pM/zsZetOkDX2mzDQdrhc7HZgvVeK7HdR3SUJX/YlCH98hPofrpvXgvFklS/KA8mS5u+p+DGidep/3nQrB47NoAtbkq65/mNyZcyGkf7Ao9ZT0ACFgMUiiEom+FopPSAuOWYxMyhcGw4hgw6j06uQMFhD7FsKzns/4P/z4OMBiT6J5XLBHNvTgDnzO6p1j+Vm9HMyIZLrDILC2tiwextls+DcxF7BO842ARevdaQ0gtkSrQPYYxtNDIFNma+kKpJi9ySQQapfIkJ1MSjMzpGp/yqqV+aOdIQXd+5CicrnknHHS7s9i1r+Gbucu+JQw4avSnx/apWB5jhnXFcVYjcmfD3MLuPgf4/r40Zh1Kv1Y5UStJJODi88pif8hUFZrPuMDwtahI3ndz98ZCKXHTFqOScU+OFfJvOZYPYh1YBFdg1rJkFX1GxqDt46Q4yzoXEypURbukLcIESqZssjICT1EJTFNw8DiqC5ilX6wTnsLbxyNCHgqaPMmhmaRUoT75CgCkVBQ==
  template:
    metadata:
      creationTimestamp: null
      name: starbound
      namespace: games
