---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: starbound
  namespace: games
spec:
  encryptedData:
    STEAM_PASSWORD: AgCsFO6elyT37ljhJpUh4eDap9mbIm/HuttYFGS16p4mJBEzdj9lVX9erk4We7Ig2v6TN/brChiVq+vLsMBd0ea2uhr4cPdIgRVxzab5FAQQ5pclS9IsUYayRanXPOgcIUysn4qptTZ525L6ihgd7CBmhsi+lB9/l8DyiejhSYzZ3y+TgOmzca4Yu70lNtdsJyf13h+vMCJmdwfFZ3DfghKRaQ+zj6CnOxLwV+A3JkePRfpj//i4Ug3KwOZBRi5rn45mp83I2P9LRGLIh/htEmb6rY5RqS5O7e+XPmosKgwN9Evmi9I+Cc+6Yu64iRCdvsqPBq+0G3vjnI5fWS4WV7E41Z4lTRWBOQawEo07IRtumOBsoqbMBEPNSDiE+44OqcWsbGslXB6RyMdhgaSxRBFTy8aITrgRNnYgoMNEQGTitbcsV9qeZePXXyQkCTLQuu7UFAbMSQKZu10WNKEmjZMJPnad0gE2+UV+x2MhF8tnBRyi9zXD/cH28NoZa1xRHiA+1TrzI8MbszojQXQnhEyhmearfwAkNp++x3ijHYwv6TBo839LS9aVDrRyz+stmTsbdWBfXdHfIJBuO2sUWlg8a4d/UevXcvlQpo1w4ACZ6mc9PV/BZlN+UTEllvkj3X+4GiNfRMVL2RwIJ71mHX7kxdt+OoGeXZ7MN37+9c2Glof7sIYz/ukDrbaOHJW+Xgq5Go53DawlyhqOfU7Yyta4uwxSEQ==
    STEAM_USERNAME: AgAV9/FiTfHVYHFXGLFqfR+g/w3GLC/ZuNyg39Hbdy3WtmO+Ut8M+LxIv74tmvMI1ITZKzhxl6BdrqH5p9jXPylPC0DDwaVmXq2a4JqvDGHK5o5omXE2kja0EQZXMGVH/SYpDLDo95OiHIdD+MLCRDUP8nWLmNIPOqCEigLPdOE/8GdXm8yi0cagfBJym6Or52ALi41Ejhq0yXyYyXyrlXw6doPHpQr0LmDp5Eezmt4OFLoqULAgc8jLI3cWdvXU2AksjKvtXHwJoH7xbbL4npOUMglb+2M8znzzQCeAm4YxyO0uMOCv1r4DXYZc4m/vzz8LIxhhxheUDdg2vCvOeG51lWQ7zjZUboiQwcbFsf1yCQIE7F2iuCj7sx5zFOhgdPbhmembsS/EitE4rrI7BgPoESx5aeGJTFB+aFBGeYaBvyySYIDyrnrSVAeErF/fnxhWbgH/oJtXqShLVL45xYbQ8VWjvOPAMWzi5nzBfHLHzDw7/zncfMpD723g9YVLOmAzpO1tuPjoBBO0yMRNZcnKxyHFjJYvoQjzfJ4g2y31Hr02ICfAotMq8YJb1MUSFy8wg+dOqkm+akGUlo+fEd+Qy7k20e3Fne8mpUsRUVK89kJGbrCJU2V0vtY2K/+aaQt63jVwtmaruYehuWSO3klpv5B2/VnXygVMlyGPOw8EhrvYxgXknagscK7lxGFCF5td1ZXpsqUQHw==
  template:
    metadata:
      creationTimestamp: null
      name: starbound
      namespace: games
