---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: starbound
  namespace: games
spec:
  encryptedData:
    STEAM_PASSWORD: AgCAnPMLpVHfPS95Fz5sZv71Drt4+gDmLNoWbMe7LP8LGApm47GI/c04miPWPpVPvF4oURGV2AtJ67aBC+Awk+55N7i8v4Uud4ajuemQrOWXx0cKJbaeqkh3sKJSeWl/HJBQnw/NuX2hU4dMj5slvLm7YJEA6jVetnvxz2s5foUepnfTqmqYuHLHwL10d/8I7HW8et+aiQATKL+wlmV/xMSdHadL78nzPAlLQxtT5Ex839N/vgYoMttqDUNvbxitEym75wuuFlAP+Cp5TrBDCFeDOsi2j5CinSglIK3KzW9Ix8TOfG1PS7swwNe7N0tYS+ftxw025ZmTbZjvsxfaNgxbziS53tG7Zwd1xy4x5KuH65lmkssSYwUzoylk1yLDo+4gLe0CUcF3oPLVVCeaQZUNWX+SwCn9J9TD6XTztsM1tJE6fqyqytNcdhtSa7NHqWaz7/H9VixHe5VwUBbqdzAscFyS6wrB2+iNzPrtVFk58jvAkD22b6+VGKJPH/yaZt0rpWvJQ5vUBGdUuHIm+B2LDNdl8qYgOOqfhTWp9K0ol53dpc+u1i2fPDo9tiJ+yhmIyogui2oyFazPq4CKSXG50lFriPz3KsA95cPBLXIF636CimdTQFsr4QhJkPxSsEmizHKDyjNBqI8s1p3PHo4SJNcLZsts1gMpYFIIXtiHvVsNHqTniDd0kkfpCpE1hXl+W0QKzudhmglt1WtN3mLCd5as0g==
    STEAM_USERNAME: AgBebMy1L82C3VLRF2Er9rI2318UZW8zxScTMJgYrNeV/9I0x8vEO8IQv/nzQ/no9Q0QzDg9TorwmH/NvKUAT4/scxQP0OPYvD0RTToUJ5we57cLjCxW24kuwEzmAdNniBCRUSfShL8XXLIz1WpC1FFBn3ywQzztqH06DWKFdQ7p9X2tNAz+5E7io24r2refVNRmRO+gpwioKzPlKJjhZhYQA9ho+UO/Z0f0xbsmYp4LjP+upVvIf9y+vniaNMuhAi05/jJgmkFnwxFWrngujy6Z0lcuVaWnDVV2yH8ofYA/kRiZ/tEFFH4D0kTy97FcjWTUAXPMTd+NDeE2jZvItE4GSIdfDh4/+z6IQN6uNRQSyq4WlLZd537ixVoE5lvsg2mvdLwXVEnK0EGYSlHkdsNCigiUzhfzB887lXXf6f0avSgYR25rVmXxpDVGdWqqk/XzYqfcmrxFFGcKxjAf3UZs0+Nt46zSniCYMgSJhACGqliZOD5xubQTVe9LFshfvrd1I1Xc/kWbQTOYU9k0LvCFvl60yox28tZ2zhHDG3Y4IMr4yi/Oax7AwJsWhTm4Rt3Cb73Azwhl4BRrUQDsiHKtxRdBwRwBk/oGgCp4hMmZGBPOV25y/U09KFCpGAtPBhAK/F4oO/dD0r3tSJlttVA/4LevIFhEkhhNKAJbsJcgKqVbeWKI7krJZxZjUNXpSwze+XG6GzN8cg==
  template:
    metadata:
      creationTimestamp: null
      name: starbound
      namespace: games
