---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: starbound
  namespace: games
spec:
  encryptedData:
    STEAM_PASSWORD: AgAZpnngHasJ2ilYJHqD6bD/yG833gvH8aZAnpCxg00xEf0OdTWbovymZAYoLAvFNKrluzHjCRQIjJWko70vz7xS1n0XbedDzMFusSfg4dYkuyamg0vSvZ+GQKunfg3k1A+ucsLcfFQXCHcaDmql2LZ5gvgN8DCcAiQZQ+ZXMR7IoB3l1GVcKWkxw0T5WLohSKBgTbal2zUtpZ+hEpXTbCM4VVSbBiJbTnQQhzcbONiAfnkjD4S6uFt3iwmgo37y1MS0mUmHmR4yoWo2pa/WYNiiii9YyOo6ZU/gLp7frmbNAUL4XPmkTQqPi8aQYyN8f9whxa93Avsf6PF7zL6t7M9jA80GqxEymVnqHkzEUfVT2tu93CtAYk7wLAHtDpgLx+80i8/i8tMmbuLlW0W2KNv8f+i53o+qnDRK7nl4g6NRaHOrOzXeiT3foxMdLPbGhO0YkMtOtrnjhUXk/RbInk26zexZ9pcQ7YAFfF2kbT7aVwKwsG/PngSmzTaIcJ/ixWnRT2CKikINOW18whodNmGOtFAYK7Mn6BL8LkSFrXWWmhRd4OJ740uL7xRbYNYXacjuap3eEyyvm5LBDPwqahcN2b9L+ZZRSCs3x/7x5bXp0WAeYWxziFJ5ZHShxTFw/Ey84aD+vrinygcT8d9x56tVgwq+clH8/gtNvNaEdbNGPBKFnfvwzJWljZBfDXHVBxnhaltUepQcnfyEOISrlMsTzJcokQ==
    STEAM_USERNAME: AgAbsi9qRWQ0pQpq1NPfkWNjA9yacTpdURdLxvSToyyPW97+6exQbC0Uh90sns4294LxjRbDZTepFf+umLBK0T7xTKXmYS3DbiiyKCx1EGglqgRrN9Fa5vK1bGZCjXWgXzOLBwDpTdW/u2VZC3El9TG77Jl5fckh1Cg9pzmv8IcvS1E9egMnh0q2ZW+FxKK9KCpBIuibDEkcjMbe0OucgLchgpSmdg5KXQ4OowsDu86p79NoukZYAh74YU7zw3RUdlq8n7cTsVaLb9rVuJD5eHLsphiXmrzZ7z2UG/MdrvIbUi2IsP33MMFPYgXDNRWIG8v5mol9Rs9eGA8w4KFyy1tsmDYjoIaSe3kvUWgpTYu2deuuszo+r9FO8nlcgk04qKmb1APJ8WeAyRDK7937LkknlqzwnhBkeon/kS5Fd8XUQI7/YD7yu0eHdV69jaUwAlRkD5wIfPUOFB2AH8bNOFiIYm2yRncFwHytxoE3HP483D1sLOeaGt791HEj7+JwBWFD9qxsre8szfw0eaBfDUjkp+6lqVjG2ON39Ap+4LpTxHYF9IUze/PFtiJigSqiwz25ChHb123SN6eqN8kqyEVDTZNOH0SUYZWDNO2FNXJ0d4+ciXYZhpPG6MXvsRf+lKDFEGLE5N9NjO9Pg+Pbg2UM0BPI0IQHlASgyzDPeja1wAxTBWWEourmxyqlCcFg0QjGr1FpTjvslw==
  template:
    metadata:
      creationTimestamp: null
      name: starbound
      namespace: games
