apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-operator
spec:
  selector:
    matchLabels:
      app: postgres-operator
  template:
    metadata:
      labels:
        app: postgres-operator
    spec:
      serviceAccountName: postgres-operator
      containers:
        - name: postgres-operator
          image: ghcr.io/zalando/postgres-operator:v1.13.0
          ports:
            - name: api
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 250Mi
            limits:
              cpu: 500m
              memory: 500Mi
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
        - name: operator-ui
          image: zalando/postgres-operator-ui:v1.13.0
          ports:
            - containerPort: 8081
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: APP_URL
              value: https://postgres.cluster.starsystem.dev
            - name: OPERATOR_API_URL
              value: http://postgres-operator:8080
            - name: OPERATOR_CLUSTER_NAME_LABEL
              value: cluster
            - name: RESOURCES_VISIBLE
              value: "true"
            - name: TARGET_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_UI_CONFIG
              value: |-
                {
                  "docs_link": "https://postgres-operator.readthedocs.io/en/latest/",
                  "dns_format_string": "{0}.{1}",
                  "databases_visible": true,
                  "master_load_balancer_visible": true,
                  "nat_gateways_visible": false,
                  "replica_load_balancer_visible": true,
                  "resources_visible": true,
                  "users_visible": true,
                  "cost_ebs": 0.0952,
                  "cost_iops": 0.006,
                  "cost_throughput": 0.0476,
                  "cost_core": 0.0575,
                  "cost_memory": 0.014375,
                  "free_iops": 3000,
                  "free_throughput": 125,
                  "limit_iops": 16000,
                  "limit_throughput": 1000,
                  "postgresql_versions": [
                    "16",
                    "15",
                    "14",
                    "13",
                    "12"
                  ]
                }