apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cloudnative-pg
      sourceRef:
        kind: HelmRepository
        name: postgres-operator
  interval: 1h0m0s
  timeout: 1m0s
  releaseName: postgres-operator
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    config:
      name: postgres-operator
    service:
      name: postgres-operator
    serviceAccount:
      name: postgres-operator