apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgres-operator-pod
rules:
  # Patroni needs to watch and manage config maps or endpoints
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch

  - apiGroups:
    - ""
    resources:
    - endpoints
    verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch

  # Patroni needs to watch pods
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - get
    - list
    - patch
    - update
    - watch

  # to let Patroni create a headless service
  - apiGroups:
    - ""
    resources:
    - services
    verbs:
    - create

  # to run privileged pods
  - apiGroups:
    - extensions
    resources:
    - podsecuritypolicies
    resourceNames:
    - privileged
    verbs:
    - use