apiVersion: v1
kind: Service
metadata:
  name: postgres-operator
spec:
  selector:
    app: postgres-operator
  ports:
    - name: web
      port: 80
      targetPort: 80
      protocol: TCP
    - name: ui
      port: 8081
      targetPort: 8081
      protocol: TCP