apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: medium
description: The default priority for most pods. It doesn't allow preemption but will take priority over those specified as low-priority.
value: 100000
globalDefault: true
preemptionPolicy: Never