apiVersion: v1
kind: PersistentVolume
metadata:
  name: valhesia-minecraft-data
spec:
  capacity:
    storage: 45Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /home/jack/mc-valhesia
  nodeAffinity:
    required:
      nodeSelectorTerms:
        matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - mc-valhesia