apiVersion: v1
kind: PersistentVolume
metadata:
  name: valhesia-minecraft-datastore
spec:
  capacity:
    storage: 45Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /home/jack/games/mc-valhesia
  claimRef:
    name: valhesia-minecraft-data
    namespace: starsys-games
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - mc-valhesia
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valhesia-minecraft-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 45Gi