apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddns
spec:
  selector:
    matchLabels:
      app: ddns
  template:
    metadata:
      labels:
        app: ddns
    spec:
      containers:
        - name: ddns
          image: timothyjmiller/cloudflare-ddns:latest
          env:
            - name: CONFIG_PATH
              value: /etc/ddns/
          resources:
            requests:
              cpu: 100m
              memory: 50M
            limits:
              cpu: 200m
              memory: 100M
          volumeMounts:
            # Mounts the volume that has the config file
            - name: config
              mountPath: /etc/ddns
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: ddns