apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
spec:
  template:
    spec:
      priorityClassName: system-cluster-critical
      containers:
        - name: pihole
          env:
            - name: DNSMASQ_LISTENING
              value: all
            - name: TZ
              value: Europe/London
          envFrom:
            - secretRef:
                name: pihole
          resources:
            requests:
              cpu: 10m
              memory: 50M 
            limits:
              memory: 50M
          volumeMounts:
            - name: data
              mountPath: /etc
        - name: prometheus
          envFrom:
            - secretRef:
                name: pihole-exporter
          resources:
            requests:
              cpu: 10m
              memory: 50M 
            limits:
              memory: 50M
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pihole