apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealed-secrets.yaml
  - pvc.yaml
  - ../../base/pihole
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment