---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole
  namespace: network-system
spec:
  encryptedData:
    CORS_HOSTS: AgC8rRrMcTTjfMjfw4AP7QFFrQGNxWlzcu8QTxE/wD0yx307PuMpWTtEgdaYp99KsiBg8HgMf74z10NzMAHSXG58xHF6eQsN+AU85fMybsQlAc4LSQ2XytcQGL9ByUTetDtnaZK7gfqCIXBknUJX4ybOEA+iuMNfTiSgauoOqLcJKYwkwOO+QkwHrLFHKB4Ic5MkcvAa33h1bkIu34MwIsxh4f4neqhCb1Bk+YbxVWhnvcLX0GdqZrd/SXSJ+QJT9FB64wy2s2Xdob+LhWuhvqAKwI9FKqf/EOrbpqGZiw0YSpIa6jQq2EBtbG3Q3g8mPXukc8mEWVZ8QRwcvV2C4cphfeUrfS4c4J3LDm/W8N2KVWeTantk78UU6mM9/anVk8YRytbo7Ivi/KfI7huYba0etQG2Gw5OwV9oWTq44yKPdZDksW0itmdM/tNzEs3yPeRyjwIb/KoTOJz+aaUZ+wGWEDKVROJiuRhkOmjq/ezMjWudhOK2m6B+FsEI3vAHMiTIie6g592y963d4wkRps28i7R8kiSdwssH4SoG0CvcKK5LZ9V2BJ4LzXHHJgdGU6GWn5u/uL4ZqYeemDjqOvzcqqEOWnRR/f9v+pO1rymkjPQKdknH28ew4r6rC1pEq4KsiqGakizK4ROCu0SdqK+gCp9rRvnMiJn04sWhv7WTXuaekUocR1Yl8JJ22nVW7utNIcUSTHwqbFxr0mePRhRBatF8
    WEBPASSWORD: AgALKkufU2gxR+IGOuP+nzJCniI+vmdWNC/kr5CLLOu+NE/Mj+pBBDDWailahAKwd8tbE6jxGidbrSsNGpJK6lipXz39xAoknJ/LhXhD7fnlboYJeRyVnTXWUlhRAbz1pHJDi9DZZ3qgoMuJVppfvG+CQCHXqXYU+wsiTxZ2vGjeiz2/qOqoAv+XEMvdh+jKvQpIDxPTMcEe8OKCTLua0xJuo9owuKouaHjDpJB6gWUZtLdSYiPOPeJn4HZbk8BFfaFoRdiyw6rCZHAy7iTT8bQuC4vfgBWe93t8l/iM6gXODZQLstAc2zjuJ/fFLFB5LmlQQRYJSwlP7phrX05X+u9wr20RGcfewSc0/Di6MfquJkQj+AowWfOwWs6rgl5ULHpkOrqax6eaX9vhQ5SVCuNCHt5yH8UjVVzceG/ObEgfXGfknP4cJVeOjtFNBPSae8YRuuilByWkJQHHrHfxhoNcB4DBdzBlgvnm7U9i5CjBF5vY+usYCegSHu5bPnmN8gZ4bS38EA6jHM1cWXryARrbpH/iGD/va4W9hrp/iare9oeWtPyRe1VbGl+MpcnOoRdPm1Mnq7j4fzpMZ8f1LZ0xfoUzxjuWYoMM9BPzDlmbYVXhf/40ARTENAhpe/1RrbRgd9jMl7E7JIz/pP2nbwFzbbuxjBaZpK3bsFfahbqIwRk1SIPGc2353tvNiQ8lz+1qTThoUnhzbRo1rzRF
  template:
    metadata:
      creationTimestamp: null
      name: pihole
      namespace: network-system
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-exporter
  namespace: network-system
spec:
  encryptedData:
    PIHOLE_API_TOKEN: AgCX/ai3024qBjmjYsVvLKHo69PVN0hBtMmxa6aXoPnHRZ33sU5R1hUOapKdOoYiKZhx0d2Sb7Y0sZ3v+BZUcWODFQtzrMTfAaNhTmp1qQ64380SsB0teOmQ0NH+XNqKBtvY6R0fw0VBqBpdTwGU+Mnyx3lXHzl7jkAPgCnfNI8pbInIkTNt3UR9przYFUeVmEd4VBcwQKcplp09PseRWNbh6l+B2/GM5XSeAV/e/XbW6ApgFVmYs7YWhox0/4nFFcS+hetvFYeeQPDDL5zHHZ/162+g08j5WV/p2nhaxrqMya5AS2Vl3D648dhMO6JnIyTom0I6KgZ28kJ+8Ay9dRm7htsglvD+T5j1Iy4SI0Mv7kBPKWey2IN2eIHPPbl1q0c8qJMZ2JNGwCl8/9sKsLZjKbPDhF8np6t9sXUyDillZU2z0x0Tw/NCfo5v+yQM5xAYtzQqpfIV5NSbzTrJFmzZbkvrWDI2S8PHkezGHm2H45r/SQQVs42dvvq8uwjjLB5y2g5OhVt/mCueeAF9a1+sK0dBwbeRx0EITU3iNkVweepw4ZvDzqnYjSW9e5v48TdiWEZ/7TRx1g/RBoAE3Rp1aj8Wr27fY8MDvd6DQXJxqemLtG+/2c6jnzStmOwfRIYc9n2zYzYXKZ1SDvJ8qxS84t7/bl53ArVgp9LOFCe0oI8tcHZEzVIK6CU9XJk9iBU=
  template:
    metadata:
      creationTimestamp: null
      name: pihole-exporter
      namespace: network-system
