---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole
  namespace: network-system
spec:
  encryptedData:
    CORS_HOSTS: AgC/bOXEYN+NfO19kjz584j1YDfBzmNfl9iKcN1IeCn50zgrI5x1A/vjxI+hgjJvNeiIaEZBnVnhtHB/j9osvbq5bI6/AVIjzkG4yiligS7dvZ4dp34NBkeU0N2mjD5EhU/0Acruqb34W84MTDqeqY+RqbANARZhldQ+gHJCpLBbNxAAL1CqFRe5PPadgAABnDNQd3hlmbBxA5eEX+g8dDcZQQUAD9geusSBH5li5z+EVM9EcDjVtDKZP5FsKpX9yXTt1jLpc/XKrC2GNNJGezCRcYvbeWskX81mTnVD5udPlpSLRWEvSqJKv5JsokG17H/aJJ//wDL1aPUuUR8uJ3NIoetGDnE8ShTFNRbFfIwC74JYrcSA48yHu8esaqmlTOz5fsXksIv4sdPIyTx4XjhC5BjTWQyAbxR+8TcTdhinpyZ6BYI5eYWZaX+LxEd/uZLlJRkcYn9mwVyIUBrnPNCmfi9MQ/gX+8C5OS8PLVVNADhZpuHgC3TkhazT4CO4gakqH3bvsYeppqlM/cN2ymyVtql23Hkct+idkWkrW3l6sjDIZBcGMnV+IxbRlxOjBfZ5DBU/oVVVvtWX1wIeqxES6/1SEY85AdMOdOmr0XgaS8mEtyK+sIZZog603atglKAUsuQFWkEwVGjq4lxnWBGuOzkYCnvKP4zlVRik70NFt8UQa5vS0tZ7c6e4yENRjEkpfROA1gdPolZtm02/UN8utFwz
    WEBPASSWORD: AgB4B+ZwTKX8ipPzRcLdATJQ94vgU2ynEGpyI3OgZQ11rOfPC7cnD59EhxaM5orOQTDCrOLQkRRHyXSs0RYhc9ziXkc1iMiYscoZFrdAuRdTBmphuafk5GIAvbNLEWnaY/b/D75u99QmMHPlW+ruK963NFfWCc98MF5ihIPuJLG88G9SdDncuSYz4XwmOH0NY5q9Gzp0VU0Fl1Fku2/GBwAx1UQNeblfL9plVh5nx+RCnpVzMXBT0qFPkYixiiJMMVKqj5UjN+9RMw8rZFB0HaaS3IifWnA3dnWQTIxup2AyJKxiaYhH0IkQ4+i4k4d/JXevzoF1xl1AigRJwSVQxeZH0oD1NXLTw8o2Mdmcw6MEX2P1jMzfURE/49cYKoepGkkONajV/8zqDStE9O3W6H4UA6Jb2HWaqKuSto9crtCBANyY7zgqggKa2S6ZRw8rMf7UPv+JT5SdjQ34r+DF0YHo2e0F3UBEDxoUUJGG3bAlFJVkkbCEpRfvIgRrRWMhjxB9gOldSSVSZ+GTu3vHq0kPIi2z4FTcLbk9oqzXiboqs6jj1UpONjzfW50fXfDMotruIxqBzpwdJB2V/i+EPbfRIksr70HEonI9Nbw5W3OPBXJsby8pTk6BjhA+So8tUs4H7tn3vne2h3ZU526ORCnhAIokZchw/XGm2PfTHvqIFzTPwUe0NWwqN0t/84OmmHew0vhvnBVBXjEI6uTP
  template:
    metadata:
      creationTimestamp: null
      name: pihole
      namespace: network-system
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-exporter
  namespace: network-system
spec:
  encryptedData:
    PIHOLE_API_TOKEN: AgAsVfBI0fp0bs5T4KaIZbDj4GDX38XRZyNb/TBFxukKUC+nLWLG/JDcEQc4aQGRj28NOHAPuEzMiAudb75JuafLWl1VHor0uK0zVUUmIQFaVGPDAdKJoWMNuaf5R9FCEVwFRx/Tp7k4spkC18SKh8ZeegQCuvgEg6WqRAs7HNuM+2fTgiN0APybXkHeM+58MMdM9jWZO+W+U/MfcpeiHEdbbSUbuY9ND3uXXBQrbdDfDtLpHwMLf7Bl5s7J+zAeicrw4N7Rf8RDP7Njr1/G1Li7P/2OwNKm2kVtu/nCL7f0UPhK3AHCUcB1JkkizG38oVieFEnms3lpE756Iy3qDa50w+l7miSIIOEYUqBlsPq4WmYDlRBuJmzttzEC7REq4LRxDRHe8OlPwdiN4Lz0B4qLeFSXVco6Wj0NucWNQLqbWIa32ISoifI55SkNZzL6S3kVX8rv6t5USLPjkjxnLVj7hzby9/1T/YSzi0ihpjGxnaPJIRXXPu7SbFKDBxvurWYxe/0Tp+TzCEXWGuwNtBYXQ4PsXHoF+xeT7p0gMLGtgWUAPHmrRxA+k4CmLf7FNW0PR75s2IVM/VYiZCFTXjAXou2ZpP58ZOAf1BSmGAxnPJ0lzfa1CSeRrXAqkGs+V5FDqVCL96mjUeq3Nwa9tV4qZuDWTs7uHAGXKbkSBU433vpiKfN7rUzn4VWZs8niPQ0=
  template:
    metadata:
      creationTimestamp: null
      name: pihole-exporter
      namespace: network-system
