---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole
  namespace: network-system
spec:
  encryptedData:
    CORS_HOSTS: AgAhqgDFGBho++7Cjk8Xk0T+dJP6sK+v60EwBLqmPBWIs+fFj+SBLz2NRgYirKIwGZ4q6BhqXrqSt6A9rUMMac9E4559MfhraN28kQ/YUFFPUWh0B3CYTgjvOPe/JaX4dW2yc3eYV2qj6aLFgHj+yvNBJd8VUqWkiMmJHDaU3WMgMyVjReL2VVsCCAK+Ojz6X5EOb2zyGeT4zh7cHAwIcFfrQH/7Qc2lMP5NSCKyoEl5NrbV5VD5pB21D7/ZpRTJKTNUgsk2Ti0YVg0Tl5HYStVpp9TcguH8N5lHhdkRYoZHY1fzHnkZcRAP34vKnK/ELCjc5S1PnJZljx7APFxEwRYeo34t3KZLIWaAMbpVZt9qeTfLI8bPNoCCutgfsv/Tr4o3J5XTqnNTC6lua467/4JP3m8L0W9ZMQDVVjGBGhHSmO8EocKwkLdgD+cUjXevVNKIRYaN5KGnPmWGauurBfANILafQ0s0I2dvCFURv9HJVYJ6DBwIIC1TacEfATauYNLRiOJs4rBvPK3V9c5hMSePtazFnAZa2muY3W1O6if46NGORIcY0mY5/4nRO5zHXZLF8Ygrn/2hi2HsPP6oP46Fjgm+ddxbJclU2K68oJEUVgV+bUPgpq/cIBzmtc+WXtu56Fsg/GOwWhL0E3mHmLNtLOcBM6Bz+8UImPvGnOLQGKIWgaAz6j7OJtlxkthqeGtEh9UiC3xIurwpyozb2xStVQCT
    WEBPASSWORD: AgDHIrnco4lfva/VXh3z1aADiF77KrziKCoZRRa8T1nBjCQzG7eGa2zKF/R5qJ3ZPyb+DXtV4vtk7laujpXmV+FySRIvPqqR5FJbs9ietB30MA5reOxhLZX5KUUVLL22qPOxW1tCwbjURbh0qv/4dCR0JcNG3mLuY9hI43o89g4Gsxg/FimkRw9WSV68xOIEQiT3msriBrsOMUQGtrh1WBGTD+r/AnwO+ys2JYGrh5u1vzjbsNMerjj8pLMwakiKCaSHQfSJb7hxJFxP/cAcuSlCUojn2bJi3EQUB8YdR5MFeSaMdg2QQy7wg71Rg1Erp+wr58ajyVaK88l3XeMdUi2mKxIKrYxg/fEC0qD4z6W2D+U0ZDX627Iecs3pjWryPQqI0vuzgrO8OxT/6DIux+ropsSqf2GBWyPEPyjTf1O37+/aaTh+XgHGjauuakVUzB//SHmwOioqPFwDOlGUyRv5rqFIvxstFV+diwAXREv2tPGJgcO0/FxFg5lBBaT/8/JK5kugCmzR1HomKkyL8x+R7U4Myci0ihXe8Vbf6y4Dp+zffaTCFuiyHi2b9Tvnycb4jEqB0NOX9EnUrtIh8DkzCowiyAKPqmoKbGazA/Iu3CstKLDUl7yWDd9frKE+1wnNkkEF0Hlg/rqTU9Nj8TTNeKiPZTFors0YQXoc7R9/yDGnj6ZX0gmBNwi9uvxvItEHJ3Ihx6xfveHAb9lD
  template:
    metadata:
      creationTimestamp: null
      name: pihole
      namespace: network-system
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-exporter
  namespace: network-system
spec:
  encryptedData:
    PIHOLE_API_TOKEN: AgCe//CfObxyPtdlrSFODDVyYOqUuwAwi5IiNSdu6gKTQR4LSdO0tO7tm/N2z2jmLMgsmCz2FZ/oFw4rpxKivFwPpN/xDY5qgsxB37+YJHhXfC6RzV1O3lPVwuljFY8FPPYrWmCCSlO1KUDf7WN00PYZZrWZ8TWRHBGYhiIcRvjlhavzB/l05k0oZTOsLcMr4QwGfV4V7QsM+/TLX3D2Lw8TCNwu//E3Z4z7l/RcQbj3AZiSyzUb9lczn8m8ACABjQqUt5nQY1tIuqfKB0ONOdyF11a8i0HdHZlPDFbkpjkCoXMnMgHmMNsBp64c7SpUD6Sdaepvm5JoiuJpLzbLnSSgpgfci35ZyMolcXVM/B5vtXpf1HTbl/2Ae9fiIOMi0xgJAy7Ek6ciqvrpMzwrpti2y7EFq9WJ7aRI6D3lQmTabyGNkIW6WZto6ouDCtvODnoWkPDyb1h692UYd35d2ywfEn5zkSoG4/gox4d7MKZzLJn3quNilm4FGRBbepvZx4Rg/996f4OuzA9U6Ok3YKdD3yIgE0oW0cXyGX949B73b6lggVrmsyHgOWNrDP6VS/S0GG3gtd0ItMcA0OllY1iY2KrXQlxdnfp8X6bMJksqG3ZLih6wI0+etnPwRd3xKmZkhfCPoYMKTbQm0PihjbhTtTDFQ8BIIawmgenI4oh4lt0vF/DYrjNTDL0pd4eAe7Y=
  template:
    metadata:
      creationTimestamp: null
      name: pihole-exporter
      namespace: network-system
