apiVersion: apps/v1
kind: Deployment
metadata:
  name: wgportal
spec:
  selector:
    matchLabels:
      app: wgportal
  template:
    metadata:
      labels:
        app: wgportal
    spec:
      containers:
        - name: wgportal
          image: wgportal/wg-portal:latest
          ports:
            - name: dashboard
              containerPort: 8888
            - name: metrics
              containerPort: 8787
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
          resources:
            requests:
              cpu: 100m
              memory: 100M
            limits:
              cpu: 200m
              memory: 200M
          volumeMounts:
            - name: peers
              mountPath: /etc/wireguard
            - name: config
              mountPath: /app/config/config.yml
              subPath: config.yml
        - name: wireguard
          image: lscr.io/linuxserver/wireguard:latest
          ports:
            - name: wireguard
              containerPort: 51820
          securityContext:
            capabilities:
              add:
                - SYS_MODULE
                - NET_ADMIN
            sysctls:
              - name: net.ipv4.ip_forward
                value: "1"
              - name: net.ipv4.conf.all.forwarding
                value: "1"
              - name: net.ipv4.conf.all.src_valid_mark
                value: "1"
          resources:
            requests:
              cpu: 100m
              memory: 100M
            limits:
              cpu: 200m
              memory: 200M
          env:
            - name: SERVERPORT
              value: "51820"
            - name: LOG_CONFS
              value: "false"
            - name: PEERS
              value: "1" # Enables server mode, peers won't be created though due to the directory being read only
            - name: PERSISTENTKEEPALIVE_PEERS
              value: "25"
            - name: TZ
              value: Europe/London
            - name: ALLOWEDIPS
              value: 0.0.0.0/0,::/0,192.168.1.0/32
          volumeMounts:
            - name: kernel
              mountPath: /lib/modules
              readOnly: false
            - name: peers
              mountPath: /etc/wireguard
              readOnly: true # Prevents wireguard from writing these itself
      volumes:
        - name: peers
          persistentVolumeClaim:
            claimName: wgportal
        - name: config
          secret:
            secretName: wgportal
        # Needed to properly load iptables
        - name: kernel
          hostPath:
            path: /lib/modules
            type: Directory