apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local
  annotations:
    defaultVolumeType: local
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: provisioner.starsystem.dev/local
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  pathPattern: "{{ .PVC.Name }}"