# MC Router acts as a proxy for all incoming TCP connections on port 25565.
# It uses the destination hostname to route the connection to the appropriate server based on annotations in each server's Service manifest.
# While Traefik is able to receive TCP connections on port 25565, it is unable to distinguish them via domain names, so Traefik should be used as Ingress, but then send the clients to MC Router for them to be proxied.
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-mc-router
  namespace: flux-system
spec:
  chart:
    spec:
      chart: mc-router
      sourceRef:
        kind: HelmRepository
        name: constellation
      version: ">=1.0.0"
  interval: 10m0s
  releaseName: external
  targetNamespace: starsys-games
  values:
    common:
      namespace: starsys-games
    pods:
      priorityClassName: starsys-games