apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
spec:
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
        - name: pihole
          image: pihole/pihole:latest
          ports:
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: dashboard
              containerPort: 80
              protocol: TCP
        - name: prometheus
          image: ekofr/pihole-exporter:latest
          ports:
            - name: metrics
              containerPort: 9617
          env:
            - name: PIHOLE_HOSTNAME
              value: localhost
            - name: PIHOLE_PORT
              value: "80"
            - name: PIHOLE_PROTOCOL
              value: http
            - name: PORT
              value: "9617"