apiVersion: v1
kind: Namespace
metadata:
  name: database-system
  labels:
    # No restrictions/privileges allowed needed
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    # Log if pod has baseline privileges
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/audit-version: latest