apiVersion: v1
kind: Namespace
metadata:
  name: games
  labels:
    # Prevent any kind of privilege escalation
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest