apiVersion: v1
kind: Namespace
metadata:
  name: media
  labels:
    # Allow some degree of privileges
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    # Log if a Pod requests anything higher than restricted
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/audit-version: latest