apiVersion: v1
kind: Namespace
metadata:
  name: network-system
  labels:
    # Allow privileged containers
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    # Logs if a Pod requests full privileges
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: latest