apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-vip
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kube-vip
      sourceRef:
        kind: HelmRepository
        name: constellation
      version: ">=2.1.0"
  interval: 10m0s
  releaseName: kube-vip
  targetNamespace: kube-system
  upgrade:
    force: true
  values:
    pod:
      envFrom:
        - configMapRef:
            name: kube-vip-config