apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-valhesia
  namespace: flux-system
spec:
  chart:
    spec:
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: constellation
      version: ">=3.0.0"
  dependsOn:
    - name: minecraft-router
    - name: local-provisioner
  suspend: true # This server is no longer used. This will disable the release without deleting the manifests
  interval: 10m0s
  releaseName: minecraft-valhesia
  targetNamespace: games
  values:
    pod:
      envFrom:
        - configMapRef:
            name: minecraft-valhesia-config
        - secretRef:
            secretName: minecraft-valhesia-curseforge
      templateArgs:
        priorityClassName: games
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: class.nodes.cluster.starsystem.dev
                      operator: In
                      values:
                        - gameserver
    pvc:
      resources:
        requests:
          storage: 45Gi
      storageClassName: "game"
    service:
      annotations:
        mc-router.itzg.me/externalServerName: minecraft-valhesia.game.starsystem.dev