apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-server
  namespace: flux-system
spec:
  chart:
    spec:
      chart: nfs-server
      sourceRef:
        kind: HelmRepository
        name: constellation
      version: ">=3.0.0"
  interval: 10m0s
  releaseName: nfs-server
  targetNamespace: storage-system
  upgrade:
    force: true
  values:
    pod:
      templateArgs:
        # The local storage class can mount to several different nodes, so we need to specify which one we want to use for the NFS provisioner
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: class.nodes.cluster.starsystem.dev
                    operator: In
                    values:
                      - database
        priorityClassName: system-node-critical
    pvc:
      resources:
          requests:
            storage: 5Gi
      storageClassName: local