apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres-wg-portal
  namespace: flux-system
spec:
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: constellation
      version: ">=1.0.0"
  suspend: true
  dependsOn:
    - name: local-provisioner
  interval: 10m0s
  releaseName: postgres-wg-portal
  targetNamespace: storage-system
  values:
    dbName: wg-portal
    pvc:
      storageClass: database
      resources:
        requests:
          storage: 5Gi
    pod:
      envFrom:
        - secretRef:
            secretName: postgres-wg-portal-credentials
      templateArgs:
        priorityClassName: system-node-critical
        tolerations:
          - key: taint.node.cluster.starsystem.dev
            operator: Equal
            value: database
            effect: PreferNoSchedule
          - key: taint.node.cluster.starsystem.dev
            operator: Equal
            value: database
            effect: PreferNoExecute