apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-system
spec:
  chart:
    spec:
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        name: constellation
      version: ">=1.0.0"
  suspend: true 
  dependsOn:
    - local-provisioner
  interval: 10m0s
  releaseName: prometheus
  targetNamespace: storage-system
  upgrade:
    force: true
  values:
    pod:
      templateArgs:
        priorityClassName: system-cluster-critical
        volumes:
          - name: config
            configMap:
              name: prometheus-config
    pvc:
      storageClass: database
      resources:
        requests:
          storage: 120Gi