---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ddns
  namespace: network-system
spec:
  encryptedData:
    config.json: AgDGAP7biI2IbF41gzHR57BDynIMtv3F+PstRC9r/cFhhpEbpr4wSO1vTqspyy3djZeYl71fO0xQnJiTFKYpZnpftZdt9Q8gGOgiQfU1xfBlObFKIsNI5apTEGBmcaL0S+50AoKDpg4k1sofw+2Ene//4dJ68KP1rxISqaMYJbdNLm45mz4sLPoXsYIGGBjKayftgu6Hofs7ai+ubzfaSB2RaXBd7MugxnJTi8S5OLg4XFWrW7NBRwrJWX19OBEbuFoR7hxR4l+7tfE/51CpHu949iqUd3h9EI6HJiDbKfZdtZzkxttfUkP/CamUm2FsDLJsPf++VZcO7uRkg+IB3wthKgsYKbyIgQnwk5wUDOYSXgyxbSEkuwNk/ovPj0UFFFzlOsE0JJw7V5V+Cssln08EI0xhCSqVztQLDBSbIOEi44mWq4km1zuPbs0NA0XetECRCssi9rgnSndeYlMBZIaRMSxX+aFD2MiOVjVUQ64mJl3tcz6xRNlcCm3LnRawLdyfx3OFw1QQszaqlodu5eeBL/PMxh3PI6tFuSSrQUrjCdpEnMPAoTVDwHYiO7fAMnZr8B405exWtoF9CCtgJlclvNKqeFuhZnWFoTxKp+ah3rlznHuWUeopMwJmKge4WqTtBHnK1iMD2+iMBAn9HVW+BCHqrVNkORM/J1d0x+vHzH2oVxTjbXAst+25OpX8rXPhwZ0iMSdlCcP/lXNUrX285ixUTH983HjPHSH6n06GN8pGIrdJunjQItF8Nhr+9KkKCmb4ejRe1lbbmWHB1Z+PJtyUUhVzrGFCPG6Qru0V3cBZHMygHmGUfvzkqtaLNt4BNU63rC/lvOct4uIaVmfqKn0aWl2Ny8ZNXMIH5l+DwFAhwfYw9j1kCAf/vZ5XVR03cI4q71RJ0HPVhWLsuE0Hh4VdBBL0KWE4+UeyM3Ivpd28BVP7gh8+R+FM85alpjJMWa97arasvQ1tQloWtCdCUPZOV/jxyAWevrBhikwP8BDrAHkk8o4f8+ApjhnqAREj5Ykr8FUWx4x0Yay+cB560v8ML9Mflfp72GTWYVk0mNtjhiHnt211xq787JxQZ5Hqq604qHhri0DShe26MK7mGjgJIXkkHCkYbacw4L6is+723hGmee+uArdCEB1V4+X+eVIeOx7RS+kHS3HxnswBAAE/Fne/xsCp3zueGgepiKEbIeYSEOWnar3yWt7W/vbu8bj6LP46RHRHuDrLc6XGdRN2CmG89y3dWEHtdoFJCd883pTlQP+cgyoNy4cReGPzillvrmLD0AnaeDusFmn/ZzeDYkrH9pn5GgJUvGV6pvbS2A/Fldft9FmHGFhkmnhx/yaqlKt4ZpoUdqwTOMtWU3zvQZ9ihg8hX2g2qoFE4vA1aA==
  template:
    metadata:
      creationTimestamp: null
      name: ddns
      namespace: network-system
