---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ddns
  namespace: network-system
spec:
  encryptedData:
    config.json: AgCInxq3VYMfKFO0SgsaZbUhuAgmb+pH++Zxtc6KHkT7z2ETpcxgWs+jTkXHX33GO7xAOuuAPCS7tWeR77rl8vqNihgZuX5Jix0M+9aSsgo+tn5IADUOpFq8MfkX7dHE5sL19RQOss1rCp0yCcPorJ+0uyg2Uc/6P7Ie0IbzE6njrTy9HODZLBFOaXWCPiJDo33DEAyjwFsN5lqSNWdQwKkQVD5G8u8WP+1LKTvVPkBPnnP6iXi2R68EgtmJCQi5jzcaNQqQ4qcjeKNvsfon9R928xb0Cp7oEZ6vpR7GV4Il4aj+jLJt6j6EBgvEkXAHglC452vYHnJgm4rTz8L3RzHdB6i8zi3IUJZSc+JNWxFdWmVI5xDXGrnr0deX+SKWtc0Zp9ULCqcGPs3QXk6VllHZ84sZJtinSpnvdyhP9V3l+5IQooZzhyqqtFAmxhakOI6d2gFrdmPeICKWDhnsLVkN+7N1bWGBZ8em9lOs3hYjm3AWSkW2MjgrT5PmmybbOlCJueKohCzJF3vjxVBimeserztRUuWNz0vD6Yb4iU+VubPnSy4WtpUnQEaLG1bbjtUVfrvhJdA9SO2yQCPZHk9QzmU5LvCq7UD0rIEkJZJ5go4VVr5uVpkuQWAEkzu9g8nUpHzcAaW65FIYQCJIMrzmoFKy4ztaBiOW4DN3S8Gi2zu3XoABb7dB/eTmdF9eIpOX0yoYYUdh8xepKqopBSi/kZjbk9OHNxvkVTXzOvut8C0v1ilhnAQU48+LY/5USIla+GwQzB8gGsmw7RmR7TYB22TYlaJhH6s3c6c2sgRZkFrh4fRNhcdOwNRNBGj44sKVvxUFC/WJbEjBegc9+BoyMEVUkdVfBSki8Kne7++dGC9wdaXPmn6xRjRzkxh7DRzDHfoVG8zrMe6iAhQkHfUKMFMAb0g2CYMxvqmxE65WDs4x+cj9BsttWbnhrVqONqCUNiulPDfQ8C6BPodfVBLOA6DuNjv1A3wXvQg8EALB43ZbfL0c0XIxZpiaVPPGvSPMtuMprEuGWNO8vILp3OkffH+MoafliH2jtv2H7l/Gn0e1eiPc8mfOgEH9g4YOkVsxPS4MGV2ShM9x1yOctA9hD4EHm6rpMDjgxj/dPXeZfi35cVMIDPUX67QKTeMNK8iZ0TCMe9z4k5ZJO5ab902PWcqo4yOFVkBFDkuOGncsfV8ZJTILtqksD2TNSGSiqYTSDd1cE3sk6YFLASrHggoBCmjFyi/45FDdqcQTxlkBipmDo4TUMog/Dv5BsAfEr9TEQGAU8uRhWa2SmhS1QL+LAEYhF53gLb6ivZ7hZT2DoAq/OKMvKpB60Fz1ymULpuc+5CVa9O7te0gctdFlKTvpgHxCWE/gPq0ULTcJIsT+9YOfIw==
  template:
    metadata:
      creationTimestamp: null
      name: ddns
      namespace: network-system
