---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ddns
  namespace: network-system
spec:
  encryptedData:
    config.json: AgA2pqc0ad8N4wNI9JJP4N3tXh32tw9uZAGebh5HSC8ru/Hot/wJfjb7w8/NZ6cPzm7HsvVE74bQYWTaapDcKwXJu4HqodPRBu/o+0X/22MCzzjhNe4CA5ERmUOQO95RysBfJl/bumOWRLsKz87pMEi/7h5R1l6v8AvcTPW4OxO2fHnu9A3CBjYhW1Yww2U+B0KAu++x3Yposc2mxVDlwp27HLA7I7JeqmlEKijlm+jQpi9AzAQUKLpFZEf7h5dI8EOY99cODTCOkr6vXeNGzccTyhbgm8o7sUX+Kky87e/J0I8mTeHfydOycczPztN6oCB93urtPBsILC0GUCOh3xaBUoVY79m4tnK9yMKF3hH5DTrVy/i4jQ2e1sxlR0Nc7a0GMYDJpa/dkM4vfcY2m+UfyiJcsZHo/FI8DGiX2y3xIR/XZpg7TCr0qc74fu1odVm+f3VeCzOhgAVJ8Ut+e4RBOu8uFMiLDZtGpLsVbQKbkPOD3GD1bW2I/t63UwTKWJxaA6xxMOQmaGAMo+JPNTI/pIT8g3/riwlfCe2elOzVLfiF5sfSFI/AZSYnT0AL6D9vpPbiW/lDH5kQlSIBekTUBc5TbOvoV0TbFemAsoBNEsE9merae50rozzL8YDTNLECv44im6mGx9VG+O9vvBlYULbIpqL37zgzxMoNfOBERMyG8HKClQzvUZOyhSIsJOgDjv1qzsL6/lW6W9katCX8Bh8V2A8ehLsC7hJ3D5iM7Jy+uW3l09LCjLKh3a4+b47BAAo060SYZNVzSRbKnykzqRA4PIyc+H/QLuhkz9N1r/CEsahx5KWTLFnRw5V5J0kDSZyZxNjorcp9IpilYoEQ5hhnYzHpJdVhIfpFKf6HKtXPEwcnia2YmUze7rdlcfwTv1QYtClEhASKWOeV9vnVVDER9mogH2d1QGqdhpMHGIxEtJ9ZteMF2n8RqSuTkzlo5HuGYEJKhalzrDv+qw3HHlboIacw05dUczXU7gDzPZ81eXRT2SoNYl+eY+sNuVOFtiCgHbc9cztmoAUdJYQUK+oZkavzQ9M0AuGNYFrDZi/h10oMiWmAPkgEwDraZ0gM6qcMPf7C0AmiAgvRqejTBqTpwv37b6OfyZcant1CflhnPF8/Dl4zRcZ8GlTsSHjyt9hV6n9DZIa+D0qG9o9qulXG7RmUy4brY73eTTOp+MjaAbX0hI2R3MgKkcQzrxCzELX8ZF7pEy9rRvm76SXjfOXATNZZ8rvNhzXOAVAtp6CoHh1qmV+s3p/FX0K0d424x58CKDsmH775dvbMqK8l5zH0RguLk7l+3WpTcYt+8FO5q7FV8L2Qjfl7pO/PoAoiOVEaLYVYQpNtgP88gz8Ay5i7d/lqp/AaKQgL6Pz0LemC+A==
  template:
    metadata:
      creationTimestamp: null
      name: ddns
      namespace: network-system
