---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ddns
  namespace: default
spec:
  encryptedData:
    config.json: AgChg/j9+cGiSvFdq9/MkpPFe7GUXz55LSK4WT5x66lTPAtni7ZkBO0X/3+tdfF2sWYRiFH8WHAIdUTUxMKXILimvLEJajutT+HK5XJnYtVVCowYHBsERXsct17oq3YRuFKTWGvKDgzs8rsTP4Stnlh3eApRBxsw+F+XBFpKBwbLAYlKqPcSlrOga5ymalaV+Vj2LyFlXF4GHiNwiFdyXKfmHpd998OcyfltWUSrjkkpkEH8QxHY+x8qIjl7igmKXxQr4MXj+em28G2VA31+p8aMNm/jrolxOBkaGglusmzgQq2dYska6Oq5ZWFnnREU6dKB6ksFwpeK+AHzGPvAZVJ5iWtLgtWrxrKUOn+75eCwW4gigD3yPF7yvBskCGif197zjss3Hy/dlTjSyvxygNy3xuSI+06WVt45X3kSJ/j9jhnuFlIAxVYCxIkCLQO693cP1HiSp+hnLZh/reStq8jneiG0fCuR1NXRffYsLJrpgxHfOGHYJFHeG8YVC3uiwMzY24RA5RFx8rPSJ17U0l2yX4qEm20kBvaxmAv6Ba36vR71GkdxBn9qYL+zPtTSa/+NDE4yMMYdgfqc5TbkUzaJxyb1b0vm/1054w8cTjClBNsksxfCuKMH59g6TGDpMLQ+xb43nC4yF+c3kbxQIQ4m9wutPBJY7nxilR+qmCSloWW6isje7peodyK/Es3/v+KKXVL0iwM40d1uE6sNdcAzV6ky8Z69KRRoamlIxrP3WjlEAL88QVxbN5BK5aoZaOA8QfHPVCtjolxQMzvhhIabDMKpWdX52RH65DbN0HdE4O/U65wo4i9mQcfu+/RFmdWmMQbLSyBlnjFp+xa5liJgCv4taBAaFhllszkWFLOdV8+NfsZpsbfe3IyTY3P5eaG0x1ekWlu4bbVJGVU/Or3BnDC3RWB3g1CCBWuJKAtPHeGO5W4JOrEI7zhvy8twNIMspOZGhMMP/FwMRhU4v+n8DSztyv4U4NI8lrNcKyF60Yz72B4D8xQQOzMaXx/F7tqQF+d5r8sO4zNRQrqPHCNOnPuFuR+qFeqJTTUPYVlnyx5u+4GbPsi54IKE7ExBQJ/dQ237cbKXlHuvq+n6AOQGclZc694BMKshFSeVGpGUvtR9TslfBYi4d7Vao4WRrz+7XnZ324LFRbGmcCqohtiUm1q9tklXD0CGm/E8pko9D1t9nXX3mxCEFLyAPKzYyeIfrDyvv14EEK5oooLcmfw/mpLDAhSVlUm7qPWuCLAloA1mG+kasC0F5blwQ5xQB1CuN0sxkqqAKQOSwnK8w9WIO1BZ8NGJjabEPko8u8souddqUt9Wzo9Gve3J4Z4AlKsVyhgPoU7ODYgkvPk76CZ9dXqY/aLk/efb/mqfG+/AuhVTkw==
  template:
    metadata:
      creationTimestamp: null
      name: ddns
      namespace: default
