---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ddns
  namespace: network-system
spec:
  encryptedData:
    config.json: AgBZRGEe5oFcKHmrWflbcW/vb44SJiR6qMwKF0GMQOyxj1k3/HUjtuALJSpbVq9vl15cWglnyihGDob3S1QlHdWiHy56SZVYoCNDQuQ4D5p+uwB2MgLh7cka/V2GgDeajmyc315VsoiBbfshvgMLIYnfP9grMgey3ClDT3VT2klMrYbID61ckJockn6Re8muXIoYBJvQQoUBgVVOJ7EG8oxSRgEU1uIo11Ds6ZsS8khEYhTeNfFLjmvWKdraKPx2M9uDV2PseRdJL23CpuaOfjNtneUy+ljxV14cq5PYkGwhgQKfGfi4nczUUB9FYj01SoDs9YkZUNEhFUo91d4FbG+uRWSGpfYUrw1ebWSUorPjz7Ukwd6jsMJ0A+p9Aog/b4knFLSmibmUdEIGzKdvn0TDQM0QLiGiyC0McVEG2Sy+JW3xIKlllXMsWmSL7/bAIYgJZcXHgSVh2zufQzUHOCqDid4oMz1cXXUfVQtMXJvtv0kFY6Ou4l48d0j1sYYuuY2+RNsRhUOgEB9jMfI7aWzB5k2eUGHbdqkL0Y+i2U2wHKYYw1PDsGHqGDwMrH3/J5JllRBpgsDhvp7h88Un91D5D9Obcjt5ZxG7SoTIpuuRoNc6YvgrgZDzxclbQgCIZGIPuyCwubnNq1eKUvUqlWoHAP3tmxVeXfeG7VMpNCqMOO6Eh4oaHnyAcNHEX8N2qn+SI5QhckaxuV9uRX2PSwa+V5LoGZx6ib84UsEdlXEWngyuVq6RyHTWjQrmAiHVzhgiyKq+eWGb0ZA/BOPy4ShkJneD+neNyfByAbIdTdZ4EGN0gRlN2CvDVkOkDHzqoCCMtzoP4Bkrr3jxFg1mBUWolitJeOsAEkud56VXjySTTaKtL+r58T8qCJTywbC2V+94JStxhXHbCF1LZGGmX511oPhrLmvM1/oCDCtYP4d4NNvaU38ydcTpJY6R4RM/6GVhk8j/6c+mwvId7zukwYXB5Uft2vU/kx6iP83RxZZfFIouhvokA0uk9UrrmyYxvvDnZYItmqC+rtwz2Yg5vkHSf7bj7629B/vkQCeNeNspca/5aP/r05BOFW0sbHwrrJeg1ydDfWR9QDs8o+MRvJ23ySI6S9GyVdX1MpvCmC/fkHDEwroRJcF0Y5/YKzgZFMiVviNexRL/orqpEF4ZzfKzMMKmrppHtBIt1dCxVDn9oNbddHtqO8kSnjXKHHuptUCOuCOYerJkQyKf7FFewa7laCRxnLSRUnAGJ9t2R7Ily+bt+HvPw+rxYlP+mOtoajFbCrdIWpH960OtTPzjgp/8NrurUDAC/bSOYpHN2GVmMNEzmmAy246BOXhUkc32tFz7Q2LOYP8JnZuq4pRo7/K/0o+oMLz04dvqr7wtZrynEgpBrlHihFsRz1kzSs6Ro2a33xtvqnO6fmegAsVQrmB3P7DMDXJvZV0B+5fZ1Kqws1uBF3KZilaP7DNPQr+2lJALvjpTXHrSW7u/VuuZPE1K
  template:
    metadata:
      creationTimestamp: null
      name: ddns
      namespace: network-system
