---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ddns
  namespace: network-system
spec:
  encryptedData:
    config.json: AgCj1CKbn8Kjq7yRITAN6aPLjzlxWA/LgKP5oW0NLrEV5d3PMX2QoOKBHCw9l5DHC1xpbGV0EBdd3BMLagobNNJUobRuGzt0gaVKR56S8lZ0SbWf1XhuzzmATHQl0jyAz5SJ2nQwLwiOD9pQZF8nAImc0rA8PGyRr3ZeFEdqTdFL7IfLLH+jKPKFS8m/lqoIVJI8k95HoeiOPwsvMYEp6PH6zsJL8X9WVxOVy8N1XrdO0XRq1luD/zq8DsycDXtbX6J/OlRMBQBUAyg32qg5FNXpvMFRaXIxbXZXKYvOa0VzK308OOEmO0iIwvMWxW2Kls8s8OqaUYhjz3qkIgben/kCZadqXl4WN58Uy8B56k/+9p3c5dluXcoCfwhJwUZtQbgLd3EW6PED9iVewH4UTlNVGFThvTbjSv7980CVDAb9/NCJCyAAHYm2kMeG9eFh4eVQ+axA1a5WorVGO3L3NAquKRp8U2clwuKp8SLneijn+NNrGMIv2R7LQzzKkbaJM7IFXxkPh1chZW37oAFBW6/bLx7pj5iuFsa9gqAAYd4bCQ326mG3H2hnf0ckJt/34JYTx40GATapm9aoNhWw7Y3ZmTJxil5E7MzqsBVaYb4DBzYGS9RNkYp31dwEB6LIv3QD7HCAaLdpC+/R55rvqi3K2JKkibT2wtdnuRev5J1G6n64NL8N+jUNQiP8yyb/wH8aj+0r2nJ+N6zZwos/NeEQIRw+sIo5VINidRNqNjhFzat+XEyXyrfdx5+evfS3lvVaoWoiWKYhXR9vvzm0UWvW7qn3D+aA0fiuP8e3tJALl0E+3ggxqYfWT70V4i6z8pDgik1oNk2dEgoNlkIPssHp6V/ZtJnRhoQB1MEtATeankZDfhpsXuT8Z0fd2hcf1ndTjdngTgij2gTiQfkUxBt8+89039P9HGEJYpQ/BOHdwG39qt8T7uM45hjc38KBByzeCD82A3VEZKsFMikkQGqsRJvRz9j179NsYCbARYNaBr4/R5E5+chE72FgPJGaVKgYRVI4hFCpR+gqtCkEUPcluCRMLh0BUGRG92lg2xi37+JBNUzwKBYHSOA/wlm26+S+DkpLoSW9/ntDcU1xO162FacFXgLFHC4Lj2HwmCGQhZu38U+oiou4ClEUJk08wlDzaJ4EAAko7YaiSGHbmdDlAb6dxnaXTzPCu00qvVf5SP5JXCebpZ3HiSLbhSLob34ZCp88KoF8MVUyqgXPUEZfphY1/ADeA2UPNMxUHf3zKaFrCJhJpF7nL8osZ6ckkfhcdyU5k4XeC7+nuQ9RLGLIWmtD4IR6tlvS3uuoTau3yxyYoQ4EKczNWXNTsvjU7Tg2rahKXBFUD75gk7oc5jSOjgRw6rIVHCSUjz+MCFgCBT7T2VeNAmu1NY8rjlfw51EvbWkfyFHZqp7hpeyLpaM32jOn81f3sGqlnTkKCY+42RTTRz95TIG+OUEDM9yhZUEXAdYZEbRickDcA8+XdhUE
  template:
    metadata:
      creationTimestamp: null
      name: ddns
      namespace: network-system
