apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: flux-system
spec:
  targetNamespace: storage-system
  values:
    priorityClassName: system-cluster-critical
    monitoring:
      podMonitorEnabled: true
      grafanaDashboard:
        configMapName: postgres-operator
        create: true
        namespace: storage-system
    nodeSelector:
      starsystem.dev/database: "true"