# See here for the full list of options: https://github.com/zalando/postgres-operator/blob/master/docs/reference/operator_parameters.md
apiVersion: acid.zalan.do/v1
kind: OperatorConfiguration
metadata:
  name: postgres-operator
configuration:
  users:
    super_username: admin
    replication_username: replica
  major_version_upgrade:
    major_version_upgrade_mode: full
  kubernetes:
    enable_cross_namespace_secret: true
    enable_finalizers: true
    enable_pod_antiaffinity: true # Replicas will be scheduled on different nodes
    enable_pod_disruption_budget: false
    pod_service_account_name: postgres-operator-pod
    pod_priority_class_name: system-cluster-critical
    storage_resize_mode: pvc # Resizing will be handled by the provisioner
    secret_name_template: "{cluster}-credentials"
    cluster_domain: cluster.starsystem.dev
    cluster_labels:
      app: postgres
    node_readiness_label: # Equivalent of node affinity using these labels
      starsystem.dev/database: "true"
  postgres_pod_resources:
    default_cpu_request: 100m
    default_memory_request: 50M
    default_cpu_limit: 200m
    default_memory_limit: 100M
  # logical_backup: TODO
  teams_api: # TODO configure teams and create an "internal" team for cluster dbs
    enable_teams_api: false    
  enable_crd_registration: false # CRDs handled by the repository
  sidecars: [] # TODO: add prometheus exporter here