# See here for the full list of options: https://github.com/zalando/postgres-operator/blob/master/docs/reference/operator_parameters.md
apiVersion: acid.zalan.do/v1
kind: OperatorConfiguration
metadata:
  name: postgres-operator
configuration:
  kubernetes:
    enable_cross_namespace_secret: true
    enable_pod_antiaffinity: true # Replicas will be scheduled on different nodes
    enable_readiness_probe: true
    pod_priority_class_name: system-cluster-critical
    secret_name_template: "{cluster}-credentials"
    # cluster_domain: cluster.starsystem.dev
    node_readiness_label: # Equivalent of node affinity using these labels
      starsystem.dev/database: "true"
  postgres_pod_resources:
    default_cpu_request: 100m
    default_memory_request: 50M
    default_cpu_limit: 200m
    default_memory_limit: 100M
  # logical_backup: TODO
  teams_api:
    enable_teams_api: false
  debug:
    debug_logging: true