apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgres-operator:users:admin
rules:
  - apiGroups:
    - acid.zalan.do
    resources:
    - postgresqls
    - postgresqls/status
    verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgres-operator:users:edit
rules:
  - apiGroups:
    - acid.zalan.do
    resources:
    - postgresqls
    verbs:
    - create
    - update
    - patch
    - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgres-operator:users:view
rules:
  - apiGroups:
    - acid.zalan.do
    resources:
    - postgresqls
    - postgresqls/status
    verbs:
    - get
    - list
    - watch