apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-priority-limit
spec:
  hard:
    pods: "0"
  scopeSelector:
    matchExpressions:
      - scopeName: PriorityClass
        operator : In
        values: 
          - system-cluster-critical
          - system-node-critical
          - high