apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-quota
  namespace: tenant-jack
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 5Gi
    requests.ephemeral-storage: 1Gi
    limits.cpu: "2"
    limits.memory: 5Gi
    limits.ephemeral-storage: 5Gi
    local.storageclass.storage.k8s.io/requests.storage: 5Gi
    nfs.storageclass.storage.k8s.io/requests.storage: 1Gi