apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tenant-reconciler
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
      - secrets
      - services
      - endpoints
      - persistentvolumeclaims
    verbs:
      - "*"

  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - "*"

  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - "*"

  - apiGroups:
      - apps
    resources:
      - replicasets
      - statefulsets
      - daemonsets
      - deployments
    verbs:
      - "*"

  - apiGroups:
      - traefik.io
    resources:
      - ingressroutes
      - ingressroutetcps
      - ingressrouteudps
      - middleware
      - middlewaretcps
    verbs:
      - "*"

  - apiGroups:
      - bitnami.com
    resources:
      - sealedsecrets
    verbs:
      - "*"

  - apiGroups:
      - kustomize.config.k8s.io
    resources:
      - kustomizations
    verbs:
      - "*"

  - apiGroups:
      - kustomize.toolkit.fluxcd.io
    resources:
      - kustomizations
    verbs:
      - "*"