apiVersion: v1
kind: ServiceAccount
metadata:
  name: tenant-service-account
  namespace: tenant-jack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-reconciler
  namespace: tenant-jack
subjects:
  - kind: ServiceAccount
    name: tenant-service-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tenant-reconciler