apiVersion: v1
kind: Service
metadata:
  name: postgres-gitea
  # TODO: annotations for prometheus exporter
spec:
  selector:
    app: postgres
    database: gitea
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP