apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-provisioner
spec:
  template:
    spec:
      nodeSelector:
        starsystem.dev/nfs: "true"
      # Tolerate everything
      tolerations:
        - operator: Exists
      priorityClassName: system-cluster-critical
      containers:
        - name: csi-provisioner
          resources:
            requests:
              cpu: 10m
              memory: 25Mi
            limits:
              memory: 25Mi
        - name: liveness-probe
          resources:
            requests:
              cpu: 10m
              memory: 25Mi
            limits:
              memory: 25Mi
        - name: nfs-controller
          resources:
            requests:
              cpu: 10m
              memory: 25Mi
            limits:
              memory: 25Mi