apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-provisioner
  namespace: flux-system
spec:
  targetNamespace: storage-system
  values:
    controller:
      defaultOnDeletePolicy: retain
      runOnControlPlane: true
      priorityClassName: system-node-critical
      # Run the controller on the same node as the NFS server
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - nfs-server
                  - key: release
                    operator: In
                    values:
                      - nfs-server
              topologyKey: kubernetes.io/hostname
      # Tolerate running on the database node
      tolerations:
        - key: taint.node.cluster.starsystem.dev
          operator: Equal
          value: database
          effect: PreferNoSchedule
    externalSnapshotter:
      customResourceDefinitions:
        enabled: false