apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-provisioner
  namespace: flux-system
spec:
  targetNamespace: storage-system
  values:
    controller:
      defaultOnDeletePolicy: retain
      runOnControlPlane: true
      priorityClassName: system-node-critical
      # Run the controller on the same node as the NFS server
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: nfs-server
              topologyKey: kubernetes.io/hostname
    externalSnapshotter:
      customResourceDefinitions:
        enabled: false