apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-provisioner
  namespace: flux-system
spec:
  targetNamespace: storage-system
  values:
    controller:
      defaultOnDeletePolicy: retain
      runOnControlPlane: true
      priorityClassName: system-node-critical
      # Run the controller on the same node as the NFS server
      nodeSelector:
        starsystem.dev/nfs: "true"
    externalSnapshotter:
      customResourceDefinitions:
        enabled: false