apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/nfs-provisioner
  - storage-class.yaml
patches:
  - path: daemonset-patch.yaml
    target:
      kind: DaemonSet
  - path: deployment-patch.yaml
    target:
      kind: Deployment