apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/nfs-provisioner
  - storage-class.yaml
patches:
  - path: helmrelease-patch.yaml
    target:
      kind: HelmRelease
  - path: kustomization-patch.yaml
    target:
      version: kustomize.config.k8s.io/v1beta1
      kind: Kustomization