apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs.provisioner.starsystem.dev
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  server: nfs-server.storage-system
  share: /
  subDir: ${pvc.metadata.name}
  mountPermissions: "0"
  onDelete: archive
mountOptions:
  - nfsvers=4.1