apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealed-secret.yaml
  - pvc.yaml
  - ingress-routes.yaml
  - middlewares.yaml
  - ../../base/traefik
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
  - path: service-patch.yaml
    target:
      kind: Service