---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: network-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgCwVKwAO7iJoc5WvSsaac4mlG/UhKvXE0oxD6J5BMH/geaZt0x2nYx3W9fbL6GqD0cqyT5cBUdOEORLlcgPwCuaB/brysN2q5wM/LzE8aFTlT1DDdQH9t0JaboNnpca7vs0YMcT2maS3cE5fI4NMo7psVnHZJrVrpB16PhzUyqdb1kgc3cPX4JOastV6WzCdnPCDXNr3Q51t0iU4gevRHhOfkd8lQC7WNZ38MsMTkAnrp7+iOui4HG1Aj5nhjExQtdHX98f3n5KM2DR2qVNsekb3JP6lBEF8S5kggof/9pxq2Uw7RAWsmH5hOIyo+WK0FnDE4kRJrdUUzHw6HejlIFlagAlx5qCP0Of0ANIBHlwujreHyGZAXxOba9/kDKrwzi5tfJSukl2+jaShInGBwVOKGW7pFBFEXqZ8qkSBT5jMrLAetcEoVRcxFbyVyCfSDnNV4XO3p4QNU/5oxVh2/xxHNwoH4F7ehtF6ciZckCCvzlQ3eABPR/3hqMn1FT6NXkY/qUetxK3DdDrPmh+sWral9HQW8GOW0Viu1bU4qdJTd8PWJg5e/Mk+AMbQF6gWHpmnPFhO0a/5ZBspUwniuvuCOIVzPwjbp5l3l4qMqAhSwePAUr1sXDijszD8V4e8svMM2nfd2JU2WsTOY+6liQd/dqiQ0ohR+VbT3bwNEl+GSxpsec8xBWiOhq77g171NrET3K6ZaBsSEl/Ek1IrUuxG2gLv5TnL3IoH8GYHv+riGhXLYSaK38G
    CF_ZONE_API_TOKEN: AgCwAs11uACTQJIsf/sXkp6ad5Hduy8Zlj4K60AKhJjCdf4KV8KwdUDF5TCFrn5R8uy36ZHlBmYXwsKsRfgF7CyBi3djQsq4SM9q2ipbGoGVjXagATQr24viV7KuB/TOfjGfwoG3TebyCRh8XRRFvYdasOXANkecwR1Jko4RV1cKyjV5CgZTcsXjvjlUAhWXPwepTnWU4iuuR4k2xP/ub/bemOLS56MbbOavDDOJaYgp1PQbX0ED+ERs1/k/8tyxOO9/YrNjMFKR1CniCx5wEMFk4DV9ULVv4I0emPyxYeYSQz1liA9fyhE1ll0Jst55m9m1hS4TbADsFAA8E+bgv0WbPOOFWtymIm7TGGcrvEHNMw4UEQje4egQExeJ+/tl5oQjYDzw38haLg0fM+hnqFQRPX+YWlnuBw7OJmDujLS1vLmVo+eaqR4zVar3nsS+m7LSO+lEiGcOBRw7W8jQd98+fWPZZblB2HLbG5U7nAWXUDjyFQ5LFO7hxMIAblFvkfOba2cY7myFnJCjkfxZ2ptR/xN7kv9tuBIxwyyPRrcPR4xVlCH+IXRplMQBYIYb4YrOwtjB+KlaWGn0d8Ilg+ywqKSI+b3TilBxQcMoZvIqX0yQN4nwB5RnCCcEVRUaDO79fkU5WEMt1Lc8aiKi4GLwkMHvY5mW/nYapP726zelfakPljgj7zhgNqB+LLlAzg3Ftg3IJZAdjNoKfRJyQeglDEQPY+JhkYDXSNeQTXzhRVSR7qnLQdGE
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: network-system
