---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: network-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgAUVuNiVaZyZtWB5Z48eOGYx/LdAV35/MaiM5wwxfctwBfJJBdRs2n2O4NDV4nOkc1tf//XeFyhBiTmA/MKx2c32cboMFaEa2HiAmL9HICpV/CNys+X674PgbLlxxDBJwimCUS/oG+tDFbmv/rbaL1QEuj+YqojE4udHOBvYq8KKf0ZzNN7HIdl+GAPiwjlMR3NlE1i9RTTJGg3a7XzPFjCgVDAwy/XVHkFsvW+TidQSk2Yo/PuIi7d+ylIWXVLslhROZrdfdDnxmiQG6VWGk4ub6e1kScVZVssFpl03B3NAOOa+NHqn4q1YVOkcMpyx5SHXdJHIm4NGO1hAa6G2wmBs/WTW+KkO0xyepEKSOJmuq+cqlPSVHBEKMAp5EAEIAjnvtZDLIStyxJ/oi+xpyqm5Ib+eJbhNkVt4KdZyv1wkuLX7PkIblDaD2muLIx945+2vdDszF1AXRsghhZXVki94hbepkLfLBlFI8y5jTfAcqQEJogONqFSqgKbRCo3GwEotPfL9QbGTIeXc8WoMoeffZ4M+6I9il+DjZQxpvOvyFbhO5t6boCuVR/xJzXawdzWwPzSx90nfFpZGkRND+tslKDMnU4C81UNvoVT856W35HsMv3KIzWAoPMMivSPkr8Nb4jHwWU8Tzz5Smn1HUMvEMvbaFnKL9edNTg43v0hCPtx5S9+jJmJ0iwWhnC6+GfCaQsnpzqqHe7shaDqfwl9vyMg6Lb48l0HfNNxJjOLHq2Wi9Kc0Vrl
    CF_ZONE_API_TOKEN: AgBNtfmwEjLytOWhxEkMMaJtVKEO+exAkISC4DQjQu60dguvr/H04ocRqugOe9vlYc13F8NBzn5qjKQuJW2ZjsmRwssOnEh08zOpEbzdiC5YCEuZiLpf4czKiX/TMYf43udR8KVMsSlMqvgGEbz6xCo5or7pn0eA+4q5K0deuzH5zR9it8MAAlYtjTui7h1TLowJkfgPtZfsiR1r7f14RwTnMsq/FLtlegP0xyx7AvWgA9Fkw2FrDBebezB4q4sMJn0yaX0OxfAl3vfF3eLiRH1MNNLgEx+VMKBRLHGaKDz509Gtasc3wC1tS+5wydnxAKgb/Sf5VI6tTazBUJbHLalrYc42Al6NvUiIP1IkxbXYr6uie3j0behwnZjdBxJRagJJDdkOz6i6caQrqQwN8nhGVr2FZASgYOyw9uO12Lq7ZxS3xA9cvQYbTHdBnMVXwCJ+AH4qg5j5EjUsy5a4SX8h7DKgvbSbhMjDXkW9OKNsyJ9/ezcq243SqVeUkGv7a+PFcSvJvZ0s2M0vD7DGUM+eTPkWzz+99/mq/z/qxnXatNENvcYrUI6rPcvMnTKy4AFEF1R8anE5BY0Q7PjSdO6MLLSywXXNQeXdLEBf2SAFkSyAJ08RrVr7mydQQ+rVWSQ052ssd4t9hRlgwKmwPVbX4TV/L4gO67PtRbI7kbwMKUXwVC+zzSx4PUUQL9GKrtTtKnb+Eb9OmJzqnJViFyww1ELx76tu/rnoUzzgj9+7kuqVRZjhbzbT
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: network-system
