---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: network-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgCL8gDDrzcFQqWs7OOIGxgpYKgcF+uEGeLGZVb31AkTwpGg43h+WbLIdDs625hpBI+F11+0/4V9p/BtqjzgiOkmlDTXGUMvktMZh6K+XLFQpoLIv1u7DzppjZ8AR2ogqzQjR+GMfWwa2u5AucQG9atjct6kW/+ml2eG7h2tib25LbXisJJU6X7+RUBZHX+fe6cI2VaG+5Jf7Jz+OKyi2iOzyRl5/I/RFXa2xr3FlozGYBniIu2JMOUiUsbk8CZFb33Ozoans8oDmYG7t2Wrxt+2WR8lQeSQfAcbpJSfJJozP7QHBcrhnmcI2VONI2f14UitGZa07v9qva1QSIV3IliexGROWecCsiY0j5fzk9SdV96toZ1/vI+pAxvrhB4Gpoc+Br4IEPQgeXT82bM/E5E3ZD3/p8Wf2ITPJzdQM7abvokj1FJepENqP6z+q2wyoh+25mQfvIPpltF6rCm7gUGNPmc76ycyIOk+0rAc3jM21BlVDiSVBqwbjNiEUSu/JJ1vImpHe6y6qqiFTYbFkRv/vkaPUJu9yaoODKE8kwflyPjQZcfmvWjvPYDBl15dFjHujgDzYwxFgXPuRgGnqrNV7nVkO9OZHe5NVZEeYbdyOnj5M0OSx8ph5OUSmEbbHFIE1IdhQSZXj4cEKmEmY79J1rUb8xvFMMKQd00xIp9nA8njF8/2ziKeynQneZ5a1btMp2WGuoxLr31N+0d/N0OapC5MYJ/5WAGC8u3gWdz9UmGTEb/vwSG/
    CF_ZONE_API_TOKEN: AgBC8vzso4RG4SP90hzb9ELhy/Z8nl6CDg38WfYNa+Y1OViZVAH4yQdVl7/uStoUvScU+ILbnTWP7Im0dVzss/R2Q9A/4BHuCTvpBxiwuBGI/b1YrP3OTGpmP7Fwh7g+9Sf23yarcLl6Q1bSekDfaW4LHvRZAyIOPnzUbzRKkFUiP/lhlhNjSmVxkwgl7jRex/O9ftewPvFXyf0HnFzAXL49vSHlUpZh8HKqCEFPhUveev3g02vyT7jpVHfRgIRdpitcIDWWaafVWZpJhZTU2sY02uOhcwB7YJuUVGw0NurLAQ9pkdAjpc4RLZQdec473eQFfvUf4OqHKmb0BqgyVmLBbmzyFR5bDhUql6YE05VU1FV5eZbq9so06MXpMCET8ce1vKWlpw18KjSg6MOuvqXucFAx4hTlEuTFGHJ5iU/ds6cYhSlO8tV62p5CRnHXAqT/OMjQZqHQ3apD2r08GW3keLC2/HpoXuxSnUOcRyXOyAJnDsUhMPD4TOef/CdTpsDCNMesj1l66VI72H4RiDGuGq0WtD3k9vfQx4WnMaj/k8XRNBzQIAMqy6Xf7R050Chb8HJ3vt4PGwCriYJs8/ewDw1QKgiL+37n0VAs9lqJwjMhdGiKWPdAF/egPDUl09AmX8Wkb6wLUeQy2lweiE2LfpdA/nM32QdZpu6RbewssvQZnMPoDaqEGqBuDjcQ8jYajLjPVQmgWS/VrdfZ7eB6BE7Vn8eLynzpNSfPvRT+0Z3YK4cYPMTZ
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: network-system
