---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: network-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgCATU74bUVoAAAzyn6/t1d7wJ1TrAXmHSWWR0PGxfXJcSxWyTSDYTNDIK+dSLriBC9eCnuacc2jw5BF9QEZpTv4JXj6hlwoXt6MPMZdhYiMnKx7/r5KsJoa5raUM3PmlRFfZJDEneKRR42z1T7V2zWjsiYBvCi+M6FYJlAwHjrLTr3/493MTEb/HWsCgiEFWcJ7Lb2jBlp1WPiDZV9WNdSNcoEWgIWrK3x10+Xve4Lh+9zG+gh1rEVm0N1FN8JjLFQoOM+61SDiJniZwzyMTbwPHwwxPFIpQ3Yfpi4cQqGmK3qsEZGyRW96kJOhUWKrZ1ZTM1CXkQXVEDqEF4likFu4hL0OAjeI8lX8tAWSsaGIBzcFsrAJ2dr6Yn5EdOjN10Yvt6K611WiP3rW5p+qKoje8MjdwW9UM4fnSJL8Joi3FfpKBr9Yh/ntL40putCfaOmT7JjIk/X6NxBOm5R9d3veiXmhX6ro9eAoMhHMUQshyy2RgUZdA3xQqEMy5dpLblf1W3RwFsxDhry7sZx9xEzt2qtBLplPUWbPndGMDMULd5tYk3Wpd2xgNkNuYWDTpvn7C8S3gOTAz6yLjVfapK0WXka5IRNnDPnWNGgKOD5EwgeNb3u/3/PTwqSzp8ddTSOUt5Q+dWhi/5IoC8LZmY/tpAFxxIkOE9qUeN+Q0cUZ7N86Cdrmy5XMLNg3Pp/51u4QBe1Gq7zNvMBMEgB1IL4NDMV6bafb01s0H4lExl6zZJZR/lzrTr1u
    CF_ZONE_API_TOKEN: AgAuARRDnZxLLCJh50PSJ0a/F3N9P+dA1mcSBql/Dt4NXo/s/8fIU4Y4xJM4APmTMopzM8zB8wX3QRNj1yqifu1vyuLC5DyLMC4IC4TcB+iPaKRvmQFGqCYYNIwkpkrjJ3kBrZiDc8tPnoeBNd+mp89LriFlL/pnYj6RKry2NHBWdR9h9uiZJQ/i4K1tmFScDc0NMTrdfNGv/G0Hu2+j3RH7P4rKkcXgwCnYvVYgNh/JCv5K/ijWUmJa970IGO5zGxFn/h3D0+JZ96ChC9MS3WZlHeOKlHA1dfBU3/i2/TTyAqsk4/y+992jgUh3ifxMA+XFWMvwt99pucl/m7Ny9g8neQw/lsY3l47vDt8/bMHs1FG4T/Hvu6xvCjmW/2HCrZb9yiE/CVTnm1af4YUYbMpF7O3+0iW57pMD238lXtWv0RPU3IT6YSVGCgzqd+IEmkJ27y6EoJeU9gcj6gDZsrh9zYRn0RiDXFrYbDZ/yHoBtXHjEDoy/lOjY6MOZzV378HB3jHtQuXtIVZpizHmDGArgYspb6jWtgMAzy+2j/zgT6D0t6SfGc7hbrOCuKpiEfm/LOL4sUssA4y4hMeHZaGD2KLad6pvbd3SKYky+KScG5tQG9YADuNoevrcAwWxppBAZ7oKqstF06SPcDYmhNXDMr0b3fLH55SuAHNkVQG1qF390bZCrvDrsL0cFE3Y0dXyd8r15KTWXyJknilF04siBUS5/eqYX5GiHowxrjSVA56RDnn0iHgp
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: network-system
