---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: network-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgBmW7OAEilH1KVBCr1F5vlnqwF+DA+iZ+HUeYakWXkOIqqNz5OwucSwJvwl/8veDMjUl2RaTO/WR87DjsfYUv9H8Qd5RklkNzp5K90skSO9qafhyVdlG/kD/guFh1/Zr8bTOHgBjNyVuWPBwLulPYTDVw4IOVLOF+//Q2mT0igKiC3WoIMAOnWVeKKmN7pS32TR1zys4W0H8k59Md1onEUCNfPwf3EOk3DfVgtnb21ZpXZU1CG5L3T6jUw7rRDUaz3jo3psXPQVtOUDxIDSfmEqgirkEsAXKvUkAvi1GPpgccss0tkVCjoe2DYhOoFtlHPqvHJ6pZnOV88VIhwMHKTsWtQDNEnB85stKofEqQzKk9M1cYVB/fSdC6eNtlgHab3L9sFNIr2hQrFaXsi0uaG6O7uzJPMxNs/gcYphTW53/4u6Mj+PYyUU629GwBCwSyRrykvcJvk0yES+66u47LTXZbgzVQdU1lr9bNiIurOQ8qbJmIt4/QmMZA6YM/p2q+WB7apr89iis6YCpS9Uw317mc5YhywA+iP7Bgu6SuJ0oN0jeqKRFwWaxi8KmIOjHmTL6Ip/5Y57HrfS/vXTzCqeo8u7P1CG8ngagMnjtPNVlKOThqduqLTpx+znnzV8zehvtQdLS2JKlmUjhRfuTUvotj3zF1ENx55nGVylyJ/+Je+CUICZi/9TU+IsM6NZJFp0sDuVI0fWqG+FD6hJfeY97GkCiXtloXA+K4rE217+aI8wyYxONibb
    CF_ZONE_API_TOKEN: AgCrQMZuO2NiFjgxTtGph30r8e7w2nAvLK/g88UAhYyz+xpAcdHb0ZR/u0xq6yDQc1gvsDZ2TC6WcorMYRLpbcLOc6v5g0CkefpNbh3FNHGIqwNlaNkGMmDFS6EDo7aNebSNjg/nW4j+D0dKIVAxEld5gzWRPYszzlIUBXA6syUIqHHyY1Vkx1Bv3jdwjmndSi9K8tZ0oIcpggZ4inaW2qyNj3tggq6AfomUH4MmrzV6IIOpRdfN8tgh0GAoQ+iLqrwNL7J4O6mqe4ShWsa/Ee6KSV4rr8u4rxPTT9hKMXul1qgpCg4rreVhsg17G2uv0c9WLFILK6ypPV4nSq5gGqB8FNwFn5/NtgYN9CT75uHNWgBB3FG8teiwqurx16TQJAMHM9/NwpdOzIOIu+RQ/zkT9aYajE/GWCB6xsOZDVBji3blS6LKCxEGGjizIr1gFqBXDJYhJcgvnmEael4/G71rXZFze0HVnfRnDG6gmNZPsJlf1hcbvEmpCulu6C22CU4OkfCD3P9XsKTfCJDegA011FqtpBpBP815+Lz86DXiebSj5ec2u3TsvXpKWHiFNYW/uye+3fosLXtghOLQP/Bfftj6crCM5kGN9OEV0WawdlHWttMPh3qKOTSZ/Q4Eyrg9H4WdMrNULiDMvacaRwh+TeD8+OlxgFMOaQOeuiluMi3Mxttm5tflrfKPAGKf5v7RO6bAxpGwbqnveRfir76E1xWvzWipBZ+sV81QkIPzKhNQMRbDIioa
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: network-system
