---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: network-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgCcvyHKIaMcm8YnDN4IonJfzCQ7Jo7cXzMdSkrWnwjvgt+BXqSrJK2vw1ofDzm1Bee+Ow9s92sYLoaZOnlZqfEFhVEtj0WPriymqAEE4OW0QZLqk9LG1cZQ7gZ4wfpsOjiHySVjKP9oymaGGAgkhNRsRE8Qa7A9sIbL6F+7//1BRNafy4IHKr9af8ZnRUgGsRCR1M6HzO0BgrHFa19oYLmnUIXMQWpDkfc1HUUGPKPf6omiiw7SSbmLU8BTxZ5ZeMnFWl3ZyfTrvm54JgGPdy0oABwvnKRyiqDoUPLGLXyi1V5JfRJv9U5FSXvIU2D4ZIZJGx6VIwb7Ao+IvKca8OMuPeFbz9+kYy+yDzzpNlFDCOESRxUJHlOtMNUjnBMkvR1JkmX91pmND3+ssLtleDoFdAeSOD5QYRpfVrfU8YNE6x730Rmz+2KNsBwa0Oks69oo53atjviHzzgk3EWoH/1oFkPQSv6eWMBComfMNiwEQARR810or/KjoJBs4ItdvHz+TkDCW4/HzCtihTwLqkp+qbA/f6Qop575rSivjWDZsKYssvdQZmhalGlBcmKkk2ECyfTCr32xkhyWORvfF/3raH2Ad95NASNvibHjmE20MwV07fWqG7wh0JKUvGuvaJe7i+gn4BCUL1dcoT/FQqSHo/u/9CU88PjFU4C8haB/nSdiJe+Pd261ZGtEKVFAEJxGf0g72l6ef6N51JMJrMVG06JXQNWoAR+NXyx+lP+8D03ys2iCN8nz
    CF_ZONE_API_TOKEN: AgCMNrTba6Dp4mpfW+vdr8GRhaoPHuPL/bwseV51HJb3CmewOxRbYqXRg+afbKAjQjdD/DlGxPKxuxaKb/t2FaeziX+cVmyCnbbmLEvtj7LDwNqoCQl/oVgJ0pjTDZvhsK76jEeWl49KAiwI6DecSgsa73/SVs8ie4dXrlRAR+IZq4YPEKwPmMEBUIsGhgOu8aYQY1+dos3kjekaFGG/f0XrbXBhIT3khdokkYX6569kw8Pe5veB/u/AveZa7wSYLsPVa9uV6IOGNX0TR9EOGS1KD/Q3rn1MhgjNeGPrD1ryDXchPa8WLTp3cEh0XBi7yKsVpyx4THIM5bH/chk/pEpIKCWv3EsCZzSl8N3+MgIvURWLkVA/jGhttxG/vYZnnTKrniM00+SHIhiR0IZ9qONkAonF6P930o4tK4XAB8WQhtTlfhRuW56ElEVVEbRLCG73v31XRe62z2Ma/PQU/Fu0kIbPLWJV2PXtdj0yk2/WGMnziJychGB6nLJVh/l421CaBl7HiiLHJvWAiVcb/2ZuBu5OBwCQh0zKk1FGnWOj5+DVEFyefZ1fcA/L4r5OVv2CpjGaWV/9NpakIbd8+HiIq0GaXsgCIsQD4e0bhXJVpMgSRp2TUPLvhG30xoX4gzfIGuF37lNwoExVttLPVLs5IkqLq+3c35CfdYosR0202Oe2GX3iDLQmCxqNxr5gRSwUe6aKiYYGAvATeiW03LqQ37adRpTO1RjLxtzBJUyzuxJanoC4Rin2
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: network-system
