---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: network-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgAcXBcdqQUSkpzCmrZGvIve9RifFPHb/Ie8JH02gVSJIZl7IDxS62ONEMVaCcpg6JPEK3sQahYyE71ZvhzB5EN86YYeRPabon1LYeXj2NEcNsQy/x3GEsfcEBPtsk05l82+Xq+ErBNgPwSiEfVcHyHiIlu3yHFKipdxynNdAQMLpNYYoUdjqIssiNoOnbWzfq8Yc5WdiHOo5bTeGEv5quYZVZ8UxrUejqeTw6fi0szaH52Fs55hW9+Wdb8y0SaakIw4SLotyXqNxM3pL753Lqx+zfduT+u+Nfsqp7oE4dWZkvD3UVMG8F31Yxl1zTIWmA4adl7QbWGt7iIuHbg6++E2WZYktpB9Yrp2vxB1B6LJcZ67he21469BE8QdBfmsRCvlmkU08SQ8fdvV791lNEeZGpvaMEzh378GJTa+Zj8QtYdWaLM6HkvL6P+kj1qskylqXOTcOw2M4gmAdI2jztxI9LMWp2Vi/dB22/Yfjd2w9lVc8QOI1pvvaLdKn06ADc67upIQ+X9+9fAKH9GKY8tpRMf5+118KJ8H8GtUpA/XAVQTu6h8q+s2E9jS8iXAsA5M7oldveYhTxFhM/UefNKBLtG0qtQE6xURQQChFf48FBfPHqx3Zg/nIhy3o1w0DknjBsgGgz5f+kwnEUu6mxDYTeLI+OV+q8xCcIjjswETCZZRv8l/lAE+s787U5Ryn+z7Eh8F4+rAyq3dIP4uiOtT7lWxH8gnpsdGRTOjLSeOEZVElFDv1aNJ
    CF_ZONE_API_TOKEN: AgCe9uSRFJqnPLndZJA3bP3wIBYjckvPVGmlsUGyO//sdBSvBVrpV/uDLmtQOPjKPsjj+2zzQuvgBbgVtxUe5CdMzEryMqRXBgaGJt2dBsoyhFqFhsBloml3kQhJhvHED/CY9uXZ0gsSduRbZz7eaIr/BWN8v2+95R/bSNI2o0S564pbx/KTy11lj22YlmXASfw0HlWJngc3+yuU86+DtTgeOZv8E6+dVIWlZQp9vhNxjDdJIljK3+ZpU/s0JkS0FQFUdBEcSVe4JBgpjuxqMRLNVSba/LnQwNwWn/JMjRgn90E1vrhkmMQIATP+RPIq/tqoXS/h7EYQoyekSCzHG7LiTcNUZ+mIOlyGidrIee1Hr9yFYlMbnT1p9GcQ8R7n3cZ0x8YEB+LCnTXtOggTqJuQm+J534SO+0BWRP0IpyIfcfbc0zI/ffhvb2BmTFK1VfTBfL0FiK5lUT6jzYfXf9jpII5mdmxSaDu+7qxFLGLtCC/kvc9UYws1T+lLXL3An566aH795YtkJ7L/kYTyiB1HpWKo6VUpyNQvYJYGf2FP/hMQm0YdP6G7m5dLSg9aXLYvet917Vv2rYs7SV+8ePEm+y61UDVPiB2EoYJUqnBgnqyOjcWUt64S+OR5d08XaPlgqy8r6zFwVnJrTzpc+vLLRIh41Yu0EDEGtxC9q9Gosd7Pt6HC5xJoDbTHLkrvP0I12VisnPOfkNjpdH3rzuso7MO/VobaACom52T4R+wT8Vs9DuV5DcsW
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: network-system
