---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: network-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgCyLLibw1+qj6AFy+tolaDuwsuWgOLmaAw+5BKD4I/tK5At40Il+eHwRsfruyJrhP5s/y9RZneOCUFTDMSODGTyTRS6cH5h/GxZdwbZFyYKvycN7luiWur3ugDuy0Z1dPenNjviCZPz2O7vhhQuHkLgNUVC7bZasyOAHGaLWLLQiM4AvlFAbg0SFhOsLSiZASTzrLjd/zO2VUFs6X0Lxik8HpXiGV7zkqTQA4QNPa64xFzyiFffrB33xS52KaBO8CKJdsOaHF0LTDzytyVNx9x14rf6XSIw8Cs+C83ShB1irg5fLgymdS9LULVzjEOXbT/GUDLnCCtCsjaZzzyph4SdQECjdBLW1VHlGV2autFFPZBXcAjoFadAfYPULjhCXhrYjsn6ZTOw/oUdH35/NgysjQN0jX1qthokOoY/qAn2OqbTrUnmQqmBrpLyCC3O6RfQouFzEf6Y/9fzlLS4jF7o92oAs8aDaOdDmZgAS+hO4W/TMJ4rVx4NrAkwz1qcOrwFyeFoL+4C3DqA/gw3a0fOFnHNWl4ykscrHMWRmuTcX3+Hz8puuhm1+OINAf0uYJf8GSs4196YF9HO44y0JPBmudf2LjvWm0up12OIaxCiQRGXKS2yRCT+JHnqlcJow/4b99m7+gGDgn6bvKYzKndMgC0rJaynHsBKvQK5ZJodyrtqFTLcX2IAvS7NPhyBokGZ39SdxXQmS9ud2Bl29f84F67bIZrViQEiy2PhDG+dns1Cnh9mSVA6
    CF_ZONE_API_TOKEN: AgAINUWNEinDZm/L1BkJC+jaNW1NVFuBE+sRyPdyBdZVlcyhYe6PDyBrERcoMWBPOqWyTODO1NOAipyKM31XTuDlOD2FV4xWIBIOeEffHc0Yk4zfqMm8wHN1ekU6qrD58Pb6DkuBgtkdQMOsmZsuWfUxTzte1Qg/cijAwjnsP7s6rKVW6MPYrcds4ySCOz6Bb3o7mOee4+Nb2OGws0NMAPx2XEo2s4V0ae0Yci/r59B8sVjLePA0Dc14zXRDhc+hYBS6ETy1yZrdI4EDYz5GEeIo/QruO2ewCKt65I2nhJiiPG/XDitVef8+AnuQb0C7Q0ut0yruqTEaZVjx110mDaye1/BBpaOvR47QMBDgu+5JCtAn+T3UYGORZqpHFRXUC359Hab+R0owCjcgKgXIV4+DXqgP+ar4jaw+eG+uGG956PuCbnhzQV+47RfU895utJPkHVhwFC/sbRucBv8pleuyru4H8NY64C9b1gUwoQFNNsi02XyJzcwrFFEAdiad7HBjpB/P9BUGdZPp7ZqA8Oj7jOPyS6/xV47OW/tnrvtN5sTHNqHDxQKaTPDTEmkWzRVUNijNex1yAw+noGVhCOvAUXOJ6pfw020qZXUBJRU7yKTl3IakR4BpNOP8Ixw9va+eY5XtNddI5CswqCYSRa9X2YXe7PZBOwUqoXvAdZL/szr9w5e6XVFGPJV65oHirhL9P+I7x4Gwk5VqCIDzIMHHrqCYrrhwP0UpxLaQ3S/12J+mvEa+sWGw
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: network-system
