---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: network-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgC7TIr3ioj+H13Aytx6bihCC3et2JASvd6DG33p6bVduVEXIPAXFk4NzF3JJ/zYnh4m+osUKp3RlYsMKGWFxaMSIsBjjWc1FHfzDkw/THYKQHI6WlU/hptj98ssIebVDW+Ft0u8e96I3qtiSULe7NxjnUBTdG6q8CdlfAX2u+siB1HAKAIOm0h/gbrwa/igtBbJMtQMXQIB8hOBqbMOv4Zva1k/9IDXBFFmi7rV6319eHIi6geLkQ07JQbEPqZkxzkehR3hv721+CEVOUx42lvT5d0349BmI6g2jfH+6frtObErh6U5Ry52jtxq0A7pVSb4CwAowxaClnjQxRPWxdxIAPyIaAmN7usGHjIYAWR+cwNGzZD3KTKhyYRQB9YGZPLLWGVT8XJCLEfHG0js4M3fyalSJevhjaYibQZRSgtU//j6wf+NfoOLd/KQ56Q5yNXsD84c0Z2rlkhk0NB852bF3j0TAaOX/JJuFwdVfT40nV+eknPmOSE2meivGQbz3OYBP46nctfW3se72hRi9iGloNrrjV/3fZQWVmJxjxCyc1e+sH6q+awfRX0kRpY0Y/JlG/D5h1XwEt324ICabi90GBHTI9oRq3/7yvfNJ09w/fA64ahVOm5LREmIrqjOYyZLkbanP+A2JVKsbgULsZtkW0gx1ThpP+RqjDd2BEwUlB/W8axQbPWeaJi+5hdpOrzSHrC63WRTZ0G0CVy8LvaoxQ7pm4ehYAKlDyUXlcW7ojaKrhaXAZdi
    CF_ZONE_API_TOKEN: AgAKSMyRS1k2wYZ9bR8vENtM7dRrXBlFTuAe9cf76BYLN4cVRKbppKa34ByTyynntIlobC7EYWm901xTjIEIfgpJPfpqi+A77CPYBwfijhVEKkd2WUCJlPZWto4YMRCqwxX4J9GQh90tQJ8h3NdLxxb4Ru1dV0cHzO0jUcp1LF2ERLX+Y4+3qmwosYyDtjBANaH1hvfPBmqDi5Mfn6UpG6qOtDLJWiX+P+3IuzGOym1leh9DZrD9Lbc5ADhzPmcVBCXgp/+GjkiIVqopkwXh+5JRJkwtzOvS+Fqp5JUyTFkYwqAgeVSmnane8xsSPGH2fupZo5F8JjXME4orTyrMK3Ypx/5HQ+rQmE6GwO6EvE3PrbDzU9Ejc3DszQlH0MZ5o9IWCyT0RFQ6Ie8hDgGsSGY6mxn2nqatvc7s32YHahx79HMyso9eCeI77pvypC+h4+rJl6KOglZnheX2fPTndDMK6LNCw4dI4QEYCHanVbGBweaoNMg44zkgdBbdDoFctl2FgUHaIlduBt0sArRS0sgyHZMrDWW55Ibnq5v/srOdnuZOLq+P8idA3LRMFrk/864gBQLDP8kdnMSUd2yKOV3+PRzPhfCCsVh2rUv/VItdJivC2hYo17xHDSc39vsLc+YYnY8azwjNM1uCrZPHesjW/44Ja9dP/AeBlJIHi1QjkvA7/51RlGuczasNMSgp+Fl1sRz4iT7mfUzKRh0Vsw/ZzD0zk0Vbi6mi5xwz+gBLag/2mxiG53zF
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: network-system
