---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: network-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgBC/CKRgWw6etjIZLznueFOHHVVy8nqmBzIUsDC5tiH90IeAlYbhFh2e4GlrABP0XhG/kl4KiUJ0tybYrR+BFAkukDETrehXBLzC8m//yOyvEYF2PQ3Mh5u9NWqj9nsj9FjUkPZE+nIq0Pg0fAnzv+WwiSNspX4gHGESKyKlcaRBZIPIX8pXl+7phcrVHD2+hXO0alFgm0hmtnGPqqFckKpp0885QYgIYppEG+pSCmY6SXxtww3x9qCEBejQvUtXj/EXK2tX2zk8cLQ+/fUmgQq/4bRY68KS/umD4Jt4kKfE9MkRqTSexwNi+mfaTItZvDqkjGDOaJl5SnAkKtl71RaVYwfE7BNBw7u0J76OGbvJcthID0oPurywt/OuFbKzbc05edzmyOpTPhXcliZhXXiS/4oGFdlUdBHmkaHi37slrTonPy+7D/KYDHvh1fxCpTpNoDVW2DNb9e4+6SoorPWwQsRd/OHjkfKHIhcaHbyJ4oTZ0gTRiNaSRqiEtRsM5L+zwTZb/ATQ3XUsJ5jKB5nvDEb0CzodCYf4XPMpJD5IEn8Ykt7olNwNIdRIcJZ96WkR8ZIxDilfGcZ9EkGODmwL8N2Pmkbeo7SUVAtL/uJbxTQx3eTJTEGTyt1klZUCsvyYqsGawk3afX1JGtBTMdnIFlKZevZuo47AOIM527CoEJW0v6uINXHaZEAsWQb923NB+kyVPMzM3hgOn7U4D4IUKT4vdnfrY7XYIdNLbu+YbXmxNDhVrs4
    CF_ZONE_API_TOKEN: AgDFjErfYQhVI8TzIaZb0xXTnkX2xxf4VFjVDWgIEl9Db8Pp0nDQ4OXQT6yMszL9xHU+gKNxlmCqdwzgWjdwe50HJhJSTxWeXdxhhM4iLUbCWvv3/CWtz7feVmjtAqNKDZwGekVWMTyo4P5NXxOnCMfOjjdy3BKF5eACRWlAxV53wN/XHndHN8GuxXUyW1t6aBBJHNzQcclyVzJeUYplmZPrJRU2vUMKmuNh7R9iQMRQHnFK38BsRGZMOKG00jOaWyrKxR+gC1lkheYRp+XHtpxd0EC6G4A7UQq9B/LW4zmV4dQaaUGQLUx9fulBT07ZR7uuK3+LH1zWuYHJFmW52uFT6zgd5wHKsVX4l45/zKxup3MdulBWj8GK2zk45ZkASpcE2sWecRksAeYTuQYyRpxI7XN/OK3JeI1Qh90GVDVN/BO3CZl0uh4ZAVB/yZIPMM/i8Ec17EZG6hd4eIn6VG+ojNwmnbCM6Zsc4qWSGgD7NpBbK/7hbkj+FxJJtAzTUQt/zOIj4cHR54zpoiV+qNnBkZWbb10aMeiW+fm+EqQleFZD7BkPaSAefrlBgErIaIG26wjo0KBzR6Zoc6bGBWZeSw/U4UI4Wc7YvQhT7D+NUOPsqYno4G8JeocoyrVixH0pKxXl3Mj+g+NESni9EnuC5gwOhsn/Hvb+t4CJUhBWNPR1VLt6KqFp1WRZRSJIeUKM/bHkpMOlv2xFZlYKEW7e6IkRce1xYUoY6qzVBYjyxocG2orBhq2z
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: network-system
