---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: network-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgCjPpLoydd+VOJxBpHBJ8DIlhzYRu9uj3fde3b01KQUAvlaxy2IE8bkpwFQDiFH/Uh3ktW0ymcT3+jaFo3z3eaILxXa2dAqo6lTCF4yH6lxGmc8JJjFoeP1U25LgaDXbUvMTPeNgu98PmqNgnmT0x8eAnWkFlKgezv595F8BgtQCd//Ma4Uor1bFLxARve7G9wkwE+7UVNm1P3UopWy1GEiWsF99WQItVrEqP2DRef0/8PI++VrzqHKwqYF2vaNfjw7eoeEFcxEo6eKncEmoTbw4qnqtwBISKILXB1KoRKq3cximmPbqyBfbK8hYuZLUm0J8wY9J08DOL02ggGoT1zokPkki2vwAaAcyfQmJsE0dh1ILriPzDVZNTiSFckNUU3GcoTbDD6dF4ME5KXgazJJur6vmreuXMosa1KlUMtnRKbrX4plDZR8FMLJyKzv/5et5mGtXgMPPKpb7BiA+rF58RAvCX00zkztSMAzQKH10bhe5nZDp3D8rMhQ8DHvyLi442w8oT5z7ymnpr0wHHLpRlrKIPyPFaWN7zDMBRb+0XTnejKwyHcR/e92+cn+2W15Vlqq8/drpAEqx7+c2VjDGtrFyKlIMHhHSlZo3ATaCIqIr0ZYC4oeE6qx9UOg30p2hZL9skTExoIQDu0zeYez6uaW73j8YAjDZ9iG/tmQtStCVb+tl4HxZFR7MCht1G4c1XoFmrGICK0HMsaPuSdnAknJf0bS6rdbwyedhL4LmF66t1QhkFlU
    CF_ZONE_API_TOKEN: AgAd5qQPgLYeALO298/UzZhBUCAsVBO/+cMsJS9f/E1RqJzukXP++9zzN6ASoHv1FOEjpcWFECH75xf0aTC7zEDjOjUma7e+UgfRhsUzyJsv3FGE9/Xo38lHv5gU1Pfl5D55PJ6oRcqO35Fiz9TGD5qCoYhVmF0JHnaRDC7nV46HvcekWZzpRKfc3PzgHXsPn1QKN1SfZwNFGIlimFt72MLu4qcTJezSABq/IbpwDYl473CHpIFVgN8XJhnpgt40I9xXsn+rQ93rIN4XWE2iIgT4APMlegOPIg15aYzOqi7fIy3h6cR/6mzMZaSXryL07OdIf2NaC/4pXm4EpDKbp3JKCGsSoRUTbN7aAjDVj1T0qOa5RydmCZojk5NVNTaA9zxWL94kH1723k82SkHt3mb+BN0G/lC6dKZtncKMBnqld+++yZ98+uCAHakSxrhSOX0GTYtuc48juz3eSoPCkdqsxEW/Wst7wP3FQb/eH2diF2ZdT5S2Aif1DeVOkgC81wmEa9PwIZHEPFKaEr6iXuj7LzxL24esSWupBgfFUSU3/rXHeRrTQoLuz8rW/PXyT9W/AeL7pdzNIITO0/h27xJiP7/UubWkyAvRhSww9qAbGd8co5yyahraRuKkVW5kyJu6okQR5mYNMb/u5AIEKma8iE4DpU+xu2L2VXaDA/kgD8KYLLVgwUrtL1BVixpSKLniyRodY9tTrJ8KXeSehZ9TTR04cvv+HMvU4w4KUr+YfkB1f94XQg8Z
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: network-system
