---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: network-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgDByQmJuiSoPknBfFS0Wu4Ik5VwD4oY+/fmf1fuf8d0G7LNN0YQFL2Ss4pBMd/41EH5hLfOuiXQWRA4bJJf2cjLbpuoz3zGbzTbqj5VmMD297hodc1KSof66/p9/4JoPJTtRRoPjgff0bf0NUCt/Tgq+12lRhiAwTN6vPdVcytQkfb4cfNmGC19089E/4igYcAHqBlojwyGbNCSlmYyCHg9uWED5o+qUMGkfJbjU5tYspbhxR8TMu7LjjnisZZaG9e40UGHPSuF1g3vOGV3i0/+ACZpt/nqHzOFiy6MjbA2yubKTwVaN8BQwO0p+o1Fox3KIUJOZthgNsTxVNEiRi3NLmCFA/cANFl8u8hkTp3NYFazGKbaW+teYOLjprQTMP8bisLPZmFkDiuNZ949g0yIK2PXb+0ZSYcw6VxMAPCVboDqf4cQzfg9sR74vJrKwYRZbUPGhenSeUAvzjiAA5uZLxJDO7cnNKKtc1P9iCFxknolS/2vChAghrkXrT5lUKhXROHnEWTweRnYv69o9xLD1/aAYHl9zUmFm0inusyapAwi99B22ll07k8IH7ahODZUM+YDdOfF4cIHO+5W+hBJPTejb0bsrD9CKNOAYehTLYsV2pdBdby177PBSog1+03R4+0ngNQq2ilZMUgIKRdlJpsZ1ANzD23X4glm34Or1qU//9oV5os92tdD1YkhMHFxGbFxAXEXFjCxA0TTmpHgptK0uTeYWacOWAaMi4+tH7fCr4FkCwh+
    CF_ZONE_API_TOKEN: AgB64Ikv2V5wcn1/O2wwpoZt3NHzH/QXZzzA/IG7JQjuN05t8s5jHLjqZkNU6m1biGTqE8roeoI9vgWxUAjVK9DpwK4Zh6JioTKIk9u+tmfozHQyJbkHzrHEL2qiIX4lHHNefZrOsluAcHDhN9pnX66d6TnbU0vKBOFDRxv8yjeMrMGZyKDQWw81zRm/R3PnSlxjzJSD0pYfN4LTtYTDjhDJ+EQR7bvApP+8HoSC04OUW9OVJQc8r6t39e0GkWG5N/rtsigXUKihBZsdHTaYUrNpZxPJlMLRxehfZMeqViKxv+1ILZtTfKIQvmMl5Gl2GBokxrerBmnieeNUqurxYSYMCyaEquE/ltUCDpBF6oTB5fxoFszuSOMujVmOCP3WRSUd3sZ+pbS3YfJL3F0R+Lo3/fNsPAci7wXN776opHEeY2PJkS/IkS9x7jY9sSVceuBx6jp8wjitQn+8Em8KyV3RatdKwKVtnS/dEPLudLVzrt9R0sidQwY6ddVVMQlMTJ85SdEU39VxwbptnlMb8QdD3/6ZfAqZcaGAm2bERJjcn+BaY02mNSYJVUod6Rx6Mcn40Wu8DNqxTQC7/Fm3iZa6XbdryQwCfUKw3miB1d9Ef14dUnbJEUPPUGwzMjCqfyftuIX46yCsbXLCH2n7lTjw3IqESD8ixAIC6+YIMlfrsmJRD/FEalj+/LAJLcm++3EN9vUfzG924zgkTP7GKFRIcFUb19Yzu6R4L5VLsaD+XT1aBwZXzWAI
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: network-system
