---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: network-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgBhQY0wbgnMTgHdXKOKVOm+8htD5D0jtLbyeTWzqPxBlj++QUDYJdoGi2oOCgYN3yH1P/NY0nlosRF7O4OBVvW5sk6G1QfV1dbSPn0cBV8sWu3RtPyLcOhH7PdB/3AC2dvWyP0qnKstxprtz+5vZNZr/XyYGr567RZQMIQ7O2n0hqZxNbUGusDB7k0/fKMzWQ+LoGWvdBGJB3cVYGdzLHtQzw/pEQ1MXDa2/h2o9/zVIKSniRJ5b0QpeJELiZrRWDAWxfUIdVXE3+Iy9np8P8qOXNhK3lwWrgPGU05wrHxsYTV4Jxv52ZmWUdvtHAs+L7mtmDJjiTnKXuoPwyV/bxgM4eO/ejLMMTrqcjMrZgkaxfXlMEXVMzT/UvGxd0uVTUEHYQ129qRMw47u4cf42sujkeN6UTSbEcnSf8yn/PJL0u1wx0VrVJbBUWEbZ80cNTiazbyQ3eszTURf2gXvSVb847TupV9e2uJ+lOvCpferxUnZwzwrr+oeKdAgX2R4/q9vj8BbzF+pUrzQf/cSaiHr0J42FL97nKqGJZgLEGh4L6mUQ5RQFuiph/yVyYmZ4rkgpdQZxiMyhjiLekfTeNbEs5yjPI6GQKEyNZDhvfAJA2D/l2wi9kK080dTet0RKU+F4eEtxr4Y1qDt06DxC203vgghNPa4aA6+JeMNDxHGV0/STbfVhwg1b6dKMKCfSncuc42IAtfT88y7auQjDbjk44EE38YBpUX0pyBt316WY1x61LvN/H0K
    CF_ZONE_API_TOKEN: AgBKOMRLO4X+OnbNiwweLx5PK/ArDae8iZx8+h3YoF0UWiNjP8rix2jfc7aD1cJQKLXkYnVWL3txWL0Z6jBG2rX4y9af0g+03kyyZJioV2C3t71/aCjXhLQvYXc8PzxOfSz6erxw3F8wN7ehaH6omoC7IWEc3Cmf5XQevyhFOrjM0z4RjrcydOwpInTENNOMhfzoGO1vsSeyPQrpe2jD6zMQQlXndk1C/swYd9cTC1fhIKYIVUNCw8BJXuePtPGVh39gfjNVURpvN0/RuT6fCpypgKe8ik3pJG8zfIhbBpmXOndXqPe/6uEcvY+e0SESz7NLejB1CjkIlmW5FpCzz/+XXwTxXSvTyt9Hb9yEeVMXo3rsihKtTl7hCOYuTPlHYxPsaI1bYTiYLgnNT5Pwh+FTCJ77qUIMvZLaSPKvLX6Nqtx1+2T1orOm9ax2gJ1djaNpy2uXvs1/5HPfVDvFZP7Zn4K4geWufK9Ue5o2a1j1vN5FnYE6UXFZzTgZM0TElDsDUFCVgBU85lMaKw0WGDbIjm3TxT+dX05Bm2uuQS/cHl0Ft1ohMJ0T8N9vzwFC6AkZnpo2UdOAkIyLqTyzCBSEq4xfX6CdDV44HwSbDowDO1aYK5I+LE7KY6qSbyO35EFz3EV9MyiGusX2FvVJDqkQmfPGfUEVaPsWZuRgfplQlFHnpdqjO0BtOk41vOlueM9gy51S+ha6PLtk2taxDd96pN25fKAz7x77ZauIuoG9c9lkBghl3ovV
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: network-system
