---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: network-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgB6OHMKRmfS1Q5M39BBxHWGbR7PgM7YwtyogGyCUkPm5xdWRAdN4fgVYncfaUV8GB373sxqQzi2B93nsPVQX5hfHmb7zmLljGHHTSc0U6UFRtKH+Xscsj8Ub7H+eiOvLxg6+yI2JNy1KYRqlI8qdf61X16MhKfDvOzQaH9MTvm3gSscx8toZ4HSzSVMhZgRnPRdhKBD3sUbqaSUPpj0wnSNG7FrG/cUragvVY/30FpqYeQjJ+VRJDk6MMdq+QTZC10LNEnCrua2IZAKEoFx8WuY7W1Eo5wHUmOf0lY04cW3WEEQKpdPZzngNst1+H9AoUy5T3DzuTQEvJx3q5jKv2eEg7TIAimEX+Xqcd4+VNR4FYVF2YPvF+k9CONrBBqpo+l56J2nXPnXNWnYv21hIDRRiTkjRHRi12B54siPqUz1BW37vlLRMbkXBF9Lo6IqOncH52mAGaXwyJfe00d4Hr5vhPplZX9006EyoNAgJgQHQCboHOgUMf3j2J/6zReaYuYtV2f4iB2zY3mw3SCeSgFBiH0Rum/XdMk4bo48P0qo5rPsMARGdeFTz4yMQSyp3hWVhQtEHNg/hcWFR2vnsTTceYONDdxD62t2R4okdvFGVAaozp690HvXDaRSWNpAEQGHUXxK344JoFUAtJGmuSGepFTVhPIASVMsIqULzjzSdv0vFGlqUSNRcszG6c7bYthZVvX0JRuDKssD0YHPUMAPCIu2oht+nWwXyjU9ALtKheKtcdSot+4M
    CF_ZONE_API_TOKEN: AgABnrowuymHG1YD1kPIVQPyLzpUrWEqQcXWSMhhruQ1IJE33sdvgfkJyYOmmyhJXODbxkuo6q8iRinz2NE4j8fpzLYghmINoemCgOxf2f8z5cvvWHzmRAPjcGuoPtECA+IpM4lkVdt1wTQm5JMh7fRtLkP5NVuPLrutt5MgJWl84tXaELULkMbf2JejlyrD0MntbbEO3+XwVYbjjKeYhYwtfpPEWQhgvkBFL9VA1yTHbhsKznqS6K7p7EDF9zxo8cUbaiboXRVaKkw5Wr9+r07Mq8oIzbW4MaV2vccdbmO7K1ZhSiTJz3Vt1pCNScolZ7zyX2AWIY8olY0lcWuFPnPUVB6v1pzxlPbH74sAIifOBFAp8bw/07sCQMkzi/QLtCOStaDQ09R4OW84zyNF87izCOj7wrrZUVZQkHmQzys4dZTFo33DdL4rp+OuEoehTWNryyMDTQxvuS+15zlUlciyTtN5F/zlZ6nXrmzKFQIfUkOKxy9h8HuAEhqJpVDcVOh2Xsug/WoS+yKubt1IEjC+h1RTHyL6qJdeOPb8iPzsPuyVfOViCAiLWwDOeDe0IyCOFDJdPXUZwHegOUYbCvViW9M27qa10WmpDwlvwsuSYPc78yRImWg+0L+uNwl4MT4UQ2wJNX/TuMRofxL8ADRNO8+HDTMVokqVFcGnpLWWkgxQCOW19UPemFmYN9kGRXoTyRCGZiQIUIfWLJFZDlUeHXPGYqoUtoy+MvZyrxMVDLrtKPFU6Nck
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: network-system
