---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: network-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgAUpGAvsHqm8ZXNXda23czstlSYSStpE02+yRVAvroZfNxqRVFbp6DkKjPVKOTewz4U8oG3R9XKfOppRyxmv7S6aFCqDOOFzREhbuUtEZQSVH799P8iuxXk5XC/usk/Uhj3OwqLBGvijr1ofdUurTAA4vR0Ryr/jwWX0E5b0iG7W133WSK3yFlm1KnTAWt2CGeXxAvOPdfj2w1Uz4E0KJs+2Amge/yPOJpMQ6a/Pl/VrRAdkxK5D6qSpN3Wqa1JWne0nSQT7onyl9RsSZKrJzNv8mGXkBOpboh/ZVIu5remh21qynq+3By8ry0NT7nUTw4Ngw+lKHe0qtkDt9/aVd5ekXK6TCxG3DMfrzAbJOqo/89g6xgIyAXAZQEo8y8giUOPwRmys/isFRoJNg+eBOuytjzUMR+fYZazW2p8vqiFp+DJNHhTfbMTpVD83Nm+zFzWCiCDKwtvQpYtIxwHK1DAlmKBfk90sugUApdCX69eYgX5Wb4cgpMVsGug7x6nHwGGFVhWb7ara/KU/4WloqOSHh+JpvNX+EnsB8Bvv6WZFPVAftsuT/Sw9yA5yhnwbxUvRw7lkOr0F+VgZW8rBMCsb68a58G9xbqG6i9u/0gRlJmkMZgUtq9YYVD8UPPBHK9E9hN64FjXRAvK9QM03DPsL3yJqGCmsQoYcTE4CRAY+7Ku8adiEI0EVR3zeeUV5SuhZePCKLISLDPbEZw3diow+Vp4y995AkreEhiNPie55jq5x9gAw1fq
    CF_ZONE_API_TOKEN: AgAu4gGCHindmuctFHvzpmWP0iUqr4uH6Arfa8R03kp7QXCRGtH6ZNAa3c0WBZ1Yuu0OeqkYtFdU2ZQLUyaZwkAVAvEDDH/ZKWUcqKHVxn3cEUrEONNijiM4kcdOIcVJbuHtEUbilGNLrelrNaJUwTdNDovFVOQlOZcaE78vE0JIKg4/GYxgESq0/5sAggIpTiuL3D4K90OZCJax1+NLlXt50bc5o0+xUJaqC1iyBiGtP8R7QsuBb3VUWDCp5uNs9GAh0KnP0PdNl4+TASYMwmF+wwCu+4UotnsZSbh6gi+JmIJAHiUcStpj/2gbSwsyqf39ZCMvOHtmMrzcnmlMGrMM+NZy2Ckx4J5mgcfLHxVFxNHVh2Gu0gIGS627xABP4d/LBC7nYUkYGq22w+/5b453sGOJkXQbGKR5t9t/hWWFBKF2zAXYQvySpeackh0B4D30neM1zO+jYHIB+ix8DpXZkN0Wr+7AmR8308/UC5nMfvrOW+vXE6EEvPKVa1o/wUkWOUgus2G0JO1uvaUaYtiwys+upZ2VGPAUhKkbdc1zvBYqMBeAFIv2RG9TSqXow7WMTHxqw8C0gOqRdEtIaWdOFDDKt63gpfhzKJV01Pw6LnTD+uAEIPXAa8cs/NSNG6slpoM2ouZUffYlaWRK4Z5DF6NirWDY9U4a9BGGhCNs6G8z/nRP7ZH7TBgcDO6EoX4Xi77oeXtDx6H58hrf5s6AHtnTOzV0pnCgM/3WG22K8QiVkMN8IYAY
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: network-system
