---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: network-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgCvXmoJewTY/SILsw7g96MgQ47eAra736yEf1fNjS1U3Mcv5CA0KPyyTj8IdK+wu0rPLefs6F48nj7FDruC6s/2QX9p/F9ANp70zF+HSARpQHEvX63p7DCLunO+i6tNXRvZFPOXnI60PIo7N+Xwt9rva4fqNTlxCtuwWA7sryrGm1gBDMSVhR/tgNFWPQ1BEd0/emnWDE4oWkK7lMAdbc+RyzYOG8NYTyUHSua+T2/x439qKbJvkXnRX6PjSi/K7MN/sUy8M2TZ12Z+5DEHUSJhSKA7ST8aut755qXxPUmPMwgpxeU9uXs6D+35ujtaojpY/NZAUEfCgEt7iAjvClUz+COpIzYNOE+bi2mpNARuWOl5YAAw9+28AdL6qWf5RNm9IpnM+zPMRl9nzYaI7vurafTNURbCC5UferWFToTc7ZARao09FCk2yy7I1gLRCCrIgMBN0HWULaUWN1keUxQJ3oW9ngJ8QQmrA7l4sUwbwq70nj5d8ky5Xc0Izo0HoIPd1yegTFqP+WUg0XVPJg4FbE6WFNJgi+IScXGOsXG0v0CWKQnfLJHQgMdPSHPqEHeJqgSapEMb7qPo3TBlQwkGCMlqk/3r3uTDAJLuw5vbCqLjlO0ufa3iDQmEZ58GCLzVXd/SktEpjGNLq2wbNBUon1g2U083KBHXYCQKRmz8EZnZU7e21as2bwDrZtj3QSpe1CBXaO6UEkBWsALkkFBTpthu2SJzBZLKn+Et16MOx0gTBS3JiIoM
    CF_ZONE_API_TOKEN: AgCUlj+RRiAoGb/msGqJLXUEwAShyr/tUsbCziIAL2dy/qNztZPdkOB83JRd1Nvf3vD8K7+Gpe90RO945oLoPL5A4e6piFpSrUSgFHMCKglssU47iA5CvP0RCE4gbt/0XVNPJqRJ5Zt+ooDyt6xu77oulevQu9kB6A9S8YnEX3TXqIpd7Ciyve6A007TeDS2FKjZwGqsgB2wuKG6vNad/e6737fXI5GddWb340NjJslj0huuwolZvrBmTxIQ77LLKWJqSnqmgYnWmQwspfnej8h5alImkBPJ8Mx4KHpCgW4cLBxX86V+RoVv5AAxdalpLPDg6rnzhsdz/bakWWtQwkMqLmn45UQ/8SQjrdKP39/P3yRRvavceyAjuvIriDQ6FBAuOC5/Gg8fo3Z2LUm4LV+y7kzPlKSnAyAAU4zjPIcllcntKnV/brVGCSieBAhtTzLyVUvfy0i3TkPFTcQuMJXZ1Yn9Abt/6H2dBiYjtLN69Bg8Q6fnKTOY/m8XduWp5DsqEjcWsyV0JInlJ7qvM1XKEsI0Y1T+P1wZdVa7U596wZrsAWy+GRqzegEX1MFKOFolr5DgGeMnuL4l8kkQFvoHuEU/tXCalUPM+J7F9b3OU76uIEtKtf067J3WCg46OpPQXkpSV0DFvY1+w0Ayf1w+ZiY0Rc0lAqaq/rZx9CNsjgHe7c9I6ufmdO62ywlogQIuzRKVG5Kiqs08PF8POuAUY2Ji4cfBlgYIr635HfhNXhz/6dDKbzLM
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: network-system
