---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: network-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgCQ0SqaG8xLO+O6uY0jPP9RR9MTwRovtOehMR60XioLA58TRYSIl/m11Ycil80BmBhnjHujG7KEX8ER3j9cSU6s/FjzKtmQqqHtsExD2kHeiSOk4yeMkqzPqvJfUeXXJYqOPgKEMv0ZhydjAq9ewK8EyLEJtOHNFROge5/WMULx6G6oNoVHFbsV1cViSfPjWQSqDYU8+yDZ0NUqQ2Zns4whSj78re+8Bd/e+cm2eTs/Bcts4zCbeWAX9LB3AvZKR8WPwXtbektkFXMitZ46Y1NIZL1lGd3001Vhii1iGfGwYOS/rp+fFAw2OOvaX0UZhW2jenutdKyQYV3REVbSjhWuz989onkjS0XNIglb4pqEJDISAIPepX7bBQdhE1FJyJc/BpvLOBjU9Gg3LbH1rAQzPX/m07s+OTO/lIGM4udtApSAoqz5+fsSET34BBOX9E0W9Y8Rm4q3vZqGg62CBvTQDzZ4qlRP2I3fkUaeOGxWCjGZRzujNZXlSI0mUBlcXoO/f+BiYc8ayUOaMVqlvl/YK710xrqOPqO5quwrSje+b57Zsn9saxNpRg+1hHHjv69YbdN4h9aPLUDFpWOmjGjwl3+2jPCZUv89ROnFe6YVDZ7q6WvL8ora8TwaJHzEaueLx5ttt8QxcO9fRTH95xigAyLCKyIMpXYWXEJqFyOaoBYbKftDJ4eHyoEvUQvsuir0AUxJIxULGoTF0/d3CpO9rZ6fT3cT6fkuClO7bY8qQ/jeYUreozEM
    CF_ZONE_API_TOKEN: AgAhG//mpd1d/VbSyebP+jlHzwPi/Dn3Ww3w+Ctq+AdhDWJGB6BRNBx9Zeoq2LG/ELcnvfdPCLvemNQRoS7N+1BjEFLZzqtY9GP2DhUnposCistpIHoCjpClH1Z86jswEIGJQ83cjQzFQJHQImU1K9hhsdGU36MjggKTIv4BXozlGbxWRc2s/k6aeVnIbJbZDZRSIaHyC+4mWynRwolg3d0Ynl54NjSfZ0GyrM4yuzjVbdYBSc5m6wJRI7Ghdtwagv9JX5nEPKtNJYL7MeXMSaJElkw/LjA1OCMUgDuUpBLQ/aV1yR+zE/tztUK2ijUZ0KtKyk6wDlWa+Gsl3inYldxaCRm+ia7uXX4cph7A1VblK7xqlhiQ8FjJyB7Ln0SWBuof2thWbL3iWhqHNx7aAVAscWWxXY1Cr8efIQpwNhZI9beuzDrstjLRMscjL+Fv3pvG4JSFB3XCZED14z1dQNsqpyaClNHq5/GloOXPDvMtFQvD3cngjIRKA+/y9L3FyZavh1E6/O2g5ZBpdg5E2RD4pi6LMjiBute1hUHSQUT0r13g/2THPeHbfpDjSdCHMglA/QhyjSTp8SFsTWrwYCIjhjjM1JK8hyFiURy5sI8tc1VpwejUx1V3Y7jgi2IDLZZa0wXXvsI5pPzTBHtm3mjvu7Iv2oRjQBEm3n2Nix/8e8uzsTH2UxMBFYRl9Buld0nt8rlOjjaF0kpKcEcdg9zj8LKyFRaOOFegFdlgh2ElTvs0loOcgfEw
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: network-system
