---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: network-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgC1+6OIncYJN93hHemJyAxlhFK+cbtfjfd6tOaX/HWq21YE5L16b3O+UJkhrt8ik3M1WBZ5jroabRHgPvwX+nJ+sLrZ81ZeJZn3qTmf0q5F6co17VjjMVSCOo28ym8ubIWiD2XaX2zTBPLknAm3Pjg2u46NZrnAivcfjQhcjC4Vbj22mBlpuzxbfR3lGwRnkX5RIOPaqGl2iX/cb6pd0w4dwZqR0HlYUn2FDC0zKz70VQADiX8g/EeeIttOrFYc25KDVR4G4Y0gCCqLVZ2583S9jTnKrNomnkm2BAFD8FWRYUj6sA9EowyeW20VUTXHzpGfqihhfLJKKlxjIr8vNT1Sol/maBJNoFTEfoaXcBYT5/KMdyhSFgkRUYinq9sTdMkCm7mz66LRr0U/1PHrwVN8BFRJivQhFClcMAjPd2wjs+wJ2ata72+u5WlJBsWW+1xLcfkcvP+lKeunoHr7QL6m+T1APSzBtQ/lyL27Siv70cLsjbh7Ql2mBuiK9GoRJA1W/qXqAtNY0rg3MeAN5p9RbtdDnRkeypZaqXRR3KzEOZanijT9ZCr8pbnHwvMiD6TZQLXB8MHhb7GVw4MsKL/+yT9QEst+RlfDm7GVCRJ4xQlRJsmV4Qh3HRojpe+fuxQ2wmdIIvm6X3UWnzDCIV+tr3gXLdbCKiVgDHADKl75AYsJvpFUlsXGw6LaCeIy/lRtB3LqBd0awlK8Ar86rgYLio8ibmkYbot1BfyKrwna+WcMHb632kpq
    CF_ZONE_API_TOKEN: AgARRZ8dD79IrGLOfbNhhzeM4DV0PJ6s3iBKKeTeJZMDyY/ew/3Q9W/hnnr2mi9bbvKx2cAnjYm6932aH30TbkXsu+J32bOWkiQrrIPyhixg/FGqUlsx1olraplh+GF/dAuiE8sY0H7BztYs8p5d+9SbtwIYYoQysbTratwdj2DqjWZs5fuzkRx+nFr0tBSDVvbTtPRkRufPTMN4VJFLDa73GrlJlR4jgduWcgt9GiaIWe5Pb/IvtgvIADFRXaoS68uNjbDMc/hBTm7hd+rBaQkpUhggJUh0sJul4u9t9toTpEpmSRtw/W7WaNLFoTRMEJRiIQlV9tgIwfOEz9AExu0A/in9HXtfWsRAiyc/3anGVh0DqBxyzTJEgcocWT7i3CFVFjaOz0PFDAwovWL81b84V9QghOQ4fSgjq6BGbQmOoSXdrVjpwE/XFCjly+D8FSI1aE8vrjadFzK+Qmfgp1rZgtKR9/Bx97VM2VxL/dfzXMlDkTt6PAhgfrwD/4oD9tzwcCQUalY5osCFBhcKdXlxOK1Lrd7MYj37qD3qy9Ts6Tq5XeB1qt2gMu0yHe9wjgg96VS+3WZpaE1O39Xg2OI1VIVa0a2BcebeXdNOaTcLCidG+gJkDOBZIVR3Hx1iTAhzijI/l0PpdEx27sWdrUD3UHlwLsqNh6xlA9Ql6ezc3PL5YP5TpvPHydgLt/3l/IIkOxc2XD60OOPp3hl04bvURljPByukA67GoAn8A0rw7YOyHXUtZfru
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: network-system
