---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: network-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgB2+ZL5SQ3knOcrAncjH24v6z6L9vULky8bq0VG+F2GLxk7T1y9/h17qPPsZ24yqcIGlo/Z98PAd9IMzhiesh+MJoUVTMoiruhmyDowzyGXXeKBRo0Qzvjh4LDkoeJhrscgh6eeXEbvCCFBA9bVZRHXlzd6Xrg7JC5zEepK1PpctvoA0zxN1TYlqwLfBMM/ukTBn5aAHGMQeB0u6A76Fb4Vns9rkdyTAkQ92pqHsl8UX4mrteBUOPH6nS8ewn9NSBixN9r3CbglAMDt4IKIxeiRHSPYWasP6WX0vssOUttnaSu0tennIVMszRXqoUDSTll3hjGVAYCk2DDtWXb+roCdX3pU3JW7fsGYcfH1t9zWQ/4WxJ/DIqvHL6qrLC1q9v1eFuEPluj0vpPizLmYaKKnfnrU9oVWjF3chzKdk+IOw25wfSEkj4+JQhSci3uWTM/+BAfRF76JqHmvm1wdpr7iv0Lh0VaP21TEr9em4RU/8DjY+8NT49qbfAcqVTfea8JdT9u/pA0Ln0g/9F2eUXPZYnotJJjuTUyjS0G1DpRHphM3mZurSvAe746B1AMRbcDzvvWylEivAtTC1+Z6gK/DAq/UyEZBnRjL5n3rhnZRtqI9VjGuIUVpNlLN2KGr4RNJuzWfMGZSIXTTUSqZ8WZqfdQyHOhsSJaaV5Y2oaiideuy+6KOc/BULZ1bQRCz3jpz7FG8uQBZ1/wG6bJ5khS9V3VhiuHm4TMJAZJfU+dao8pq2WsO8hc9
    CF_ZONE_API_TOKEN: AgBHse8oSH7JPltSCc4V+awAyeLlKnE4To/6Z4npZGOAkK+bgljyszNRtZUm638YsGN7zoWZFG3FMSpyVPcB+gHICLmW+Ky2Yr53whz9R9s3p+MJi9x3wY2RfA4IFvwhqCCGYmOUqHNZnHhwQzs0KdyeI7XoxgTjmYlxhJfwqfpFzEyydrhLi4vH1j8dSRNueMHGPyLSLWg6KGPWzWJxlUavPzpGv6PiFYBkxiKIC+D50t/bv2n/esz0NiTsycMDb7x/2+UlAbC/OU0QNedvqjPCAQ1J7iilOxB8+uITt5n9ZL2obTOHf2se1uw+vYWz6ZI6wEE0fZTxFD0ACvXFgqE4IlyNK1QYugeWLW1QdDFqglO6b46Fg5q61JEaEw5UaJE+7FNxgSIBpqHC2OTYK45NjtmC69VrYYQil6cSipvUCjE8IeTFCzMmIb2Da0eisZYZuLjywEz3tKYhI1KxaJYJkhQmTY2ZDUI0tB+YNKCeCB3wyRMTl5H0i8QSqtItdEULXv9HXEs96vjWy88VG1aNG55Xwo1vAbMHGE0XL02AGbY325vYReaoqg/yt6sLJwbAPkC1VhGBfkyp0CLau8/f3d5WVD1X8IABx5NNihfN/jJXcrm3kJxfOvNwTYnpXKqM4PciaSnSGSW/Dxtgv2CyrOxgFvkYPTH2Fr2AmeCNaUvEEzlHSBVUFenq2vaA8xB6iZlraQe1VmZOosl9oYfOHxdznbCyfkseKnBK3Imeme4G5VTRHmU3
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: network-system
