---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: network-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgCck5uENkHwH2OInD/Wyzq2OUZOmxVAEjsYjtzTeyhHGD4yAbNP5apSysSAMgcCnUMn4iEpc1HMtDrgRgIZxeayKZmnH/ncHA0EPOifr6SfAgNYEk/5m8/YcF8nmQF9hKNUqE3XAD19KedgLxWpC1mlf98a5X4I9q2Ybi+jkWqq+Ay/gX8cDhI0uAOSlzhNt+8MMXeC7HxjLxDFSEb2N7frWGiR5CmUo6kYAPRIRDzH8NfeLZfiJ5+K59GMoEURV9klnQPjllyNpFN1MhV7g0i9JuGBWCEEePJLU+E24Q+7D01ZTvVzQpBim/j9bhO3u+U14zAL5wqG9fgNNQw8hywk7+Ebbqzby0wLLiFdsdEv2R1NKR+LQq+U+tx2XHxIFjO9UWUnMHhpllzi6tSxnS7hzapF8mTJeLHPxrJjH0aGJ504t7uV+FzimeijIkplo6pHaCUB9kA+q4T8kb+UuEt+OVPqomGwiuf8vRBzhkUSg4DjLHmF8U4rtPPWadG7Hca5gTU2D+u9FPNa6Xy2qSLfkcX2GNWHDhK4WoR/Ec8xI2NBg3czyJz5PgsHKZu7V8DOTTIjPlf4rq5U7wUf6opqm3YRp+7GC5CgVCcU6pWsuY1uZFjgnzcrMZm/aYSKuCmwzjO3pLENJrZcyYNopC6yYP31IB+H6DE4ts5mObH9q0hF+IuxP/dwbo9eW3Wk5kHZ2s7snUeulpXaXiOje68bXimIngq0pf3++NuYydHQQD0ALUDpTqaU
    CF_ZONE_API_TOKEN: AgCBXyNabHOMhB3EYStpnIASBTWse18q2I4dlybJ3rZWNOKbLx55j+aDK/4SScb5RyYJHJ4ZDFmM9XH9m40zWojmNbDfDDMp0sN3RZeWjVgZ5bJEm6XceJCjT4FcYMZp9BpEMa/OdiOnhfyQZGuJZdIcasvfUfIP+SOXOzCDdClC70I4EegqmR7w8/GdipCLjkhHvx8IdY6GeIuxhrQu/M9M5jWC1VMbJpBTQbuoCOdrr5nKCKIhC+6ykf5aoWtJmNhKJkyNWxKOj5dLej1DnbFb/XnfFmHValuEwcYPgbUYS77PG8yivRkrUkDesOOAefTkEBDyqN0yyUK6rkBu6adVPC6NEhFDBq32/8VToRxChQwT1DES9X1MPxTL1YrcOvwAnsz5w3ndxlUHSW9Yf8o0jzzZWl0ZEn3whmpcux77y9PWZkP42j6bzccJAE1EnM5THOp3o0MwiDGJPb+x9To3WyA1Q4qFv4sQa/ZjFeVAbXuj2xFmYOKNIIp+Iaqjd/LDih5KzMWeYXXOghRw0lpOOCK6vgg1XM7G2nP2gD+BYRQYbUiaAsGuIIRkmD81tV4ptv2dPkzRIc0PjFsi28gagVdP4w5jDiRGB1X+zj9UXxrTn5QeOumS+jFMlZbyhRouwYLYGFGXYPpmhHpmqb63qzd6G0UZP33Tw01fyX4B2eMF//QAq0WhcjUOFHS4lsPnN5VtB5iwiUD8czn4fO7IP0s6deeTSIYoM+gqoRXiL3dp84XV6Yn9
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: network-system
