---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: network-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgBfzShGaIIZRaN5SIyD8RJDNkZsRvd35XkAR2dfqOPuF2sBtTdv5Rgj5i5dDq76x+kl2NjGrDaN3oawM+NUK0jyyvaAnlN+4UcJhu8Tw/PG7fwWx7fuaxtxiax6PmyLUB+AwjVA4M+ASVZooCAJlmhlm7NtuRphG9w2D4EFlYZtGTbdddLT4u6JvfvOaknZ5WI2i1fUyXExDBFe6I9gLcblYCoEfZjHO95bG/ZA3G3rbZW/F3Z+KAmCCnNn8AGYuG4M5aEDNhYE5awrHVH1FKvVdz8EdNmgqmz8+XYmPzw+xfuzXHNflzwfAd4/tskMaYPM1cMugRgANFyRW/uzYzyfW/0JhDOd1gRyf8M5ZWBO1CgCem5P37wmmbN8N6amby1cEzCR2oneMrfwlul8iM84e1AtnXxqhv4rZosrNH1KoolvfjbcClss7Qe3yPG5Nx1NbE+Rfu/Blnl26MZ8+Jhfi2vzBoM9DAuSMsdeX4+SmoKYBGnZJIdnCLZqSpxzLLPk0+T4j+nJUsgCP6MaoqmIdNZsQgK80K2JPYhcZDWVA1vo9Nl+hW3J5iQ5B5G4EvoSL6AFY51w5xc7XgNwz8Q+aYYUhO+XAGoNZy+5+CDcMuB0ykLBNEXlHSlhD1xMRnOJA5woRbEm5vL8RCtH+KB9zs1kJvq+MHInOegj2ejPDCRzluWflbQF13VpZDVeKNhenveby/WooEoizdybuT8DNCoFyOP/B5HVU6m1frFwHFOB5cHAHv+R
    CF_ZONE_API_TOKEN: AgBlJ5+WzwDdVqsxwYcwOIKZtUKJfQMcjfCQDh1dzVEnZQc3RmsbnwdPxBMkpsUsMA/XoQyd634eOMhXsopRxlO3QrbvXnO0C8jN9F/mr8T8ytppwmXY1DVAA9Gzp2lT3PPhRJjX6dE7nls0Ze17yFhkQv8cUamvu8+4Dr826g55TWqY9U66sq1D/wnUvbcZqUKAOhn+WxMrvqqTTCYewy9d3AMuArLwUG3U0Eija1edvM9ASw3555lb8NxRWOTH6Wj1bkuh+LRwlMr1eHdXms2R0E/p1GO/EP5wgZmYkLzfnGzlxXWXw8RQ2WrGlYbTNKoQ/2ZJS1zVCVA3qMmlnjf0vAd6JSpbSsxjE9M0hfMB2sVyT1C9o0SgXfITWJSq/naI4lRta+Blcmj+ubp8sFmW+mCGb/O9IhQmouBVxiiX/9VB3CMtJyL7r08e1XZAK/0ofi/vFpr0L7H8IXj1PqJX1Di1DwIyPXt5KG32/0N56pFyMhVm0MwZIlRNfzzDDgopCpagRPjDUKLdLYuxJuWBVCt2F4IaeiXWdDVX241tmlMUI24TjoYHAn4ylgvjmCu2kkTNAmv7Tx8vk+6CuecytN4VGfHRyLfzrRz/eA0sM0jWZQAK8dbxPx/Ig2zqoB3ZxFSCAXAQoz/Sz8+tg1A4ZnOs7lpOL7yZfMTfOAD7fxkGY9TVY8MPiqYG+tjKsT0HqgPBoKFirxwuvkCFGurynIeeV1SC6OgVZP8g8DL3AyoPxX4NVf6f
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: network-system
