---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: default
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgCYywu4RPpiemW2UzaDctuRXV4ni2e5TpZ5ZXUy0eF342rKvKX52SL/zU70FsxuMHLYAgQC+/hauqAln5YeXTvMhF9bdq2H0wxm2opEUnUdgJBe34iw/b7RKJZpn0FfaLIHSBgaDZUJHpY9RHkhCGFIMJDzad736BYVttelTbBtwB5QyNvee9mwWeW5Kcdly9vF1AVf1sd/l3pqtJGxDxl+xLSpvarxC/BfTy6WrAvCX3GAMg5rZYFukZ9M0bfbXwE3/CJx4CB+MdbmVQ+4NluF6CkOWNSP0EkGlPt4zh/Tv5ByNX9A077DFlKHoKocsmT38RV6RKcZZCeEr1vo1oVuGUWobahois5gVfBod/DCGzwGUL+ufipVxGFXiGCZdKhiShjsr/XxAoJk9+VHREO4r6nqcdeEup9rpCddIFpzKt7DXC944c/4Js+Jthu8xHzDmpf/VsenfwhJSI/zZMP0Vc9mvg+G3VIcrkqANd66aQ0VoOths08nVJB0yDqU/HHm6nFx2jDYEn0rAqp7lEGrhSPnzxeNJABcH4WtbRzhtb2c4mIuzbf4P86gHzanlmDNiybSbKRxEGS12ww4/8/Ar2UYMEW/6X3I21f8flerg/saNT2jf8ddipz9Xiz4gbiqosSBTY7o26WB+0Bt1BrH+p8j7GDqxBCOXYr5pc/BfKzEfO197M+VawYvVJvIEV14CtshiioKMwXIchQbTnI4+luC32Jr4BRApr97sq4i0mRmAWGGJq96
    CF_ZONE_API_TOKEN: AgC3uoevkNF6HWBSULoiZrcSULqhsiJYu9GwEIDpPyqtUIACJSX4u0QGqn4K3sRetwWwqf2EiJw/iBGwV9z+PTgxaGVhu9R/4YGvdveZOfTOor3haHqD/83cfQFrTjcC6F1OAPPWpK/9CLIf48jTEmuD2dpqfNtYgd50aJFP0yMEHAduRnIlMHWrpWTDhn/NZ1BoIFLOZraGQWqFs9x7lNy4tIFqQKwq8y5Mxn494GMGejdL1bjnBdKN3o5+a4AfTqdBwcAmujqN/KA6J0eDSCTO0AN+ncI/Y6Xan3zjHTUY1TEE0cPGWE0JSzcM+Gx3jNVZHPwcViuWBjbhP+GSt9MLIksV3Rj0QQJJX0whnDgGOIpejTny0VqkF/ZFZ1sVdchJzGTpOktgGn2G1q0UpMZAU2+RZB5iuyevnyXvPrFg2ywSzn1zYIcoH/3LWiZcNNMU2E61E/zUOJu2+cLE8SlWOJ1FQnY5HqKr4+Q87wWwNCJx1yRG3uZ3d6jfdnj/uDSZWIN6hyhgN/5G4CC8eJOYeV5dCCDUKwfo2U2UpT7S4PsQY50qzzZ7E3F4BwKWUPK5zxli7QE+lGBlcs1HobL99U2MJssed3S9Yq42G4UXOCSA5qTidlEkCFTeIrROoIC+OP8loQDqLmulmhsR4/JIehnbY65k4IluCWJRk9q8CP5v8Cm90MSMS+yk9FaSFHj6tyrVvhGGL4Qtq7rNClw8cVxiwoL+iFd56A5QAhATYCiHvC5qbpUJ
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: default
