---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: network-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgB8iiXaEt+q8L4aQx0fqzxXcC8P74/dTojyzABq1ATLCPbu2e7q++sxFuYwv1xCz78AUPtrMvjW5n+iM+w8dGaSkJpClTtAvzwZElw2h6dyO6OYcwPlSpKbtbuI5FvWr9f5u8xZUMn19lW1Q50XVt5mDIgHgETZ5JrSlBAW4Xs/VmaEt8pzXl2HERZz/Scqor5mz/N7C3/tgbDbJN92OuZ7ycv+z8X/nBXsaC9Vi+X3MlSdxXS04S3hn5K6tLp1gB0wsjCsqWzCHndY8d8Y/8nM9cNXKvZX3VxO8Ha4qWIb+/BNdhSO2PTVVYeGZQILZJ1Z/xIt14Hu2aBABUzJufkyycGzUvibQSpz9jXRIx3xo9fI6gMTHdhPRupVXXbHTsHnMi7pa6YBGshPbX7CijurBVdqsTBZmeZrZkGXQgvAZqxaljHmjJXzEqWOnO6aMhoZ9bHpMLvmRFYnhKUVwyXlF6yGVQSSs5T876axg7BZW0TX8MFnLpQgMy6K2FlI+6EgMTNGTOaMIGjaWCL3djZMTCOlbJ7+qP02+eAx3E/aj/oYY2CO+Zwt20CMkwZwlOIzSH40wPCNlpISRnlmB14mtNMcGSruxOG/r4q5jx05lSLRIWLYRmqtAL32Iqfs+kp6zX/PoQpvvuj1E8LdDZZVHx3R3qcu+Ayzp/nezeweKws/e/Zu4Nvy5b7V4AtzJCZbE5lFlcgLlfBE6TK63wIuHbuU2RkmwpnlNFSsz5kXKMpOV2giSSI+
    CF_ZONE_API_TOKEN: AgA1Jt9A5WD7dRPcXSL7fzF15q5KD3Vx/ypGPzRcZ1LqrAN5b8XAU8K0R6mph0Tgi1mHs1PVxaOqEY3ncF0iJ4hqEZjdqgeb15KtLcxthB0nIHETHYK0IcGF2zkD2rXqAsngL8D1nQ3+fTtgWQ5gXsMKeK4z81nmop8E1t5HHhzTYEN2ktznYHPknYXfsLWFUCGUrdGJClnC9Gwde9j6GGzH5M96L/qDqV3PfKoMO3bNlpYnVujY9qH9p/zA+wwtDaYtCYc+gSbPSe+H5bHqHEPwhA+8M+7SWHRRNXssqPUwo5g5veKFLnJCPUyAYGSSo8ykxYakHjqmD5DbkCLKRRlBT1c1ZVUySjF2mK1yJQE/m22WbWQKGgFJVNeOxY9PaA7/ECR9UHf3MaA+7HzMK47zfxl3MgZBZ7TYA69Z8l0f0nK4PgzPB0R4i6ijiPqkz6Kjhsq7Llp/pZOQelu7CiauHY5bHmLG8ioiIqykaGUI1/GeuOYAcgbwSMXjGc2T3LisIBvSoaACsz0dH2vRkDlMW0hFBVyaDAcCUbmgJlUk7GQL3WBWD46ag1geSEWN3wnBkFHMImi+i4eeltIfOcr89iLblNT5aPXlhiAhuy4JMwufV6VEUZhyM3HBp+LTQ8IZnx1Xp6z4CN1l92i1HxmZTFQgi2ypH1pJBW6gI6d5wlhMY1FiNooFjnT7mzybliuwu7WGyZrnWn6xAncQkZJGPWr65ZfVI6Y+/JwSTSq5GhLzGEjUIqDe
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: network-system
