---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: network-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgAM56MCQqF8aQ5Rtv04DVMqZBZBGdVjL582Chlco5OegBKe7/PSkT9Dzkuw0V2d3XphlggLPZocflZy+9q6/E9k9zTuxZDvwZwgzUGiQcnfkszRZ67oZIM42Cq4xTe+tdJnRi2s7fK4fk9+8VSVXjDAz9LqD8wxwHNbwJC3aKYnD5h3ZFiV1yvfWgyJzCavgNqGUNnKXCCMrD43oARpGbOg1mtap3/KvXosTBW8uK2lq2cxnsQdzNYv+zP8At5djQv/PsOyhF53ijodJv1ijv26Sa7KI8o0wVB1PA0AByDVCL8AxPg9lvsRqxM8YiGHZqIlqb9/9cRka7pRsmQR2I2MKmEYfGz+ktUsBYcPU8VAgT6O2ax/zhDY8pG2dyv75lZ+M7C91BGrp1HutB8gSiZy0Trj//n1oRMcer89KJObF/oVRa/fVeDGUBczXk4B0N5nIgkrhsvj5Vop4T/PZsiTfiNbzlG8rBSuAlYa9MuTHxBqLcjAA0FF/eaG+biSiRNrnjDU8QQIj7QTVzgh7d0A86dvto2qkbhk8ieymEaWSvGwusrUnLDlYqVVboc+QcAjGi2LbpmV/E8jkRuqsDVIpCtQfdOYN1Ma54eiCQbxQxy9DzJLkStKzn+tvBVJ5AIK2jazac0p78UatvJ8vkcf+Ieofxxomf1Cv1piYYwg3MZwMQzFOPyh3R6i7dC8eA5uJNj/hsfY53mpEsJ1UZBCTOKelKU7IsWrW9ZU+iLoNbB2o/fDn/Br
    CF_ZONE_API_TOKEN: AgCT2p6mhTDF2yW0BdBy/ZN3Zxnz1k6HotNqCqh/Qe0uRm7E7JiOjB3UXTCb/nc6kIZ5kRIkdvZs6K2RyIfTMOwwR59qWe5taykNg7uXEmnq+3yOSGm8SO6ZN8lXcedr0dBI7BPBw+cIl9nGPYRK1c6sFv3Bp70wU3bFr/JA97iL6imCVlva3gBGGHgWLL16dw5DrM8FoizYoI5J+8Yrip6oaBC/Lw5rmoRlGTUEB4oZbPNqa8NFQoDbEbN5C6BZGqNuSC2A/eDWPx/XZvenN+Kp2bhiUHuyON7ppG6osvQMbvDBnJHU/5nT0nbZU/GcWVYm97SZTPE7FoK5FlHnnLJlQtpUfN9egRNG4WaxRqGw1QdWqmP7RQna5UqlGUNcbbzB378mB/jsUDDeq8mKBv+J1yXUk5DFe+vfwTvPhwAb6YLbnvztm7knTeNZ3WdaWwyudxQ6dbuFthsyzEmqEgidUJBddZ3HOfNQt+rvqaL/75uMR4woIgPv2xuDStGtkTrle0rseIze/vrzyYLnE/L84GkGWVwhblz0j8BmCD6GykV4NtlMlvF2NZzsdG3zI+1U09+ADiJ242NcD0SNW7jY5x8suB0eqDoO01c3nQBl7Q7lX6jNAO6UQ+e0WkserY4hdyUcCJpcPdoN12bZrPYoWOyxyrG9CeW/8tV8NJ30geO4rwdIj1BQifnyr5iJPx1RgQkxfBKNg5QY3EM21dOBA+IEooM6rqYS3vLnBpLzt0ZioZRs14f9
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: network-system
