---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: network-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgB/7YWREYoLA2MjsZ+pOkGL3II9hW139VRjLWD0wbzWE+fpxSeXW2W5T0uDWxPghukqWGt4oo1o5vmXhExpQzrmL09FGPfIfcnhFJfCEdY7WWEaYgrndUIR/fmCZLO8rxzbAtZC7Hb8yfAR+YIDuLchyEMAh5uQqDxBKqwfKwnbVdN/HfmSXGBRxKZ62w0JN0SKt5mPz8cjpBs3DXn0Fk/KDFyUvgyM6VHkqZ/CLzLf2QLjK8neChEnPxnC4kXWvzsbH6+35JB0EH5K+4qY0stAtYZK3ysFt2wZ0z+sotxiXboiEZwPn51DMm5npN23UTny0idJN5cnQE2CVfn1+tZWTwgXFpDFQKVHe8UxKVXoY+WA7mPSlyP+oHgg0QZ6Wxeemc4rvejR+2uJHxfv9CJjKcPG3t1jWU59d1equQgP+RGMkBB56iTOJMuWMGaWYCoUmEkOYROjuihkMFpTBhwv0A4T0ZK09PraMvMPqXt71LAvESDOlpsGeOsd9ZW0PuWt9Lx4YswkjJwC+i2aur3ZduurZyV/AQPuYbEUxe4JP7xMKwRSfoamhUSCg9kTM+BFfFJKOW4nRxkRX7cFUXUp3Dhv1bIe+BlhmpK2dTaV8SVOwd2ekhziPK2ErSgcPmdO4gzIuDhT5MN5QXwS9xtVIAzIqZnrEJsxUtboVYmToQyqbkJcZvRcY+75dJFom0pumP/87tW4yNxeqgexBXiCaW/6v4RGqXiVc5RvGjtpX2xNkaO08iZp
    CF_ZONE_API_TOKEN: AgB2USn8jS5fFqn55Hqq2qT8tyDwx9B+61nucXwdQRMzRX+vf1xDp2rFqzIug1nkNqNoFu8sFmv9DHVauj9CZ6++947r+oNn4PNlBAwAqK7a/5UAcx3jjvBzKbZbDUGULiYzMEoWipiY9gnnIqN/SpmcpZd7MVPFkJUDDJba0kiyekDhLxR7xa2gMRjts+gGihqZWj50l6RGg7bu2iomeTTJnN57NhWAt8XrminTiQLaLe9ly52kEpR7YqSkSEasi9Pu8oLTU0rRnaI1N60maS42VWQvpFgpk2WEMWhb0IVRGUXXRKgqhxyPsbE9QfCjCXWIr/Z4ZQOBlOVd/19sKmH4mC4P8do7Cc6Y0tqY2i6DJWMlXpK7ErUPIxFVJBrtAIIkShzHUjxCTBgbwrIW72trcj0FGsPT4oSxDebNWWNNCW++K0WtmuLH/fsSVgzxDixZaWCG5LWPh0X++ZQTF87oDLLf+JWbKJ9K90UKvPwcLpJyvaMY/sfiqytx+bWmu8d90OYQ4yHzTYQMP4vhgd07qzV6i//cRLDr2H349YaymUyz6NWcEnNjZ0Lzr4gU30dCCyhiyLv5mk961dp5q+bwUOv0B2SRyYldf5GfmYecHFU6AJl1jOrbOkyJww1u1/QDnHeimXZ0XLnQzMQiEb+sOtYkwU1bRied6H3F4OP6TR/ClezlhP67IZRwFtOcaFWTsE3OevdMOdbeiWr66Smc7Ow8QrP2OHUS2+cqIZTrjU5FYO0pChLe
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: network-system
