---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: network-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgBZ3CU8EHj+9AaLwAdMDYIBd6u4GPX47WVip6khATP+qcnii5OByYj96ChNKdgLmAoTlzzaB3kxYv+qRTJc3gPlJ0RNbmidAwswsJxYclIyzRE5UGI+ajjDqKgZrt55zqBHvVfolUbmo9VYP0B498x9CRVwmIjMvLYJptsMLq9pd5IXG01GQsfkuo0NRiAIrCRkDAxFUOI9tNH4RijtU9vrOK4Hn9fEkdKoroYhzhJUUwj02m+T9sxbK+vCMb6OneBNv1/i92F5f3yZlbfQqTM1+/NgaJZ2T1j1bOKw4ut30SZruGv5ESBCsN7bL6nHxoPhHmss/e6NRTn/O1/oXDWFbVpJYjyXyT+H1tqPQyiELe5DRDHO17vpAU/6BetJ892rplQUBPw/mVx+TwBpoZx8ZlUzpqGwNgnvibfQDAMTuTfgg/1nfePiJIsQZMiwMmB/DZZnQsLsUH30IpR4Lg3FXgDJ5rTj1BOE3s/M/0+qlMTZFvBUQQcnINlzrQn2LuruO0qTax0GpYQAj2to7fEnKdO4wh2NsoWWz6HbxBps9REisH68heBZpzbJbFGmSMzsNXJwt8Bj8VlFQGA0Jd163HhWmY6UWOgBNwQGEYTxfycKsEeKu4Mm3oPeaISBe0UkFlIOV56JM43yASgFEF2DJIiJ7+BaeGJG+xg33VEeZhm+kz8uFND2i1Oi75wDF3k40DGJbIfm9YNvP45YMuOl7AkW6evJUscNEe3XnW3DJIvymfAuAs5m
    CF_ZONE_API_TOKEN: AgDFmyIl/IJJ/vDWk/+0TX1iBW3z5PEiP9dWbKGf9N/RKsl8ex2ujSzjAKV1N7OeFN/hnPLddKB4TMppaC4i+HNvOLaqNb58DRHG4exGwMgi4CWXmaCNnwCSidAOXd76zgFu+dsuo80MnESh2GM/+wBYCaWzxIZ5aDixoyRkJTLgyRD8p345uEb860xmdcGzUZ8pKhBTNHiYU6//AEB6etQm46QvlWkAwkgOwEZIewVOe9+VqTNhU+4nzGj9Q3kLiBUwXj3/45BuEnvD08TtbtkROSW+5UnnQfxhY5sQIQ2fszqw+ZZ+36RklAmHFzEjA/6KroeNnM8fOpkQuQwDJQTvpYcXGlVHmOBe+MP9Kqv43i8DFs9K5y7pO9MaUbBBhnqe9ZQwEr3eD0yepLoK2Ne0X5Lp05iHWKtyMemN1h2G+t8CUVOe/zfWUVdIEwBruzkVYJvgS6ytTGypLDuwbCOwQCwLgSyJd+dpk5PbkYI2PETZQ17AAwyrb57+yI/ZOWOBo/y8C5M+JuJZh0VZ6Y2F4JEUzz4CtmIOlrk3FfHHDiTX/wuImyBuq0oU8i3P1jvkWxavNOUFN3CSWfysaHWgA4ptC3Kgi0iaVaCyLk7Xv2vXy9uAYhD3cxfsfxaAVFdb0B43NESbWwBchKDTK95Ydwv5fzUrhMXSAt/3HYkkkfS6uvvZC1jZ9qsP9PCZ7Xd+CZ9V+LQkYwWdde+H4JAnbDhxigBUnubCg5nnkl9/8bzSDJY+wjt4
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: network-system
