---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: network-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgCoQyOyib1QLKDwToFCcDAOoQqFRr6KJ9NS2X/eSfFXOGRnOpnHjkF9hOHuEODhDZDhfg3x2gpLXnSEP6LWGcQOHh08QvdIH0sHybAeveRNswtdgyk04XiVqYhNW3o/hoetLJL7ouxMwlka98mPPrJuWr5Myv3ChLS+Zpjl/QqD3lczJpY82e3KAGpo5h5H2AFtA91NRBPS+TWI6ylc1Rn3hfO/UiXQCcgS4ce8UsKOyXLtvX1lk4Qyu2kYUBf4eHl1I5yEulxGZq5rA675hCD18s+dK1/ALGmaw6H4Y76XVEOAuxLwwqkm/TugKTrjgtYzYR6MfG/S3vApEObgAiS2v7P/dIi8cOjE+V2tJyKQHw/90Il0sCVfS8+WgJMVzVx0MuCsKyPSI8oCrhL3CwVTUQidM3OTxrI3kTo6JX/peGfRcYL68f2I5BbWUzShcjsl2u9Tn9iT90SbSlvqjee6O+YMg06/uEnU3yyk6dfdx4+tmPO4ycU1vC9q7zYNk2Kt4o9DU9YVgy0f3fML3ufrJBABOO9Q03VQHK7UYXuf8UBWkAHq++9/BJI7dMiZKLyMLBVOL7qHFHCF2COitDxsdRM/nxt0vNwJB7vxcZm+fmNgbqcrLgPGf1hP3VQAMlLeml/f3glnXEU7ZDUfQtTbd5KhITq/oCT1Wzc2ZlneXDrut1s5JnEBNhOt/K4apEiTglia2e1xDTwi1eZQQdf0Z/W0qQnvctW8LNhgkRR9wn+pZfxqWWLY
    CF_ZONE_API_TOKEN: AgCshY7bQ8K1AUAuXmUpX8F5zQX2nOA80X9HBHtqZehXI4KA/UPYhj/BMf9ndYRyOs5j9EIh31UftZqvoVg7pFCPfF6qpO+YVk/9Jmf/h+jKrQW3Gbtv4olvI/AlQZZ2iSYXfjz0gnzkNByITmRsEFXENdX0ism4samUdaHRjUfrsBu8PnbXMJ/brEqwLVVyL9EEgftm9s/zsa+Dcj2EfR8dEnA5MH/3CZTkv2YHINRswc7BjR0sZjd3tNBvt9nQv/KwaiTbEZ9k3wHWvQSB/fv0nAQf9kDVMD3wV2WlGphex2qn7dfduMJKxPsigRYvorT7mXjyA32lf1Pb3ia8IqfMSJRaVEqPX8VFR+AB9vUkoj5VwlPtQ8XI/fm0iI7eLJDsm8pbdPSA8mbtwwsL0xjPlvsXVcYesZyQTkE9+sw0BzswZ0RL1cdma62yuw3zebsDeCTelj2clHlNcPqBacdd9bgyxD29b0Wn8gt+7p1QKU8brbevWkotHHG11/eERSqdlrxdVrqRN+r3HeQdOGTPrs2ppaFsybhavYDvB9GKk1HTVwEAX+c2UJFKyrcJZ1k86pSJ660ybVtyiwEGFtIOe1FbENT8xbPT158CSYKrFtHo1HQoGBPtL/HJ63rReMqYqkhC0cHdSNRHloNdC7ZtUxUk75I7vi3x9pxV0GtVdps6ixKgcMph0aqQqqIR8qwtQjVcrOgQVqcOHPpEM1TGPbIdAXnNfRJWA1gLSMemAToPx8WPRIsK
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: network-system
