---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: network-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgAPh6WMo/hZbLzut634Ey6z7TFjknHJ2XZoOEOAef8RkEAcKKYV7cQH7hMzzU9hXXjHqgm+V77qZXPqjP3oeqrqckB2XDslDC6FrhIPmSSQmjzWx5rPXuSjoYQLppZz/q3apRjz0NKD3OGdWx/6EG0L50vFeevf9nqRiJQLN1gi0Kn6F4HGkvwcO0iOWUImvJa5RxyW5FPVz3WFuQB4HdPS6J2V3jqE19SRKLfblRNkMAGpKT+rKhTdtOtWliagO+RnS13YQqexImv0oow2FeBHI149HwZ4HxkIErus/A1NPj4XI5ngTL5yMAiuVN4Y+MJo8We32cwTZcDijVCyvDqo7oySneRpQpCsVy5UgG1DSLajDYG2WrIY5yOCkxZSsE+tyg7CLHmyFoeLd6119aOC5Kh8AgAZ7QRePr5NtIzcNNn/plfzF/SjXGSp5uAxdJMYDcopBV7T7gkoZdCji4bHrPSVxwmCqXS9/4HZnNiCuqT8PKF6VdzKk91iY9u+JNX5kQ6xVtO/tAYWQTqomREjGYXFNV0T9qHZEE1fvMwULpIn+iYoB8cPR7UCwQYlZf7nX90fc27EhwJBB/IJRNtHi1gjYp8rklr+GXxlzPPxuMDbFEcm1aHJd1/N1yNPTGRCHTjmqW3UcKjlo144KvADVX9zFg6hDgpWjHqry5F4BXJLrg0k2+3tFND5ofrsE1Wsw2gtyzOBEx6VLeoIRxQQRGO2ATmLY7qkgnlyuWszDE/qXFi9bTFp
    CF_ZONE_API_TOKEN: AgBi54+ejdqEmOpk9t3g+e72Ka3bCluL3AwMrFl+oH2/ntw1WAI3nsyseCfTnOZrisrwMqfPvyqnPIYHHn22wmNX9D3czXN2jcoeFJa/vlizFP0nrpxycfm6HqwICCxt+n5Vw6NiGjiy72onFDuFEw5V9tDfiZSxvZiy5q35lhhnjZVFNukaKqIqXesYsOy1pGpE7Cpnf7xEOQDvhpZDFgKw4OVEiAq/NdatShGFyt66m13mz4A6qRMDzFsgU2cNOL6WnR+VVP0RhGOYQ7RFbaUaxIYdtfip/VEqCbkFp+JkfsL3XRCcVNdYZrcZ3P1f0HnaUURpQSEJ3xNOUKZIBNulwrf6EHGsRiz+8cqBlaydhKR7NlSgsqpB4MLzxuCxOvfDXQZiyJcKj+ve7aljRJCi92cCFSE+dYgL+y1TPJhQ7zeqzveHZNI2tNM9HWDZCcMo9SYqjwmc3BD+V1u/C1U4TQU3BLP4DVQ31lVdmxK45PY2FuUJI/r200J09iu3vj6b85oQBALRKyD0jjhaE5ie2w+DsidR6wM0zGN+VFFeOmJuXHpbhx/xeDK6KkPMOBgYZR+YsycCaHJvyKb0VIVEPq2LrdIZk1BVR8M6TqLo5bVSQeNOTWwvE8uBaMiK25RRCGSSmO/up4SdwVdPZaRcBpLruB8ueDq4rsKX6o/EARyaYa104zXVNlSJ2cSm0KFU7k0Tptd6Y9Fo+WdQkcsTCygvBffI/l6o/s0+iBOT4TWol3EcZF0X
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: network-system
