---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: network-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgCgKaopBiE07LxAYJ3DapSLwI4LykdneN8VJgC7RnCVQXVG4tmlAgEKtjkAIyV4S/Wyo8FUKkFjoPCAvG7F2U/CUuGYNp4o3H8QmUu/xAaL+I0uRYrFg4aY48MgneZev7G12GDUxBo0fB/iqrY6g9ewwMQfJglIDtgOMaVGYQ53PO3aFp3G7iRZUiRE0v5iEEo5il+SGyNnE7GYyolED9QC1O9EM6bLrbuFFLOeLO4+3Yzb70Y9BVG8E2TGJOdVWXZTma4W14dv0PqWnYG78UomfGbJ1wq155KdtaJJ4ANFe4t6CslD9ZiF7R+p2UOCdIA8tZmiw/yBhgDEpFGKQj20lIC+QjYioVdZsmNn+q+J8PTIq9B0e9sSATxw+IPvj+Z5kBVza9azkfvc7hASr/8cxSAZ52oAhaovEr7btic0tYrnbSjr8+6FdnXEMhqjCyyEMTY1QTKfCl8+jm8XiR3wZNoFpejZpEFYNkqAzSEQz+aZ5tg9F+C1xNQUnI7oYWK1udT3vrRYi/YOIjtfRe0JiqKmGPox6IChGJNGf9rRZ2BtOOFoTt2QeWXSA7CcJgFwMgpA3TgwWrjcJ4yaP8ZKjZOLU4O43BGqVjeNgqdyAH0aK5qNKB+9bVtY7qMlLXyKd6zMyWIUVEtwOdz9dZPt8QiJWfe5firB9RGPvAoqIfers4ayjc+c6t1Fm3ultZYhDOqeSTWDvySW1EJckXxm3PkS4eyyWMOFLqsCU0zNBrkKd8kfpkgn
    CF_ZONE_API_TOKEN: AgBhCPuU4UNAFZQM5EA58VVeZe3iDKBwMjxsKuqMnyYEG9h9ALjpKszkRyIvm241nPBm0Z1qFdXrZ3jGfwnEoLgVTNy0UwyQXdoGsb90Og36aYwHOdsll+IYvJU2q6z3cBP19P+wmM0N/vLey8oi44K1MNY7mEVT800tcPTo/ymEAyYIS6kYGnaJ/2vJs26mBGaCUzBHHBENCAQfBCemjVjMg0gl/pwLfReAPv/+/dIwLngkblqkghalXOQBx+9I8nB7FRLPd3j0YSYXE2W57qRhnjdH2eSFESm7d/LKcOS510u77I8JOIUGVD3KLerQSk3LcsTlJpnZ/CTxKcQK4n9ghE1EvCYuSMoFWeLjnnQBCEllUTvJbFmp7O9fKSDmXieA37J53lFEnOaNYM+rVyDTGyZQlZ8i9ZfQkefD7ABCsl71+rZbMn3GReua4NjtGdPhav5P8xRQiShQ91IHsO7pPrbDVBi9IRHSZcrQBRnRnYo1HHSB8SJhLjpzZy4JHnxB+lvW3SDCY2zxWfQnrV/4HkTW4OCkldQCALaJbZkA4CyBRUUuzJOsC6KAkMYZfQ8Ws1zE0MrVK/0C2QHmu3xyzCU1FLqlBW3wvP6ZtSYiPeBJhT66Rxl+PIWDU1clKYeonMPb5CvF9CNSdgvGLFDgD2QLfmijajzAI7f6XKqAx+a6M25LECbxKQhD2P3HLgTKdo2KzWXnhUuWhdP/NbR28NvCJIdN00bCD9vU0cJ9eD/DFpR2Fxph
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: network-system
