---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: network-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgCGnWPXZoTOPSFaNz1q37rHnOxpEMQgOW86c9rEXnOr5PMFyCdcHnk2lxFb2IwCQhxH79Mjxcb9c80+4iwEuy13Zu0UGJQ1UT+x4GdzqRD/VHoTnG0qNoVL513BADc6FDzexP4OAedVOOmF4VQXCf8VV/Vj2ovdkufz0FE0KyMPevUg3lDAIsgBkd38+m6ugyVnJ5P8VACc/hSH3Ax6kU7g71XQsmmIxW40sHpvoL87EzKsBP33hrA8B2TGfF/ojwYScR3GXM6Hjy6Pl60p65n1D1568vLoN7OkcIRf+3Ki3Ta1sFpR9H56npObXI3OmcBtG5Rc7YmPYsW4a1R4eBJ2nRJ/JkJxtQpoQv7uPFrh4UsWlzyB+q6Add2JT04skhsMHlqkP/QzBwv/SEDJSxjlD23oDqjCzCbwjKkMZwbFIMSlkTg2ZCNMcAAKPAauQbYXZ/N3SsWNLvpQuq0slV0SjJEYPUSwmz+M0hMqw0wajCzhCUDh5lv0+eAwOhaxYzSNh0Y93m6M6q0u07pLCySKHb0q7RbEGnwLS1Pm1BlOoJfv7J6N5a1cafJlMofPMQaAUrbmJ+kSF9RwdXlV7gp/3OOjG3BRpHNlHVU36WsFDBSQ8oF5EJmiB5+yu8tKwnXaGnLHaLJJMVwuph6mT1HuGrU0OZPgl/udve3aT1Mx8if/Vp5+9kkOEGMKC3ymx2ag6CxA2/p4BmjTxx+JHEzRfZe5xDYwi2XBjeRA4w1MLmNXOBV2LWIW
    CF_ZONE_API_TOKEN: AgDE7mC7bQp6r1v5LIfCQIe9+Zdb1VjIcizBkgL4EBlmy8aO/aUiEeaEXvu/Srw5gu6DpGXJviCuVbho0721U5a8QM6KwiUXdynO0EmMgYzMitRl7iLS4MwAV+tIDg9t+Oac7SDBw+E/FLoVj3Wadd0vvgfzyWrPXk0R5ILPsOP0fgLOxjI4acaLbTreg2cigKRBUkThGZpK49x7deRr5MByCQlFZo+yM7SaJxvN+emzulsuyes1baL6uNLuSJrsHme/lDZ3h58V7DBvzig/vL97DLFA91TtFw6zgeEpQu8hRGd4TpSPjNY8SnKrPVK+cUKdtZk34QYTRiLLslCpH8bATSFC294xXOxxutbWRwiDw3a796nCjl7BpiCdELVVXs7NuVtZXFj0dsw8XxKPEp9/flhACy/2hD0CibyjyYKZ/A8tH3fRgbpdfmJuiy/FJDOS0Hf7wBJIOcAV9t/+sCOs3eQsLEO2gqL1LkKFe9CtmQYFReyKrTdVWuBaebkYZoBRxq0ee/lYYd8yvhX5qE3ofc8h98mPaYmsbhEX2z/R9K/QRpzjszebQ/qAZgYPvHvz9mhV3O7nr0MwNVGSjhCEKamlGKbpEvd28pb/fFV0gOgbzdnNvMstQu5HBGzhr2JYFxlCh4y6+80VuMJcOkiePck3ClNzmr9PyJsSEwwx/QZLvVmFW8KePb+7314GiFmJkWIqNSLdq+ZwfGUUwxpCjpe6uNuoiTDCCAgyC96oKkmUk1FBh20+
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: network-system
