---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: network-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgAWrJtYVxXgNUfbrkS6wSdS/x2JbwBEVoLcV8fDA4MplO2DM0xZYAZGONPGc4JjTO+TCSmsa5aXp2AVyk7wQ4MvoATkQcZucAobhiSCyomamk0F9qaOu3bR58LK/Sm0FrILmjndgVx999DXojqcxufzk4hfH7t4MHgeRSywBTtRyMp5domvaCIQLhajJPMP42mzFuQF/Sfb8FVhNk+ZTTK22NQpCxDy3Q69lUkPtWJ/b09JB5elMrXT00L1h07JMbLHuTzn4tj3/Px3BE6JnBO78Q29+0K3qlilRkYgiWDbJFmJXGOuUs/JhjPu1tLOYa5muirQLlJcwYYAJL9l8jxg+UZ4FuPCkrlxZ5gs0SM/xKpPrCiV5HwVibaJq5y8/UnwmKbsj7pW1zN0VT7fkPi1vZwfei70g0+k2mxJuKzNsyE64KouWp7u24z6noMZPWD8A3kPYCQhEbA0t7wSg6kTQw1RdNtD+0idgnNfqISTySIQpUjmNomU/IOC/q6ekn20SSBh2Zkjej1jNBF80GabYZ7RohFepccpkB9K7KcFacmg47H1YtnDB9AKzK50nd5tDXUrtFcqz4xZY8FdvC7lYPOuj4ZOkIgivsBFbv2PX529nMpmFWNcJcSZw2f03ihZaJwjcdzoIPkKl7A/gHeM0AvFGH29UBpayza0+JaHY7kZJE8sJ/JVOoiFGCXZVvlbo2BfQiNJAoCTZllzjnRTCb7Z64YLKsFpseMhHpI4gIPCcOUpgq/Q
    CF_ZONE_API_TOKEN: AgClCy9HwjD3TxWGgd/EKZK5T17ssmtR3KeKplzYGThAAnfGnFR5CPYsEUaPFf7iah71sc5T0tYx0zwhYGroKwws5VXv+EpzZz/9hlx5gOVgq8Kmdc/o03W2/pUbfv6spIDLgCf7uDL2OkYX0mmPZ9KdaQLfWUmCpIcx9tOKskzt5jYufZbRvKG+jVQe/njefFrNV7JapnhePW+eL8HOUaFeBz2KWecomH0Z0elY6niY21KLrduI8ZTxy/BYcfWC2c7JonbRL5GRE5WA9QJYe3h4+qgXTZWhB3uwdD+uYiyjD1TsDmIhQv1xcQOlpBe0+logaZKcKauTimrntU9+NKKECPIX9PgKayFLQCIiuIECAwCDcoKXU8+GB8t8nZhQc80i+okztjkcw0jc6KyPVuMTp+eGhC4BNhe4cBA5wZ4jh8YekgdQiKvJOXGZsXMOvk+yIEBRVy6HAe3HYRhGkcXqFhZjOJz4KqLMMzE/yxUqpPqQstomCFIp64u+Z31Dck5sf3fdGAy/kmAXWSOexKacw+kUb/oLG39nkTovyx7YJmjVlR3wJUalIwNHRjg9evw/ifSHSrdPf+qHQEfVNg82Q41vts/ZYovGjaoA3cf2NqjQfRZYMRyzjx/NZsc+x+gfA++xjjQWRX5K8Qil1QsgcTH1ZER+eWfwmX3g+kFszwxyOCd8BbsqFWjcsR79CXUq+7Ia8nQYw0kKWwEFzureNdJOUhZXIV1GQ5sF4J+ML5COHfRYVWTb
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: network-system
