---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: network-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgC7eaUdLHhMlP59SaUONWlUclTrImiCrMqnAb8wyXwEOr3cTTR/GQcYH01KmgNqe8tXEUTvXyoVOcLiu8be9Volze9bkaaft2rJpBCN5pvSZP1I1/dQjxYYrx1nPE/jCqY402zrM7rN9iLRyU4pc0moz6F3iEE2OnfcWaazRbxpJc5Mfd3VdN6LtC9LDvnM/AEXAo6efquUW1hAn4l7e7LlrmE7NARq9zYDJkbSaNWx01obFVKws7QB8ni2t35QBx6NlbV04tFBwDNvXLcCxhvo/NP/jTad9Sug5n1Q3DqZTgwrGRp4OuKX9qaOA5eYCMyq8KV4twoEgGoASSZks7cyq1sn6ZtN/aSrgEkhtkNHZaulGsyB0GucPmEH4T8WRXyVXa++0VIeBtH707RXy6NGursIjFMQ//ZzqNVYelTnWLmouVdOyVabjpn4Iv0kP3ws9MS12sORxSk46Uoz4wQ/8yWIBtbxMqI+ElZyXIxtApG/V70rb5H7NbpDz9KBZFcAt1n8Z3VnnIs5qD4Fsfu5XtcvOMT3dbbmtEqyRgJL/ZeOoPNwL3J4uyTUGaw74Ehn9Lz4wgQTWcJPP6YlenEsNsfeOVrevJL9R/wIyPMBxwajIoBAeBxtOr/HWm2CHoxpzmhH8bg3XPcIjKteZuAkXMuK37vDua1RYG30zDxPGaniy7HPulzapA2CyfFqdLtoLbOw/qh9mXv9FBoId5U/WjAW6+CFiGHvsGTEkxDYniNNx4x85ZfA
    CF_ZONE_API_TOKEN: AgBcQRPa0GUTstnKL3KP32cuo4+wqMWm9o/av8w6UPXPTbUDXdt/fLAOgyELAwq+JI7QuPqnOdWS2tlAndKLPcDUts30flk1sFBL/sQez1VQgqT30W7hrHpvPeZ+Z3BtkntwxnqcLv4ZI03LdAbPkziXevu/D1qwcjCwPXGcuVNtBXlWxW7qZmWlPoPvanG9FwCSBhH/A4fcWeJbh/GFNW/WgxwxrZ3qd+kFXIBWgYrL5lBTmevSOQMbCxb9lupSlwRSBR+m4kCSWf+8CLkAdU+kUoUmgtE7OWUHMlfxopIZWML/SlwEcZKxVYAwAgWk7iwYs9JZMNn3QXG4JOjE+NRELj9KuIN4qsF7JyyW22n7NV+IeJWGK8PgrCImOoPoj14maWogLCOGdOUtxeyq8s3aqLx1QH3Aq89Ae50WTZEJqV156c6IAT2WvOpdcrCu79SBL/B1ZaYqmL1mrjdvknR3yVDR7N8ALGv55dimO8uHW/qlr17UBcl8pJn+GJGyCcdzNvqcWD62buaIVbUo+y6nXMbh1peqe7vQ6XTGI2B5kJt3hcogv5Y/arkMZa2NcwQrLIPXMc3cHQr68cEz4Wzwgum7K8wBpsHgsa7AXAWBNsO8vjPxFxAOzFSgV/Sbdb6+ulVkoAaBa4o5HE6YijdLiEKbeCG2Gg2SMDiaK9SrqJC7oXqJP6c8onoP4FQfltoSgNZJi4lbMWzQoSnXUpdYlDNKULscFwdieSRDLdKYvhvNkU/qVaAd
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: network-system
