---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: network-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgCx5fAZWXfcpwue3QO6jsSyC2kNy9QW0b6u2JaIhKDFgMBwF3KpudA4Z+qjEx2fErlNWXYhnyMa2wA+Szb2ei/MaQIggjMHIx6upABh5wEvN/TMUfVqX7HfWOO7d4djIG2joNqJHriZfBdwRezQihjWwA+Yy26jgewPHiohzBXOwBM/zhNSzj2rMA1ZQD6L16MFqYKuazP3M3SvTNi5BC5R0k+Hy+ziPi0PnHitTExLZKgwKviLWW0fBcelwWYAOoVQxQvGjxhsMJNBoVOWVRqhWN1r7OL5zhwPeAag88sgXHx56EZ/12J7mg1ya6MsidlrtFrupJjijMxRVySIj1fCFhJo5lsOP7Lc/tqdjjCch8Jxbo/0RiPZXinq5tToZ8mRN2AItqziSr7cDTt+1JfZ/4Gtb4MtorD2y1y9kBahF+4JWacadqJ7Nhy8ucnkRn+2tWgammg2eyMxhVraQ1dL6RWBN2TKvXFL01z+K/fHSbTn9Z7NlTSsvo97PCgBjMaA2vba6znTsLJluPtUbj75nTEzYvsjHjMfFjobWqhHMG0dBLz4d4QZAaSKPj7xHT+Y47FeIzQoQ1rB5Kdz7d5wk7adMrs9BOfmDSVvusAPBfMktMJHeKevqfZu84cjo1tjRGej7fycZufeNVahSwA13lcWg0JKahgsQp1cxNcqAQABGqQijJqYEiZe9ray1UeE/AIKmSa14tpo6eX+0wsOByUA5YyKJEl4L42sahTIXUGRXcxFku7i
    CF_ZONE_API_TOKEN: AgCDtU6QR8r6vFyIZUczoyLTr9rlzYRAJTUkHMtXwbPKwKSgfr94PO/g9LS3UnVxE4hy8zc5zxfXySpPT7PLdvGiQJIXxAPTruzjg+XoV08b2s5k74T4SP3k6Kma6qpOcx/SsEqlDkRO18JxNlOeNYorbWccqZvkQ0S+AstDKMHgYlYf7DJhZVZ3RigZAFI/2s5GwRiQE7uWtMTNnHrh6777n930EcCcxQlno98IjgOq49pEnjXip46to4L0rQX1Ee+GyWJIfH474WQYz6tbZ9xIP8HTQ+gLcKBOqosbZ6a7HmCibPeuuX/TC8VV13MvfvA2uH2yZHI83B/7T74D3fD65nNRNuvJzBFV+bv2w2xR2PZRMsPtn5rXv3OOUprAYIDiuG9WQLqNOIy5oBBX7+jpHMursYyL5hDIf8EFUGh9qJDO2WAcRt7AS5gpm0OQoupIpDWA5KVT922ecWw2/shFcuXoAfeBwKKX4aj215YooMRbuFaAWhvzIsMj3XR3vN88be4QpvepNs1i0yySJ0ow4sZCSe6FyBgaDfeGVkOL8/LOMAcxetXEeK9EzxagYmFaZFQYJ+m92Bx1ll/I/r2IDHkKVyZDjus28w9yntlKTzYkfeZMwPBcqJESXq0xtybhrKliVD6hRc5WSnpzrH7MKybZkkjciY7XIPZEJXo3OcH6lI0De0jyob559AsBLsVeay1Znvxqa7JfqzijuwkM3TlHXCyZdogip96Dgl4QTQRGLROFjL2V
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: network-system
