apiVersion: v1
kind: Service
# TODO: prometheus annotations
metadata:
  name: postgres
  namespace: database-system
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
    # TODO: prometheus port