apiVersion: v1
kind: Service
metadata:
  name: prometheus-headless
  labels:
    app: prometheus
spec:
  clusterIP: None
  selector:
    app: prometheus
  ports:
    - name: prometheus
      port: 9090
      targetPort: 9090
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - name: prometheus
      port: 9090
      targetPort: 9090
      protocol: TCP