apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-vip
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
rules:
  - apiGroups:
      - ""
    resources:
      - "services"
      - "endpoints"
    verbs:
      - "list"
      - "get"
      - "watch"
      - "update"
  - apiGroups:
      - ""
    resources:
      - "services/status"
    verbs:
      - "update"
  - apiGroups:
      - ""
    resources:
      - "nodes"
    verbs:
      - "list"
      - "get"
      - "watch"
      - "update"
      - "patch"
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - "leases"
    verbs:
      - "list"
      - "get"
      - "watch"
      - "update"
      - "create"
  - apiGroups:
      - "discovery.k8s.io"
    resources:
      - "endpointslices"
    verbs:
      - "list"
      - "get"
      - "watch"
      - "update"