apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-vip
spec:
  selector:
    matchLabels:
      app: kube-vip
  template:
    metadata:
      labels:
        app: kube-vip
    spec:
      priorityClassName: system-cluster-critical
      hostNetwork: true
      serviceAccountName: kube-vip
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: node-role.kubernetes.io/master
                  operator: Exists
              - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: Exists
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      containers:
        - name: kubevip
          image: ghcr.io/kube-vip/kube-vip:v0.4.0
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - SYS_TIME
          args:
            - manager
          envFrom:
            - configMapRef:
                name: kube-vip
          resources:
            requests:
              cpu: 250m
              memory: 100M 
            limits:
              cpu: 500m
              memory: 200M