apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-vip
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-vip
subjects:
  - kind: ServiceAccount
    name: kube-vip
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-vip